Coloradar Library: coloradar::ColoradarDataset Class Reference
coloradar::ColoradarDataset Class Reference
#include <coloradar_dataset.h>
Public Member Functions
const Eigen::Affine3f & singleChipTransform () const
const std::shared_ptr< RadarConfig > singleChipConfig () const
ColoradarDataset (const std::filesystem::path &pathToDataset)
ColoradarDataset (const std::filesystem::path &pathToRunsDir, const std::filesystem::path &pathToCalibDir)
Public Member Functions inherited from coloradar::ColoradarPlusDataset
ColoradarPlusDataset (const std::filesystem::path &pathToDataset)
ColoradarPlusDataset (const std::filesystem::path &pathToRunsDir, const std::filesystem::path &pathToCalibDir)
ColoradarPlusDataset (const ColoradarPlusDataset &)=delete
ColoradarPlusDataset & operator= (const ColoradarPlusDataset &)=delete
ColoradarPlusDataset (ColoradarPlusDataset &&) noexcept=default
ColoradarPlusDataset & operator= (ColoradarPlusDataset &&) noexcept=default
std::filesystem::path exportToFile (DatasetExportConfig &exportConfig)
std::filesystem::path exportToFile (const std::string &yamlConfigPath)
Public Member Functions inherited from coloradar::Dataset
Dataset ()=default
Dataset (const Dataset &)=delete
Dataset & operator= (const Dataset &)=delete
Dataset (Dataset &&) noexcept=default
Dataset & operator= (Dataset &&) noexcept=default
virtual ~Dataset ()=default
const std::shared_ptr< RadarConfig > cascadeConfig () const
const Eigen::Affine3f & imuTransform () const
const Eigen::Affine3f & lidarTransform () const
const Eigen::Affine3f & cascadeTransform () const
std::vector< std::string > listRuns () const
std::vector< std::shared_ptr< Run > > getRuns () const
std::shared_ptr< Run > getRun (const std::string &runName) const
Protected Member Functions
void postInit ()
Protected Member Functions inherited from coloradar::ColoradarPlusDataset
ColoradarPlusDataset ()=default
void init (const std::filesystem::path &pathToDataset)
void init (const std::filesystem::path &pathToRunsDir, const std::filesystem::path &pathToCalibDir)
void postInit ()
Eigen::Affine3f loadTransform (const std::filesystem::path &filePath)
std::vector< std::string > exportBaseDevice (const BaseExportConfig &config, std::vector< std::shared_ptr< ColoradarPlusRun > > runs, H5::H5File &datasetFile)
std::vector< std::string > exportImu (const ImuExportConfig &config, std::vector< std::shared_ptr< ColoradarPlusRun > > runs, H5::H5File &datasetFile)
std::vector< std::string > exportCascade (const RadarExportConfig &config, std::vector< std::shared_ptr< ColoradarPlusRun > > runs, H5::H5File &datasetFile, Json::Value *finalConfig=nullptr)
std::vector< std::string > exportLidar (const LidarExportConfig &config, std::vector< std::shared_ptr< ColoradarPlusRun > > runs, H5::H5File &datasetFile)
Protected Member Functions inherited from coloradar::Dataset
const std::string getExportArrayName (const std::string contentName, const std::string runName) const
Protected Attributes
Eigen::Affine3f singleChipTransform_
std::shared_ptr< RadarConfig > singleChipConfig_
std::unique_ptr< SingleChipDevice > single_chip_
Protected Attributes inherited from coloradar::ColoradarPlusDataset
std::filesystem::path datasetDirPath_
std::filesystem::path calibDirPath_
std::filesystem::path transformsDirPath_
std::filesystem::path runsDirPath_
Protected Attributes inherited from coloradar::Dataset
Eigen::Affine3f imuTransform_
Eigen::Affine3f lidarTransform_
Eigen::Affine3f cascadeTransform_
std::shared_ptr< RadarConfig > cascadeConfig_
std::unique_ptr< BaseDevice > base_device_
std::unique_ptr< ImuDevice > imu_
std::unique_ptr< CascadeDevice > cascade_
std::unique_ptr< LidarDevice > lidar_
std::vector< std::string > runNames_
std::vector< std::shared_ptr< Run > > runs_
Additional Inherited Members
Static Protected Attributes inherited from coloradar::Dataset
static const std::string poseTimestampsContentName = "base_timestamps"
static const std::string imuTimestampsContentName = "imu_timestamps"
static const std::string lidarTimestampsContentName = "lidar_timestamps"
static const std::string cascadeCubeTimestampsContentName = "cascade_cube_timestamps"
static const std::string cascadeTimestampsContentName = "cascade_timestamps"
static const std::string transformBaseToCascadeContentName = "transform_base_to_cascade"
static const std::string transformBaseToLidarContentName = "transform_base_to_lidar"
static const std::string transformBaseToImuContentName = "transform_base_to_imu"
static const std::string posesContentName = "base_poses"
static const std::string imuPosesContentName = "imu_poses"
static const std::string lidarPosesContentName = "lidar_poses"
static const std::string cascadePosesContentName = "cascade_poses"
static const std::string lidarCloudsContentName = "lidar_clouds"
static const std::string lidarMapContentName = "lidar_map"
static const std::string lidarMapSamplesContentName = "lidar_map_samples"
static const std::string cascadeDatacubesContentName = "cascade_datacubes"
static const std::string cascadeHeatmapsContentName = "cascade_heatmaps"
static const std::string cascadeCloudsContentName = "cascade_clouds"
Detailed Description
Definition at line 10 of file coloradar_dataset.h.
Constructor & Destructor Documentation
ColoradarDataset() [1/2]
coloradar::ColoradarDataset::ColoradarDataset (const std::filesystem::path & pathToDataset)
Definition at line 9 of file coloradar_dataset.cpp.
{
    init(pathToDataset);
    postInit();
}
References coloradar::ColoradarPlusDataset::init(), and postInit().
ColoradarDataset() [2/2]
coloradar::ColoradarDataset::ColoradarDataset (const std::filesystem::path & pathToRunsDir, const std::filesystem::path & pathToCalibDir)
Definition at line 14 of file coloradar_dataset.cpp.
{
    init(pathToRunsDir, pathToCalibDir);
    postInit();
}
References coloradar::ColoradarPlusDataset::init(), and postInit().
Member Function Documentation
postInit()
void coloradar::ColoradarDataset::postInit () protected
Definition at line 19 of file coloradar_dataset.cpp.
{
    cascadeTransform_ = loadTransform(transformsDirPath_ / "base_to_cascade.txt");
    singleChipTransform_ = loadTransform(transformsDirPath_ / "base_to_single_chip.txt");
    single_chip_ = std::make_unique<SingleChipDevice>();
    singleChipConfig_ = std::make_shared<coloradar::SingleChipConfig>(calibDirPath_);
}
References coloradar::ColoradarPlusDataset::calibDirPath_, coloradar::Dataset::cascadeTransform_, coloradar::ColoradarPlusDataset::loadTransform(), single_chip_, singleChipConfig_, singleChipTransform_, and coloradar::ColoradarPlusDataset::transformsDirPath_.
singleChipConfig()
const std::shared_ptr< RadarConfig > coloradar::ColoradarDataset::singleChipConfig () const inline
Definition at line 22 of file coloradar_dataset.h.
{ return singleChipConfig_; }
References singleChipConfig_.
singleChipTransform()
const Eigen::Affine3f & coloradar::ColoradarDataset::singleChipTransform () const inline
Definition at line 21 of file coloradar_dataset.h.
{ return singleChipTransform_; }
References singleChipTransform_.
Member Data Documentation
single_chip_
std::unique_ptr<SingleChipDevice> coloradar::ColoradarDataset::single_chip_ protected
Definition at line 15 of file coloradar_dataset.h.
singleChipConfig_
std::shared_ptr<RadarConfig> coloradar::ColoradarDataset::singleChipConfig_ protected
Definition at line 14 of file coloradar_dataset.h.
singleChipTransform_
Eigen::Affine3f coloradar::ColoradarDataset::singleChipTransform_ protected
Definition at line 13 of file coloradar_dataset.h.
The documentation for this class was generated from the following files:
include/dataset/coloradar_dataset.h
src/dataset/coloradar_dataset.cpp