Coloradar Library: coloradar::ColoradarPlusRun Class Reference
coloradar::ColoradarPlusRun Class Reference
#include <coloradar_plus_run.h>
Public Member Functions
ColoradarPlusRun (const std::filesystem::path &runPath, std::shared_ptr< RadarConfig > cascadeRadarConfig=nullptr)
virtual ~ColoradarPlusRun ()=default
virtual pcl::PointCloud< pcl::PointXYZI >::Ptr getLidarPointCloud (const int cloudIdx) const override
virtual std::shared_ptr< std::vector< int16_t > > getCascadeDatacube (const int cubeIdx) const override
virtual std::shared_ptr< std::vector< float > > getCascadeHeatmap (const int hmIdx) const override
virtual pcl::PointCloud< RadarPoint >::Ptr getCascadePointcloud (const int cloudIdx, const double intensityThreshold=0.0) const override
virtual pcl::PointCloud< pcl::PointXYZI >::Ptr getLidarOctomap () const override
virtual pcl::PointCloud< pcl::PointXYZI >::Ptr getMapSample (const int sampleIdx) const override
virtual void saveMapSample (const int sampleIdx, const pcl::PointCloud< pcl::PointXYZI >::Ptr sample) override
std::shared_ptr< std::vector< int16_t > > getCascadeDatacube (const std::filesystem::path &binFilePath) const
std::shared_ptr< std::vector< float > > getCascadeHeatmap (const std::filesystem::path &binFilePath) const
pcl::PointCloud< RadarPoint >::Ptr getCascadePointcloud (const std::filesystem::path &binFilePath, const double intensityThreshold=0.0) const
void createCascadePointclouds (const double intensityThreshold=0.0)
octomap::OcTree buildLidarOctomap (const double &mapResolution, const float &lidarTotalHorizontalFov, const float &lidarTotalVerticalFov, const float &lidarMaxRange, Eigen::Affine3f baseToLidarTransform=Eigen::Affine3f::Identity())
void createLidarOctomap (const double &mapResolution, const float &lidarTotalHorizontalFov, const float &lidarTotalVerticalFov, const float &lidarMaxRange, Eigen::Affine3f baseToLidarTransform=Eigen::Affine3f::Identity())
void createMapSamples (const float horizontalFov, const float verticalFov, const float range, const std::vector< double > sensorTimestamps={}, const Eigen::Affine3f &baseToSensorTransform=Eigen::Affine3f::Identity())
void saveLidarOctomap (const octomap::OcTree &tree)
pcl::PointCloud< pcl::PointXYZI >::Ptr readMapSample (const int sampleIdx) const
std::vector< pcl::PointCloud< pcl::PointXYZI >::Ptr > readMapSamples (const int numSamples=-1) const
std::vector< pcl::PointCloud< pcl::PointXYZI >::Ptr > sampleMapFrames (const float horizontalFov, const float verticalFov, const float range, const std::vector< Eigen::Affine3f > &mapFramePoses)
void saveMapSamples (const std::vector< pcl::PointCloud< pcl::PointXYZI >::Ptr > &samples)
template<CloudType CloudT>
std::shared_ptr< CloudT > getLidarPointCloud (const int cloudIdx) const
template<PclCloudType CloudT>
std::shared_ptr< CloudT > getLidarPointCloud (const std::filesystem::path &binPath) const
template<OctomapCloudType CloudT>
std::shared_ptr< CloudT > getLidarPointCloud (const std::filesystem::path &binPath) const
Public Member Functions inherited from coloradar::Run
Run (std::string name, std::shared_ptr< RadarConfig > cascadeRadarConfig=nullptr)
virtual ~Run ()=default
const std::string & name () const noexcept
std::shared_ptr< RadarConfig > cascadeConfig () const noexcept
const std::vector< double > & poseTimestamps () const
const std::vector< double > & imuTimestamps () const
const std::vector< double > & lidarTimestamps () const
const std::vector< double > & cascadeCubeTimestamps () const
const std::vector< double > & cascadeTimestamps () const
template<PoseType PoseT>
std::vector< PoseT > getPoses () const
pcl::PointCloud< pcl::PointXYZI >::Ptr sampleMapFrame (const float horizontalFov, const float verticalFov, const float range, const Eigen::Affine3f &mapFramePose, const pcl::PointCloud< pcl::PointXYZI >::Ptr mapCloud)
Protected Member Functions
std::vector< double > readTimestamps (const std::filesystem::path &path) const
std::vector< Eigen::Affine3f > readPoses (const std::filesystem::path &path) const
std::shared_ptr< std::vector< int16_t > > readDatacube (const std::filesystem::path &binFilePath, const std::shared_ptr< RadarConfig > &config) const
std::shared_ptr< std::vector< float > > readHeatmap (const std::filesystem::path &binFilePath, const std::shared_ptr< RadarConfig > &config) const
pcl::PointCloud< RadarPoint >::Ptr readRadarPointcloud (std::shared_ptr< RadarConfig > config, const std::filesystem::path &binFilePath, const double intensityThreshold=0.0) const
void createRadarPointclouds (const std::shared_ptr< RadarConfig > &config, const std::filesystem::path &heatmapDirPath, const std::filesystem::path &pointcloudDirPath, const double intensityThreshold=0.0)
Protected Attributes
std::filesystem::path runDirPath_
std::filesystem::path posesDirPath_
std::filesystem::path imuDirPath_
std::filesystem::path lidarScansDirPath_
std::filesystem::path lidarCloudsDirPath_
std::filesystem::path lidarMapsDirPath_
std::filesystem::path cascadeScansDirPath_
std::filesystem::path cascadeCubesDirPath_
std::filesystem::path cascadeHeatmapsDirPath_
std::filesystem::path cascadeCloudsDirPath_
Protected Attributes inherited from coloradar::Run
std::string name_
std::shared_ptr< RadarConfig > cascadeConfig_
std::vector< double > poseTimestamps_
std::vector< double > imuTimestamps_
std::vector< double > lidarTimestamps_
std::vector< double > cascadeCubeTimestamps_
std::vector< double > cascadeTimestamps_
std::vector< Eigen::Affine3f > poses_
Detailed Description
Definition at line 9 of file coloradar_plus_run.h.
Constructor & Destructor Documentation
ColoradarPlusRun()
coloradar::ColoradarPlusRun::ColoradarPlusRun (const std::filesystem::path & runPath, std::shared_ptr< RadarConfig > cascadeRadarConfig = nullptr)
Definition at line 6 of file coloradar_plus_run.cpp.
  : Run(runPath.filename(), cascadeRadarConfig), runDirPath_(runPath)
{
    coloradar::internal::checkPathExists(runDirPath_);
    posesDirPath_ = runDirPath_ / "groundtruth";
    coloradar::internal::checkPathExists(posesDirPath_);
    imuDirPath_ = runDirPath_ / "imu";
    coloradar::internal::checkPathExists(imuDirPath_);
    lidarScansDirPath_ = runDirPath_ / "lidar";
    coloradar::internal::checkPathExists(lidarScansDirPath_);
    cascadeScansDirPath_ = runDirPath_ / "cascade";
    coloradar::internal::checkPathExists(cascadeScansDirPath_);
    lidarCloudsDirPath_ = lidarScansDirPath_ / "pointclouds";
    coloradar::internal::checkPathExists(lidarCloudsDirPath_);
    lidarMapsDirPath_ = runDirPath_ / "lidar_maps";
    cascadeCubesDirPath_ = cascadeScansDirPath_ / "adc_samples";
    coloradar::internal::checkPathExists(cascadeCubesDirPath_);
    cascadeHeatmapsDirPath_ = cascadeScansDirPath_ / "heatmaps";
    coloradar::internal::checkPathExists(cascadeHeatmapsDirPath_);
    cascadeCloudsDirPath_ = cascadeScansDirPath_ / "pointclouds";
    poseTimestamps_ = readTimestamps(posesDirPath_ / "timestamps.txt");
    imuTimestamps_ = readTimestamps(imuDirPath_ / "timestamps.txt");
    lidarTimestamps_ = readTimestamps(lidarScansDirPath_ / "timestamps.txt");
    cascadeCubeTimestamps_ = readTimestamps(cascadeCubesDirPath_ / "timestamps.txt");
    cascadeTimestamps_ = readTimestamps(cascadeHeatmapsDirPath_ / "timestamps.txt");
    poses_ = readPoses(posesDirPath_ / "groundtruth_poses.txt");
}
References cascadeCloudsDirPath_, cascadeCubesDirPath_, coloradar::Run::cascadeCubeTimestamps_, cascadeHeatmapsDirPath_, cascadeScansDirPath_, coloradar::Run::cascadeTimestamps_, coloradar::internal::checkPathExists(), imuDirPath_, coloradar::Run::imuTimestamps_, lidarCloudsDirPath_, lidarMapsDirPath_, lidarScansDirPath_, coloradar::Run::lidarTimestamps_, coloradar::Run::poses_, posesDirPath_, coloradar::Run::poseTimestamps_, readPoses(), readTimestamps(), and runDirPath_.
~ColoradarPlusRun()
virtual coloradar::ColoradarPlusRun::~ColoradarPlusRun () virtual default
Member Function Documentation
buildLidarOctomap()
octomap::OcTree coloradar::ColoradarPlusRun::buildLidarOctomap (const double & mapResolution, const float & lidarTotalHorizontalFov, const float & lidarTotalVerticalFov, const float & lidarMaxRange, Eigen::Affine3f baseToLidarTransform = Eigen::Affine3f::Identity())
Definition at line 227 of file coloradar_plus_run.cpp.
  {
    float maxRange = lidarMaxRange == 0 ? std::numeric_limits<float>::max() : lidarMaxRange;
    std::vector<octomath::Pose6D> gtPoses = getPoses<octomath::Pose6D>();
    std::vector<octomath::Pose6D> poses = interpolatePoses(gtPoses, poseTimestamps_, lidarTimestamps_);
    auto baseToLidarT = coloradar::internal::fromEigenPose<octomath::Pose6D>(baseToLidarTransform);
    octomap::OcTree tree(mapResolution);
    for (size_t i = 0; i < lidarTimestamps_.size(); ++i) {
        std::shared_ptr<OctoPointcloud> cloud = getLidarPointCloud<OctoPointcloud>(i);
        cloud->filterFov(lidarTotalHorizontalFov, lidarTotalVerticalFov, maxRange);
        auto frameTransform = poses[i] * baseToLidarT;
        cloud->transform(frameTransform);
        tree.insertPointCloud(*cloud, frameTransform.trans());
    }
    return tree;
}
References coloradar::interpolatePoses(), coloradar::Run::lidarTimestamps_, coloradar::internal::makePose(), and coloradar::Run::poseTimestamps_.
createCascadePointclouds()
void coloradar::ColoradarPlusRun::createCascadePointclouds (const double intensityThreshold = 0.0)
Definition at line 222 of file coloradar_plus_run.cpp.
{
    createRadarPointclouds(cascadeConfig_, cascadeHeatmapsDirPath_, cascadeCloudsDirPath_, intensityThreshold);
}
References cascadeCloudsDirPath_, coloradar::Run::cascadeConfig_, cascadeHeatmapsDirPath_, and createRadarPointclouds().
createLidarOctomap()
void coloradar::ColoradarPlusRun::createLidarOctomap (const double & mapResolution, const float & lidarTotalHorizontalFov, const float & lidarTotalVerticalFov, const float & lidarMaxRange, Eigen::Affine3f baseToLidarTransform = Eigen::Affine3f::Identity())
Definition at line 262 of file coloradar_plus_run.cpp.
  {
    auto map = buildLidarOctomap(mapResolution, lidarTotalHorizontalFov, lidarTotalVerticalFov, lidarMaxRange, baseToLidarTransform);
    saveLidarOctomap(map);
}
References buildLidarOctomap(), and saveLidarOctomap().
createMapSamples()
void coloradar::ColoradarPlusRun::createMapSamples (const float horizontalFov, const float verticalFov, const float range, const std::vector< double > sensorTimestamps = {}, const Eigen::Affine3f & baseToSensorTransform = Eigen::Affine3f::Identity())
Definition at line 309 of file coloradar_plus_run.cpp.
  {
    for (const auto& entry : std::filesystem::directory_iterator(lidarMapsDirPath_)) {
        if (entry.is_regular_file() && entry.path().filename() != "map.pcd") {
            std::filesystem::remove(entry.path());
        }
    }
    std::vector<Eigen::Affine3f> basePoses = getPoses<Eigen::Affine3f>();
    if (!sensorTimestamps.empty()) basePoses = interpolatePoses(basePoses, poseTimestamps_, sensorTimestamps);
    auto mapCloud = getLidarOctomap();
    auto startT = std::chrono::high_resolution_clock::now();
    for (size_t i = 0; i < basePoses.size(); ++i) {
        Eigen::Affine3f mapToSensorT = basePoses[i] * baseToSensorTransform;
        auto sample = Run::sampleMapFrame(horizontalFov, verticalFov, range, mapToSensorT, mapCloud);
        saveMapSample(i, sample);
    }
    double elapsedTime = std::chrono::duration<double>(std::chrono::high_resolution_clock::now() - startT).count();
    std::cout << std::fixed << std::setprecision(2) << name_ << ": sampled " << basePoses.size() << " map frames in " << elapsedTime << " seconds." << std::endl;
}
References getLidarOctomap(), coloradar::interpolatePoses(), lidarMapsDirPath_, coloradar::Run::name_, coloradar::Run::poseTimestamps_, coloradar::Run::sampleMapFrame(), and saveMapSample().
createRadarPointclouds()
void coloradar::ColoradarPlusRun::createRadarPointclouds (const std::shared_ptr< RadarConfig > & config, const std::filesystem::path & heatmapDirPath, const std::filesystem::path & pointcloudDirPath, const double intensityThreshold = 0.0) protected
Definition at line 128 of file coloradar_plus_run.cpp.
{
    coloradar::internal::createDirectoryIfNotExists(pointcloudDirPath);
    coloradar::internal::createDirectoryIfNotExists(pointcloudDirPath / "data");
    const std::filesystem::path heatmapDataDir = heatmapDirPath / "data";
    for (const auto& entry : std::filesystem::directory_iterator(heatmapDataDir)) {
        const std::filesystem::path heatmapPath = entry.path();
        if (!entry.is_regular_file() || heatmapPath.extension() != ".bin") continue;
        auto heatmap = readHeatmap(heatmapPath, config);
        auto cloud = config->heatmapToPointcloud(heatmap, intensityThreshold);
        std::string filename = heatmapPath.filename().string();
        const std::string heatmapStr = "heatmap";
        filename.replace(filename.find(heatmapStr), heatmapStr.size(), "radar_pointcloud");
        const std::filesystem::path cloudPath = pointcloudDirPath / "data" / filename;
        std::ofstream file(cloudPath, std::ios::binary);
        if (!file) throw std::runtime_error("Failed to open file: " + cloudPath.string());
        file.exceptions(std::ofstream::failbit | std::ofstream::badbit);
        for (const auto& pt : cloud->points) {
            file.write(reinterpret_cast<const char*>(&pt.x),         sizeof(float));
            file.write(reinterpret_cast<const char*>(&pt.y),         sizeof(float));
            file.write(reinterpret_cast<const char*>(&pt.z),         sizeof(float));
            file.write(reinterpret_cast<const char*>(&pt.intensity), sizeof(float));
            file.write(reinterpret_cast<const char*>(&pt.doppler),   sizeof(float));
        }
    }
}
References coloradar::internal::createDirectoryIfNotExists(), and readHeatmap().
getCascadeDatacube() [1/2]
std::shared_ptr< std::vector< int16_t > > coloradar::ColoradarPlusRun::getCascadeDatacube (const int cubeIdx) const override virtual
Implements coloradar::Run.
Definition at line 171 of file coloradar_plus_run.cpp.
{
    std::filesystem::path cubesDir = cascadeCubesDirPath_ / "data";
    int fileIdx = frameIdxToFileIdx(cubeIdx, cubesDir);
    return getCascadeDatacube(cubesDir / ("frame_" + std::to_string(fileIdx) + ".bin"));
}
References cascadeCubesDirPath_, coloradar::frameIdxToFileIdx(), and getCascadeDatacube().
getCascadeDatacube() [2/2]
std::shared_ptr< std::vector< int16_t > > coloradar::ColoradarPlusRun::getCascadeDatacube (const std::filesystem::path & binFilePath) const
Definition at line 210 of file coloradar_plus_run.cpp.
{
    return readDatacube(binFilePath, cascadeConfig_);
}
References coloradar::Run::cascadeConfig_, and readDatacube().
getCascadeHeatmap() [1/2]
std::shared_ptr< std::vector< float > > coloradar::ColoradarPlusRun::getCascadeHeatmap (const int hmIdx) const override virtual
Implements coloradar::Run.
Definition at line 177 of file coloradar_plus_run.cpp.
{
    std::filesystem::path heatmapsDir = cascadeHeatmapsDirPath_ / "data";
    int fileIdx = frameIdxToFileIdx(hmIdx, heatmapsDir);
    return getCascadeHeatmap(heatmapsDir / ("heatmap_" + std::to_string(fileIdx) + ".bin"));
}
References cascadeHeatmapsDirPath_, coloradar::frameIdxToFileIdx(), and getCascadeHeatmap().
getCascadeHeatmap() [2/2]
std::shared_ptr< std::vector< float > > coloradar::ColoradarPlusRun::getCascadeHeatmap (const std::filesystem::path & binFilePath) const
Definition at line 214 of file coloradar_plus_run.cpp.
{
    return readHeatmap(binFilePath, cascadeConfig_);
}
References coloradar::Run::cascadeConfig_, and readHeatmap().
getCascadePointcloud() [1/2]
pcl::PointCloud< RadarPoint >::Ptr coloradar::ColoradarPlusRun::getCascadePointcloud (const int cloudIdx, const double intensityThreshold = 0.0) const override virtual
Implements coloradar::Run.
Definition at line 183 of file coloradar_plus_run.cpp.
{
    std::filesystem::path cloudsDir = cascadeCloudsDirPath_ / "data";
    int fileIdx = frameIdxToFileIdx(cloudIdx, cloudsDir);
    return getCascadePointcloud(cloudsDir / ("radar_pointcloud_" + std::to_string(fileIdx) + ".bin"), intensityThreshold);
}
References cascadeCloudsDirPath_, coloradar::frameIdxToFileIdx(), and getCascadePointcloud().
getCascadePointcloud() [2/2]
pcl::PointCloud< RadarPoint >::Ptr coloradar::ColoradarPlusRun::getCascadePointcloud (const std::filesystem::path & binFilePath, const double intensityThreshold = 0.0) const
Definition at line 218 of file coloradar_plus_run.cpp.
{
    return readRadarPointcloud(cascadeConfig_, binFilePath, intensityThreshold);
}
References coloradar::Run::cascadeConfig_, and readRadarPointcloud().
getLidarOctomap()
pcl::PointCloud< pcl::PointXYZI >::Ptr coloradar::ColoradarPlusRun::getLidarOctomap () const override virtual
Implements coloradar::Run.
Definition at line 189 of file coloradar_plus_run.cpp.
{
    auto cloud = pcl::PointCloud<pcl::PointXYZI>::Ptr(new pcl::PointCloud<pcl::PointXYZI>());
    std::filesystem::path mapFilePath = lidarMapsDirPath_ / "map.pcd";
    coloradar::internal::checkPathExists(mapFilePath);
    pcl::io::loadPCDFile<pcl::PointXYZI>(mapFilePath.string(), *cloud);
    return cloud;
}
References coloradar::internal::checkPathExists(), and lidarMapsDirPath_.
getLidarPointCloud() [1/4]
template<CloudType CloudT> std::shared_ptr< CloudT > coloradar::ColoradarPlusRun::getLidarPointCloud (const int cloudIdx) const virtual
Implements coloradar::Run.
Definition at line 9 of file coloradar_plus_run.hpp.
{
    std::filesystem::path cloudsDir = lidarCloudsDirPath_;
    int fileIdx = frameIdxToFileIdx(cloudIdx, cloudsDir);
    std::filesystem::path pclBinFilePath = cloudsDir / ("lidar_pointcloud_" + std::to_string(fileIdx) + ".bin");
    return getLidarPointCloud<CloudT>(pclBinFilePath);
}
References coloradar::frameIdxToFileIdx(), and lidarCloudsDirPath_.
getLidarPointCloud() [2/4]
pcl::PointCloud< pcl::PointXYZI >::Ptr coloradar::ColoradarPlusRun::getLidarPointCloud (const int cloudIdx) const override virtual
Implements coloradar::Run.
Definition at line 166 of file coloradar_plus_run.cpp.
{
    int fileIdx = frameIdxToFileIdx(cloudIdx, lidarCloudsDirPath_);
    return getLidarPointCloud<pcl::PointCloud<pcl::PointXYZI>>(fileIdx);
}
References coloradar::frameIdxToFileIdx(), and lidarCloudsDirPath_.
getLidarPointCloud() [3/4]
template<OctomapCloudType CloudT> std::shared_ptr< CloudT > coloradar::ColoradarPlusRun::getLidarPointCloud (const std::filesystem::path & binPath) const
Definition at line 17 of file coloradar_plus_run.hpp.
{
    return coloradar::internal::readLidarPointCloud<typename CloudT::PointType, CloudT>(binPath);
}
References coloradar::internal::makePose().
getLidarPointCloud() [4/4]
template<OctomapCloudType CloudT> std::shared_ptr< CloudT > coloradar::ColoradarPlusRun::getLidarPointCloud (const std::filesystem::path & binPath) const
getMapSample()
pcl::PointCloud< pcl::PointXYZI >::Ptr coloradar::ColoradarPlusRun::getMapSample (const int sampleIdx) const override virtual
Implements coloradar::Run.
Definition at line 197 of file coloradar_plus_run.cpp.
{
    auto cloud = std::make_shared<pcl::PointCloud<pcl::PointXYZI>>();
    std::filesystem::path frameFilePath = lidarMapsDirPath_ / ("frame_" + std::to_string(sampleIdx) + ".pcd");
    if (pcl::io::loadPCDFile<pcl::PointXYZI>(frameFilePath.string(), *cloud) == -1) throw std::runtime_error("Failed to load PCD file: " + frameFilePath.string());
    return cloud;
}
References lidarMapsDirPath_.
readDatacube()
std::shared_ptr< std::vector< int16_t > > coloradar::ColoradarPlusRun::readDatacube (const std::filesystem::path & binFilePath, const std::shared_ptr< RadarConfig > & config) const protected
Definition at line 71 of file coloradar_plus_run.cpp.
{
    coloradar::internal::checkPathExists(binFilePath);
    std::ifstream file(binFilePath, std::ios::binary);
    if (!file) throw std::runtime_error("Failed to open file: " + binFilePath.string());
    const size_t totalElements = config->numTxAntennas() * config->numRxAntennas() * config->numChirpsPerFrame() * config->numAdcSamplesPerChirp() * 2;
    const size_t totalBytes = totalElements * sizeof(int16_t);
    auto datacube = std::make_shared<std::vector<int16_t>>(totalElements);
    if (!file.read(reinterpret_cast<char*>(datacube->data()), totalBytes))
        throw std::runtime_error("Datacube file read error or size mismatch: " + binFilePath.string());
    file.close();
    return datacube;
}
References coloradar::internal::checkPathExists().
readHeatmap()
std::shared_ptr< std::vector< float > > coloradar::ColoradarPlusRun::readHeatmap (const std::filesystem::path & binFilePath, const std::shared_ptr< RadarConfig > & config) const protected
Definition at line 85 of file coloradar_plus_run.cpp.
{
    coloradar::internal::checkPathExists(binFilePath);
    std::ifstream file(binFilePath, std::ios::binary);
    if (!file) throw std::runtime_error("Failed to open file: " + binFilePath.string());
    int totalElements = config->numElevationBins() * config->numAzimuthBins() * config->nRangeBins() * 2;
    const size_t totalBytes = totalElements * sizeof(float);
    auto heatmap = std::make_shared<std::vector<float>>(totalElements);
    if (!file.read(reinterpret_cast<char*>(heatmap->data()), totalBytes))
        throw std::runtime_error("Heatmap file read error or size mismatch: " + binFilePath.string());
    file.close();
    return heatmap;
}
References coloradar::internal::checkPathExists().
readMapSample()
pcl::PointCloud< pcl::PointXYZI >::Ptr coloradar::ColoradarPlusRun::readMapSample (const int sampleIdx) const
readMapSamples()
std::vector< pcl::PointCloud< pcl::PointXYZI >::Ptr > coloradar::ColoradarPlusRun::readMapSamples (const int numSamples = -1) const
Definition at line 336 of file coloradar_plus_run.cpp.
{
    std::vector<std::filesystem::path> samplePaths = coloradar::internal::readArrayDirectory(lidarMapsDirPath_, "frame_", ".pcd", numSamples);
    std::vector<pcl::PointCloud<pcl::PointXYZI>::Ptr> samples;
    samples.reserve(samplePaths.size());
    for (const auto& path : samplePaths) {
        auto sample = std::make_shared<pcl::PointCloud<pcl::PointXYZI>>();
        if (pcl::io::loadPCDFile<pcl::PointXYZI>(path.string(), *sample) == -1) {
            throw std::runtime_error("Failed to load PCD file: " + path.string());
        }
        samples.push_back(sample);
    }
    return samples;
}
References lidarMapsDirPath_, and coloradar::internal::readArrayDirectory().
readPoses()
std::vector< Eigen::Affine3f > coloradar::ColoradarPlusRun::readPoses (const std::filesystem::path & path) const protected
Definition at line 53 of file coloradar_plus_run.cpp.
{
    coloradar::internal::checkPathExists(path);
    std::ifstream infile(path);
    std::string line;
    std::vector<Eigen::Affine3f> poses;
    while (std::getline(infile, line)) {
        float x, y, z, rotX, rotY, rotZ, rotW;
        std::istringstream iss(line);
        iss >> x >> y >> z >> rotX >> rotY >> rotZ >> rotW;
        Eigen::Translation3f translation(x, y, z);
        Eigen::Quaternionf rotation(rotW, rotX, rotY, rotZ);
        Eigen::Affine3f pose = translation * rotation;
        poses.push_back(pose);
    }
    return poses;
}
References coloradar::internal::checkPathExists().
readRadarPointcloud()
pcl::PointCloud< RadarPoint >::Ptr coloradar::ColoradarPlusRun::readRadarPointcloud (std::shared_ptr< RadarConfig > config, const std::filesystem::path & binFilePath, const double intensityThreshold = 0.0) const protected
Definition at line 99 of file coloradar_plus_run.cpp.
        {
    std::ifstream file(binFilePath, std::ios::in | std::ios::binary);
    if (!file.is_open()) {
        throw std::filesystem::filesystem_error("Failed to open file: " + binFilePath.string(), std::make_error_code(std::errc::no_such_file_or_directory));
    }
    auto cloud = pcl::PointCloud<RadarPoint>::Ptr(new pcl::PointCloud<RadarPoint>());
    float x, y, z, i, d;
    while (true) {
        if (!file.read(reinterpret_cast<char*>(&x), sizeof(float))) break;
        if (!file.read(reinterpret_cast<char*>(&y), sizeof(float))) break;
        if (!file.read(reinterpret_cast<char*>(&z), sizeof(float))) break;
        if (!file.read(reinterpret_cast<char*>(&i), sizeof(float))) break;
        if (!file.read(reinterpret_cast<char*>(&d), sizeof(float))) break;
        if (i < intensityThreshold) continue;
        cloud->points.emplace_back();
        RadarPoint& pt = cloud->points.back();
        pt.x = x; pt.y = y; pt.z = z;
        pt.intensity = i;
        pt.doppler   = d;
    }
    cloud->width  = static_cast<uint32_t>(cloud->size());
    return cloud;
}
References coloradar::RadarPoint::doppler, and coloradar::RadarPoint::intensity.
readTimestamps()
std::vector< double > coloradar::ColoradarPlusRun::readTimestamps (const std::filesystem::path & path) const protected
Definition at line 42 of file coloradar_plus_run.cpp.
{
    coloradar::internal::checkPathExists(path);
    std::vector<double> timestamps;
    std::ifstream infile(path);
    std::string line;
    while (std::getline(infile, line)) {
        timestamps.push_back(std::stod(line));
    }
    return timestamps;
}
References coloradar::internal::checkPathExists().
sampleMapFrames()
std::vector< pcl::PointCloud< pcl::PointXYZI >::Ptr > coloradar::ColoradarPlusRun::sampleMapFrames (const float horizontalFov, const float verticalFov, const float range, const std::vector< Eigen::Affine3f > & mapFramePoses)
Definition at line 274 of file coloradar_plus_run.cpp.
  {
    if (mapFramePoses.empty()) throw std::runtime_error("Empty sampling poses.");
    auto mapCloud = getLidarOctomap();
    std::vector<pcl::PointCloud<pcl::PointXYZI>::Ptr> samples;
    samples.reserve(mapFramePoses.size());
    auto startT = std::chrono::high_resolution_clock::now();
    for (const auto& pose : mapFramePoses) {
        samples.push_back(Run::sampleMapFrame(horizontalFov, verticalFov, range, pose, mapCloud));
    }
    double elapsedTime = std::chrono::duration<double>(std::chrono::high_resolution_clock::now() - startT).count();
    std::cout << std::fixed << std::setprecision(2)  << name_ << ": sampled " << mapFramePoses.size() << " map frames in " << elapsedTime << " seconds." << std::endl;
    return samples;
}
References getLidarOctomap(), coloradar::Run::name_, and coloradar::Run::sampleMapFrame().
saveLidarOctomap()
void coloradar::ColoradarPlusRun::saveLidarOctomap (const octomap::OcTree & tree)
Definition at line 250 of file coloradar_plus_run.cpp.
{
    std::shared_ptr<pcl::PointCloud<pcl::PointXYZI>> treePcl = std::make_shared<pcl::PointCloud<pcl::PointXYZI>>();
    coloradar::octreeToPcl(tree, treePcl);
    coloradar::internal::createDirectoryIfNotExists(lidarMapsDirPath_);
    std::filesystem::path outputMapFile = lidarMapsDirPath_ / "map.pcd";
    if (treePcl->size() == 0) {
        treePcl->height = 1;
        treePcl->is_dense = true;
    }
    pcl::io::savePCDFile(outputMapFile, *treePcl);
}
References coloradar::internal::createDirectoryIfNotExists(), lidarMapsDirPath_, and coloradar::octreeToPcl().
saveMapSample()
void coloradar::ColoradarPlusRun::saveMapSample (const int sampleIdx, const pcl::PointCloud< pcl::PointXYZI >::Ptr sample) override virtual
Implements coloradar::Run.
Definition at line 204 of file coloradar_plus_run.cpp.
{
    std::filesystem::path frameFilePath = lidarMapsDirPath_ / ("frame_" + std::to_string(sampleIdx) + ".pcd");
    pcl::io::savePCDFile(frameFilePath, *sample);
}
References lidarMapsDirPath_.
saveMapSamples()
void coloradar::ColoradarPlusRun::saveMapSamples (const std::vector< pcl::PointCloud< pcl::PointXYZI >::Ptr > & samples)
Definition at line 296 of file coloradar_plus_run.cpp.
{
    if (samples.empty()) throw std::runtime_error("Empty frames.");
    for (const auto& entry : std::filesystem::directory_iterator(lidarMapsDirPath_)) {
        if (entry.is_regular_file() && entry.path().filename() != "map.pcd") {
            std::filesystem::remove(entry.path());
        }
    }
    for (size_t i = 0; i < samples.size(); ++i) {
        saveMapSample(i, samples[i]);
    }
}
References lidarMapsDirPath_, and saveMapSample().
Member Data Documentation
cascadeCloudsDirPath_
std::filesystem::path coloradar::ColoradarPlusRun::cascadeCloudsDirPath_ protected
Definition at line 21 of file coloradar_plus_run.h.
cascadeCubesDirPath_
std::filesystem::path coloradar::ColoradarPlusRun::cascadeCubesDirPath_ protected
Definition at line 19 of file coloradar_plus_run.h.
cascadeHeatmapsDirPath_
std::filesystem::path coloradar::ColoradarPlusRun::cascadeHeatmapsDirPath_ protected
Definition at line 20 of file coloradar_plus_run.h.
cascadeScansDirPath_
std::filesystem::path coloradar::ColoradarPlusRun::cascadeScansDirPath_ protected
Definition at line 18 of file coloradar_plus_run.h.
imuDirPath_
std::filesystem::path coloradar::ColoradarPlusRun::imuDirPath_ protected
Definition at line 14 of file coloradar_plus_run.h.
lidarCloudsDirPath_
std::filesystem::path coloradar::ColoradarPlusRun::lidarCloudsDirPath_ protected
Definition at line 16 of file coloradar_plus_run.h.
lidarMapsDirPath_
std::filesystem::path coloradar::ColoradarPlusRun::lidarMapsDirPath_ protected
Definition at line 17 of file coloradar_plus_run.h.
lidarScansDirPath_
std::filesystem::path coloradar::ColoradarPlusRun::lidarScansDirPath_ protected
Definition at line 15 of file coloradar_plus_run.h.
posesDirPath_
std::filesystem::path coloradar::ColoradarPlusRun::posesDirPath_ protected
Definition at line 13 of file coloradar_plus_run.h.
runDirPath_
std::filesystem::path coloradar::ColoradarPlusRun::runDirPath_ protected
Definition at line 12 of file coloradar_plus_run.h.
The documentation for this class was generated from the following files:
include/run/coloradar_plus_run.h
include/run/coloradar_plus_run.hpp
src/run/coloradar_plus_run.cpp