Coloradar Library: coloradar::CascadeConfig Class Reference
coloradar::CascadeConfig Class Reference
#include <radar_configs.h>
Public Member Functions
CascadeConfig ()=default
CascadeConfig (const std::filesystem::path &calibDir, const int &nAzimuthBeams=128, const int &nElevationBeams=32)
CascadeConfig (const Json::Value &root)
std::shared_ptr< RadarConfig > clone () const override
Public Member Functions inherited from coloradar::RadarConfig
const int & numAzimuthBeams () const
const int & numElevationBeams () const
const int & azimuthApertureLen () const
const int & elevationApertureLen () const
const int & numAngles () const
const int & numVirtualElements () const
const std::vector< int > & virtualArrayMap () const
const std::vector< float > & azimuthAngles () const
const std::vector< float > & elevationAngles () const
const double & dopplerBinWidth () const
const bool & hasDoppler () const
const int & numElevationBins () const
const int & numAzimuthBins () const
const int & numRangeBins () const
const int & numPosRangeBins () const
const double & rangeBinWidth () const
const std::vector< float > & azimuthBins () const
const std::vector< float > & elevationBins () const
const double & designFrequency () const
const int & numTxAntennas () const
const int & numRxAntennas () const
const std::vector< pcl::PointXY > & txCenters () const
const std::vector< pcl::PointXY > & rxCenters () const
const int & numAdcSamplesPerChirp () const
const int & numChirpsPerFrame () const
const int & adcSampleFrequency () const
const double & startFrequency () const
const double & idleTime () const
const double & adcStartTime () const
const double & rampEndTime () const
const double & frequencySlope () const
const int & numDopplerBins () const
const std::vector< std::complex< double > > & couplingCalibMatrix () const
const int & calibAdcSampleFrequency () const
const double & calibFrequencySlope () const
const std::vector< std::complex< double > > & frequencyCalibMatrix () const
const std::vector< std::complex< double > > & phaseCalibMatrix () const
const pcl::PointCloud< RadarPoint >::Ptr & pointcloudTemplate () const
RadarConfig (const int &nAzimuthBeams=1, const int &nElevationBeams=1)
RadarConfig (const RadarConfig &other)=default
virtual ~RadarConfig ()=default
Json::Value toJson () const
void fromJson (const Json::Value &root)
void fromJson (const std::string &jsonString)
const int & nRangeBins () const
float maxRange () const
const int heatmapSize () const
int clipAzimuthMaxBin (const int &azMaxBin) const
int clipElevationMaxBin (const int &elMaxBin) const
int clipRangeMaxBin (const int &rangeMaxBin) const
float clipRange (const float &range) const
float azimuthIdxToFovDegrees (const int &azMaxBin) const
float elevationIdxToFovDegrees (const int &elMaxBin) const
float rangeIdxToRange (const int &rangeMaxBin) const
int horizontalFovToAzimuthIdx (const float &horizontalFov) const
int verticalFovToElevationIdx (const float &verticalFov) const
int rangeToRangeIdx (const float &range) const
HeatmapTransformResult clipHeatmap (const std::shared_ptr< std::vector< float > > &heatmap, int azimuthMaxBin, int elevationMaxBin, int rangeMaxBin) const
HeatmapTransformResult clipHeatmap (const std::shared_ptr< std::vector< float > > &heatmap, float horizontalFov, float verticalFov, float range) const
HeatmapTransformResult collapseHeatmapElevation (const std::shared_ptr< std::vector< float > > &image, const float &elevationMinMeters=-100.0, const float &elevationMaxMeters=100.0) const
HeatmapTransformResult removeDoppler (const std::shared_ptr< std::vector< float > > &image) const
pcl::PointCloud< RadarPoint >::Ptr heatmapToPointcloud (const std::shared_ptr< std::vector< float > > &heatmap, const double intensityThreshold=0.0) const
void precomputePointcloudTemplate ()
Protected Member Functions
void init (const std::filesystem::path &calibDir) override
Protected Member Functions inherited from coloradar::RadarConfig
void initAntennaParams (const std::filesystem::path &antennaCfgFile)
void initHeatmapParams (const std::filesystem::path &heatmapCfgFile)
void initWaveformParams (const std::filesystem::path &waveformCfgFile)
void initCouplingParams (const std::filesystem::path &couplingCfgFile)
void initPhaseFrequencyParams (const std::filesystem::path &phaseFrequencyCfgFile)
void initInternalParams ()
void setNumRangeBins (const int &num)
Additional Inherited Members
Static Public Attributes inherited from coloradar::RadarConfig
static constexpr double c = 299792458
Protected Attributes inherited from coloradar::RadarConfig
int numAzimuthBeams_ = 0
int numElevationBeams_ = 0
int azimuthApertureLen_ = 0
int elevationApertureLen_ = 0
int numAngles_ = 0
int numVirtualElements_ = 0
std::vector< int > virtualArrayMap_ = {}
std::vector< float > azimuthAngles_ = {}
std::vector< float > elevationAngles_ = {}
double dopplerBinWidth_ = 0.0
bool hasDoppler_ = true
int numRangeBins_ = 0
int numPosRangeBins_ = 0
int numElevationBins_ = 0
int numAzimuthBins_ = 0
double rangeBinWidth_ = 0
std::vector< float > azimuthBins_ = {}
std::vector< float > elevationBins_ = {}
double designFrequency_ = 0.0
int numTxAntennas_ = 0
int numRxAntennas_ = 0
std::vector< pcl::PointXY > txCenters_ = {}
std::vector< pcl::PointXY > rxCenters_ = {}
int numAdcSamplesPerChirp_ = 0
int numChirpsPerFrame_ = 0
int adcSampleFrequency_ = 0
double startFrequency_ = 0.0
double idleTime_ = 0.0
double adcStartTime_ = 0.0
double rampEndTime_ = 0.0
double frequencySlope_ = 0.0
int numDopplerBins_ = 0
std::vector< std::complex< double > > couplingCalibMatrix_ = {}
int calibAdcSampleFrequency_ = 0
double calibFrequencySlope_ = 0.0
std::vector< std::complex< double > > frequencyCalibMatrix_ = {}
std::vector< std::complex< double > > phaseCalibMatrix_ = {}
pcl::PointCloud< RadarPoint >::Ptr pointcloudTemplate_ = nullptr
Detailed Description
Definition at line 172 of file radar_configs.h.
Constructor & Destructor Documentation
CascadeConfig() [1/3]
coloradar::CascadeConfig::CascadeConfig () default
CascadeConfig() [2/3]
coloradar::CascadeConfig::CascadeConfig (const std::filesystem::path & calibDir, const int & nAzimuthBeams = 128, const int & nElevationBeams = 32)
Definition at line 944 of file radar_configs.cpp.
                                                                                                                             : coloradar::RadarConfig(nAzimuthBeams, nElevationBeams) {
    coloradar::internal::checkPathExists(calibDir);
    init(calibDir);
}
References coloradar::internal::checkPathExists(), and init().
CascadeConfig() [3/3]
coloradar::CascadeConfig::CascadeConfig (const Json::Value & root) inline explicit
Definition at line 176 of file radar_configs.h.
{ fromJson(root); }
References coloradar::RadarConfig::fromJson().
Member Function Documentation
clone()
std::shared_ptr< RadarConfig > coloradar::CascadeConfig::clone () const inline override virtual
Implements coloradar::RadarConfig.
Definition at line 177 of file radar_configs.h.
{
        return std::make_shared<CascadeConfig>(*this);
    }
init()
void coloradar::CascadeConfig::init (const std::filesystem::path & calibDir) override protected virtual
Implements coloradar::RadarConfig.
Definition at line 949 of file radar_configs.cpp.
{
    std::filesystem::path configDir = calibDir / "cascade";
    coloradar::internal::checkPathExists(configDir);
    std::filesystem::path antennaConfigFilePath = configDir / "antenna_cfg.txt";
    std::filesystem::path heatmapConfigFilePath = configDir / "heatmap_cfg.txt";
    std::filesystem::path waveformConfigFilePath = configDir / "waveform_cfg.txt";
    std::filesystem::path couplingConfigFilePath = configDir / "coupling_calib.txt";
    std::filesystem::path phaseFrequencyConfigFilePath = configDir / "phase_frequency_calib.txt";
    initAntennaParams(antennaConfigFilePath);
    initHeatmapParams(heatmapConfigFilePath);
    initWaveformParams(waveformConfigFilePath);
    initCouplingParams(couplingConfigFilePath);
    initPhaseFrequencyParams(phaseFrequencyConfigFilePath);
    initInternalParams();
    precomputePointcloudTemplate();
}
References coloradar::internal::checkPathExists().
The documentation for this class was generated from the following files:
include/configs/radar_configs.h
src/configs/radar_configs.cpp