Coloradar Library: coloradar::ColoradarRun Class Reference
coloradar::ColoradarRun Class Reference
#include <coloradar_run.h>
Public Member Functions
ColoradarRun (const std::filesystem::path &runPath, std::shared_ptr< RadarConfig > cascadeRadarConfig, std::shared_ptr< RadarConfig > singleChipRadarConfig)
const std::shared_ptr< RadarConfig > singleChipConfig () const
const std::vector< double > & singleChipCubeTimestamps () const
const std::vector< double > & singleChipTimestamps () const
std::shared_ptr< std::vector< int16_t > > getSingleChipDatacube (const std::filesystem::path &binFilePath)
std::shared_ptr< std::vector< int16_t > > getSingleChipDatacube (const int &cubeIdx)
std::shared_ptr< std::vector< float > > getSingleChipHeatmap (const std::filesystem::path &binFilePath)
std::shared_ptr< std::vector< float > > getSingleChipHeatmap (const int &hmIdx)
pcl::PointCloud< RadarPoint >::Ptr getSingleChipPointcloud (const std::filesystem::path &binFilePath, const double intensityThreshold=0.0)
pcl::PointCloud< RadarPoint >::Ptr getSingleChipPointcloud (const int &cloudIdx, const double intensityThreshold=0.0)
Public Member Functions inherited from coloradar::ColoradarPlusRun
ColoradarPlusRun (const std::filesystem::path &runPath, std::shared_ptr< RadarConfig > cascadeRadarConfig=nullptr)
virtual ~ColoradarPlusRun ()=default
virtual pcl::PointCloud< pcl::PointXYZI >::Ptr getLidarPointCloud (const int cloudIdx) const override
virtual std::shared_ptr< std::vector< int16_t > > getCascadeDatacube (const int cubeIdx) const override
virtual std::shared_ptr< std::vector< float > > getCascadeHeatmap (const int hmIdx) const override
virtual pcl::PointCloud< RadarPoint >::Ptr getCascadePointcloud (const int cloudIdx, const double intensityThreshold=0.0) const override
virtual pcl::PointCloud< pcl::PointXYZI >::Ptr getLidarOctomap () const override
virtual pcl::PointCloud< pcl::PointXYZI >::Ptr getMapSample (const int sampleIdx) const override
virtual void saveMapSample (const int sampleIdx, const pcl::PointCloud< pcl::PointXYZI >::Ptr sample) override
std::shared_ptr< std::vector< int16_t > > getCascadeDatacube (const std::filesystem::path &binFilePath) const
std::shared_ptr< std::vector< float > > getCascadeHeatmap (const std::filesystem::path &binFilePath) const
pcl::PointCloud< RadarPoint >::Ptr getCascadePointcloud (const std::filesystem::path &binFilePath, const double intensityThreshold=0.0) const
void createCascadePointclouds (const double intensityThreshold=0.0)
octomap::OcTree buildLidarOctomap (const double &mapResolution, const float &lidarTotalHorizontalFov, const float &lidarTotalVerticalFov, const float &lidarMaxRange, Eigen::Affine3f baseToLidarTransform=Eigen::Affine3f::Identity())
void createLidarOctomap (const double &mapResolution, const float &lidarTotalHorizontalFov, const float &lidarTotalVerticalFov, const float &lidarMaxRange, Eigen::Affine3f baseToLidarTransform=Eigen::Affine3f::Identity())
void createMapSamples (const float horizontalFov, const float verticalFov, const float range, const std::vector< double > sensorTimestamps={}, const Eigen::Affine3f &baseToSensorTransform=Eigen::Affine3f::Identity())
void saveLidarOctomap (const octomap::OcTree &tree)
pcl::PointCloud< pcl::PointXYZI >::Ptr readMapSample (const int sampleIdx) const
std::vector< pcl::PointCloud< pcl::PointXYZI >::Ptr > readMapSamples (const int numSamples=-1) const
std::vector< pcl::PointCloud< pcl::PointXYZI >::Ptr > sampleMapFrames (const float horizontalFov, const float verticalFov, const float range, const std::vector< Eigen::Affine3f > &mapFramePoses)
void saveMapSamples (const std::vector< pcl::PointCloud< pcl::PointXYZI >::Ptr > &samples)
template<CloudType CloudT>
std::shared_ptr< CloudT > getLidarPointCloud (const int cloudIdx) const
template<PclCloudType CloudT>
std::shared_ptr< CloudT > getLidarPointCloud (const std::filesystem::path &binPath) const
template<OctomapCloudType CloudT>
std::shared_ptr< CloudT > getLidarPointCloud (const std::filesystem::path &binPath) const
Public Member Functions inherited from coloradar::Run
Run (std::string name, std::shared_ptr< RadarConfig > cascadeRadarConfig=nullptr)
virtual ~Run ()=default
const std::string & name () const noexcept
std::shared_ptr< RadarConfig > cascadeConfig () const noexcept
const std::vector< double > & poseTimestamps () const
const std::vector< double > & imuTimestamps () const
const std::vector< double > & lidarTimestamps () const
const std::vector< double > & cascadeCubeTimestamps () const
const std::vector< double > & cascadeTimestamps () const
template<PoseType PoseT>
std::vector< PoseT > getPoses () const
pcl::PointCloud< pcl::PointXYZI >::Ptr sampleMapFrame (const float horizontalFov, const float verticalFov, const float range, const Eigen::Affine3f &mapFramePose, const pcl::PointCloud< pcl::PointXYZI >::Ptr mapCloud)
Protected Attributes
std::filesystem::path singleChipScansDirPath_
std::filesystem::path singleChipCubesDirPath_
std::filesystem::path singleChipHeatmapsDirPath_
std::filesystem::path singleChipCloudsDirPath_
std::vector< double > singleChipCubeTimestamps_
std::vector< double > singleChipTimestamps_
std::shared_ptr< RadarConfig > singleChipConfig_
Protected Attributes inherited from coloradar::ColoradarPlusRun
std::filesystem::path runDirPath_
std::filesystem::path posesDirPath_
std::filesystem::path imuDirPath_
std::filesystem::path lidarScansDirPath_
std::filesystem::path lidarCloudsDirPath_
std::filesystem::path lidarMapsDirPath_
std::filesystem::path cascadeScansDirPath_
std::filesystem::path cascadeCubesDirPath_
std::filesystem::path cascadeHeatmapsDirPath_
std::filesystem::path cascadeCloudsDirPath_
Protected Attributes inherited from coloradar::Run
std::string name_
std::shared_ptr< RadarConfig > cascadeConfig_
std::vector< double > poseTimestamps_
std::vector< double > imuTimestamps_
std::vector< double > lidarTimestamps_
std::vector< double > cascadeCubeTimestamps_
std::vector< double > cascadeTimestamps_
std::vector< Eigen::Affine3f > poses_
Additional Inherited Members
Protected Member Functions inherited from coloradar::ColoradarPlusRun
std::vector< double > readTimestamps (const std::filesystem::path &path) const
std::vector< Eigen::Affine3f > readPoses (const std::filesystem::path &path) const
std::shared_ptr< std::vector< int16_t > > readDatacube (const std::filesystem::path &binFilePath, const std::shared_ptr< RadarConfig > &config) const
std::shared_ptr< std::vector< float > > readHeatmap (const std::filesystem::path &binFilePath, const std::shared_ptr< RadarConfig > &config) const
pcl::PointCloud< RadarPoint >::Ptr readRadarPointcloud (std::shared_ptr< RadarConfig > config, const std::filesystem::path &binFilePath, const double intensityThreshold=0.0) const
void createRadarPointclouds (const std::shared_ptr< RadarConfig > &config, const std::filesystem::path &heatmapDirPath, const std::filesystem::path &pointcloudDirPath, const double intensityThreshold=0.0)
Detailed Description
Definition at line 10 of file coloradar_run.h.
Constructor & Destructor Documentation
ColoradarRun()
coloradar::ColoradarRun::ColoradarRun (const std::filesystem::path & runPath, std::shared_ptr< RadarConfig > cascadeRadarConfig, std::shared_ptr< RadarConfig > singleChipRadarConfig)
Definition at line 7 of file coloradar_run.cpp.
                                                                                                                                                            : ColoradarPlusRun(runPath, cascadeRadarConfig), singleChipConfig_(singleChipRadarConfig) {
    singleChipScansDirPath_ = runDirPath_ / "cascade";
    coloradar::internal::checkPathExists(singleChipScansDirPath_);
    singleChipCubesDirPath_ = singleChipScansDirPath_ / "adc_samples";
    coloradar::internal::checkPathExists(singleChipCubesDirPath_);
    singleChipHeatmapsDirPath_ = singleChipScansDirPath_ / "heatmaps";
    coloradar::internal::checkPathExists(cascadeHeatmapsDirPath_);
    singleChipCloudsDirPath_ = singleChipScansDirPath_ / "pointclouds";
    singleChipCubeTimestamps_ = readTimestamps(singleChipCubesDirPath_ / "timestamps.txt");
    singleChipTimestamps_ = readTimestamps(singleChipHeatmapsDirPath_ / "timestamps.txt");
}
References coloradar::ColoradarPlusRun::cascadeHeatmapsDirPath_, coloradar::internal::checkPathExists(), coloradar::ColoradarPlusRun::readTimestamps(), coloradar::ColoradarPlusRun::runDirPath_, singleChipCloudsDirPath_, singleChipCubesDirPath_, singleChipCubeTimestamps_, singleChipHeatmapsDirPath_, singleChipScansDirPath_, and singleChipTimestamps_.
Member Function Documentation
getSingleChipDatacube() [1/2]
std::shared_ptr< std::vector< int16_t > > coloradar::ColoradarRun::getSingleChipDatacube (const int & cubeIdx)
Definition at line 23 of file coloradar_run.cpp.
{
    std::filesystem::path cubesDir = singleChipCubesDirPath_ / "data";
    int fileIdx = frameIdxToFileIdx(cubeIdx, cubesDir);
    return getSingleChipDatacube(cubesDir / ("frame_" + std::to_string(fileIdx) + ".bin"));
}
References coloradar::frameIdxToFileIdx(), getSingleChipDatacube(), and singleChipCubesDirPath_.
getSingleChipDatacube() [2/2]
std::shared_ptr< std::vector< int16_t > > coloradar::ColoradarRun::getSingleChipDatacube (const std::filesystem::path & binFilePath)
Definition at line 20 of file coloradar_run.cpp.
{
    return readDatacube(binFilePath, singleChipConfig_);
}
References coloradar::ColoradarPlusRun::readDatacube(), and singleChipConfig_.
getSingleChipHeatmap() [1/2]
std::shared_ptr< std::vector< float > > coloradar::ColoradarRun::getSingleChipHeatmap (const int & hmIdx)
Definition at line 31 of file coloradar_run.cpp.
{
    std::filesystem::path heatmapsDir = singleChipHeatmapsDirPath_ / "data";
    int fileIdx = frameIdxToFileIdx(hmIdx, heatmapsDir);
    return getSingleChipHeatmap(heatmapsDir / ("heatmap_" + std::to_string(fileIdx) + ".bin"));
}
References coloradar::frameIdxToFileIdx(), getSingleChipHeatmap(), and singleChipHeatmapsDirPath_.
getSingleChipHeatmap() [2/2]
std::shared_ptr< std::vector< float > > coloradar::ColoradarRun::getSingleChipHeatmap (const std::filesystem::path & binFilePath)
Definition at line 28 of file coloradar_run.cpp.
{
    return readHeatmap(binFilePath, singleChipConfig_);
}
References coloradar::ColoradarPlusRun::readHeatmap(), and singleChipConfig_.
getSingleChipPointcloud() [1/2]
pcl::PointCloud< RadarPoint >::Ptr coloradar::ColoradarRun::getSingleChipPointcloud (const int & cloudIdx, const double intensityThreshold = 0.0)
Definition at line 40 of file coloradar_run.cpp.
{
    std::filesystem::path cloudsDir = singleChipCloudsDirPath_ / "data";
    int fileIdx = frameIdxToFileIdx(cloudIdx, cloudsDir);
    return getSingleChipPointcloud(cloudsDir / ("radar_pointcloud_" + std::to_string(fileIdx) + ".bin"), intensityThreshold);
}
References coloradar::frameIdxToFileIdx(), getSingleChipPointcloud(), and singleChipCloudsDirPath_.
getSingleChipPointcloud() [2/2]
pcl::PointCloud< RadarPoint >::Ptr coloradar::ColoradarRun::getSingleChipPointcloud (const std::filesystem::path & binFilePath, const double intensityThreshold = 0.0)
Definition at line 37 of file coloradar_run.cpp.
{
    return readRadarPointcloud(singleChipConfig_, binFilePath, intensityThreshold);
}
References coloradar::ColoradarPlusRun::readRadarPointcloud(), and singleChipConfig_.
singleChipConfig()
const std::shared_ptr< RadarConfig > coloradar::ColoradarRun::singleChipConfig () const inline
Definition at line 26 of file coloradar_run.h.
{ return singleChipConfig_; }
References singleChipConfig_.
singleChipCubeTimestamps()
const std::vector< double > & coloradar::ColoradarRun::singleChipCubeTimestamps () const inline
Definition at line 27 of file coloradar_run.h.
{ return singleChipCubeTimestamps_; }
References singleChipCubeTimestamps_.
singleChipTimestamps()
const std::vector< double > & coloradar::ColoradarRun::singleChipTimestamps () const inline
Definition at line 28 of file coloradar_run.h.
{ return singleChipTimestamps_; }
References singleChipTimestamps_.
Member Data Documentation
singleChipCloudsDirPath_
std::filesystem::path coloradar::ColoradarRun::singleChipCloudsDirPath_ protected
Definition at line 15 of file coloradar_run.h.
singleChipConfig_
std::shared_ptr<RadarConfig> coloradar::ColoradarRun::singleChipConfig_ protected
Definition at line 20 of file coloradar_run.h.
singleChipCubesDirPath_
std::filesystem::path coloradar::ColoradarRun::singleChipCubesDirPath_ protected
Definition at line 13 of file coloradar_run.h.
singleChipCubeTimestamps_
std::vector<double> coloradar::ColoradarRun::singleChipCubeTimestamps_ protected
Definition at line 17 of file coloradar_run.h.
singleChipHeatmapsDirPath_
std::filesystem::path coloradar::ColoradarRun::singleChipHeatmapsDirPath_ protected
Definition at line 14 of file coloradar_run.h.
singleChipScansDirPath_
std::filesystem::path coloradar::ColoradarRun::singleChipScansDirPath_ protected
Definition at line 12 of file coloradar_run.h.
singleChipTimestamps_
std::vector<double> coloradar::ColoradarRun::singleChipTimestamps_ protected
Definition at line 18 of file coloradar_run.h.
The documentation for this class was generated from the following files:
include/run/coloradar_run.h
src/run/coloradar_run.cpp