Coloradar Library: coloradar::LidarExportConfig Class Reference
coloradar::LidarExportConfig Class Reference
#include <device.h>
Public Member Functions
LidarExportConfig (bool exportPoses=false, bool exportTimestamps=false, bool collapseElevation=false, float collapseElevationMinZ=0.0f, float collapseElevationMaxZ=0.0f, bool exportClouds=false, bool removeIntensityDim=false, FovConfig cloudFov=FovConfig(), bool exportMap=false, bool allowMapRebuild=false, bool forceMapRebuild=false, bool saveMap=false, float mapResolution=0.25f, FovConfig mapInputCloudFov=FovConfig(), bool exportMapSamples=false, bool removeOccupancyDim=false, bool logOddsToProbability=false, float occupancyThresholdPercent=0.0f, bool allowResample=true, bool forceResample=false, bool saveSamples=false, std::unique_ptr< BaseDevice > centerSensor=std::make_unique< BaseDevice >(), FovConfig mapSampleFov=FovConfig())
LidarExportConfig (const LidarExportConfig &other)
LidarExportConfig & operator= (const LidarExportConfig &other)
const bool collapseElevation () const
const float collapseElevationMinZ () const
const float collapseElevationMaxZ () const
const bool exportClouds () const
const bool removeIntensityDim () const
const FovConfig & cloudFov () const
const bool exportMap () const
const bool allowMapRebuild () const
const bool forceMapRebuild () const
const bool saveMap () const
const float mapResolution () const
const FovConfig & mapInputCloudFov () const
const bool exportMapSamples () const
const bool removeOccupancyDim () const
const bool logOddsToProbability () const
const float occupancyThresholdPercent () const
const bool allowResample () const
const bool forceResample () const
const bool saveSamples () const
const BaseDevice * centerSensor () const
const FovConfig & mapSampleFov () const
void loadFromFile (const YAML::Node &deviceNode) override
Public Member Functions inherited from coloradar::BaseExportConfig
BaseExportConfig (bool exportPoses=false, bool exportTimestamps=false)
BaseExportConfig (const BaseExportConfig &other)=default
BaseExportConfig & operator= (const BaseExportConfig &other)=default
const bool exportPoses () const
const bool exportTimestamps () const
Protected Member Functions
virtual void validate () override
Protected Attributes
bool collapseElevation_
float collapseElevationMinZ_
float collapseElevationMaxZ_
bool exportClouds_
bool removeIntensityDim_
FovConfig cloudFov_
bool exportMap_
bool allowMapRebuild_
bool forceMapRebuild_
bool saveMap_
float mapResolution_
FovConfig mapInputCloudFov_
bool exportMapSamples_
bool removeOccupancyDim_
bool logOddsToProbability_
float occupancyThresholdPercent_
bool allowResample_
bool forceResample_
bool saveSamples_
std::unique_ptr< BaseDevice > centerSensor_
FovConfig mapSampleFov_
Protected Attributes inherited from coloradar::BaseExportConfig
bool exportPoses_
bool exportTimestamps_
Detailed Description
Definition at line 136 of file device.h.
Constructor & Destructor Documentation
LidarExportConfig() [1/2]
coloradar::LidarExportConfig::LidarExportConfig (bool exportPoses = false, bool exportTimestamps = false, bool collapseElevation = false, float collapseElevationMinZ = 0.0f, float collapseElevationMaxZ = 0.0f, bool exportClouds = false, bool removeIntensityDim = false, FovConfig cloudFov = FovConfig(), bool exportMap = false, bool allowMapRebuild = false, bool forceMapRebuild = false, bool saveMap = false, float mapResolution = 0.25f, FovConfig mapInputCloudFov = FovConfig(), bool exportMapSamples = false, bool removeOccupancyDim = false, bool logOddsToProbability = false, float occupancyThresholdPercent = 0.0f, bool allowResample = true, bool forceResample = false, bool saveSamples = false, std::unique_ptr< BaseDevice > centerSensor = std::make_unique<BaseDevice>(), FovConfig mapSampleFov = FovConfig()) inline
Definition at line 165 of file device.h.
      : BaseExportConfig(exportPoses, exportTimestamps),
        collapseElevation_(collapseElevation),
        collapseElevationMinZ_(collapseElevationMinZ),
        collapseElevationMaxZ_(collapseElevationMaxZ),
        exportClouds_(exportClouds),
        removeIntensityDim_(removeIntensityDim),
        cloudFov_(cloudFov),
        exportMap_(exportMap),
        allowMapRebuild_(allowMapRebuild),
        forceMapRebuild_(forceMapRebuild),
        saveMap_(saveMap),
        mapResolution_(mapResolution),
        mapInputCloudFov_(mapInputCloudFov),
        exportMapSamples_(exportMapSamples),
        removeOccupancyDim_(removeOccupancyDim),
        logOddsToProbability_(logOddsToProbability),
        occupancyThresholdPercent_(occupancyThresholdPercent),
        allowResample_(allowResample),
        forceResample_(forceResample),
        saveSamples_(saveSamples),
        centerSensor_(std::move(centerSensor)),
        mapSampleFov_(mapSampleFov) {
        validate();
    }
References validate().
LidarExportConfig() [2/2]
coloradar::LidarExportConfig::LidarExportConfig (const LidarExportConfig & other) inline
Definition at line 218 of file device.h.
    : BaseExportConfig(other),
      collapseElevation_(other.collapseElevation_),
      collapseElevationMinZ_(other.collapseElevationMinZ_),
      collapseElevationMaxZ_(other.collapseElevationMaxZ_),
      exportClouds_(other.exportClouds_),
      removeIntensityDim_(other.removeIntensityDim_),
      cloudFov_(other.cloudFov_),
      exportMap_(other.exportMap_),
      allowMapRebuild_(other.allowMapRebuild_),
      forceMapRebuild_(other.forceMapRebuild_),
      saveMap_(other.saveMap_),
      mapResolution_(other.mapResolution_),
      mapInputCloudFov_(other.mapInputCloudFov_),
      exportMapSamples_(other.exportMapSamples_),
      removeOccupancyDim_(other.removeOccupancyDim_),
      logOddsToProbability_(other.logOddsToProbability_),
      occupancyThresholdPercent_(other.occupancyThresholdPercent_),
      allowResample_(other.allowResample_),
      forceResample_(other.forceResample_),
      saveSamples_(other.saveSamples_),
      centerSensor_(other.centerSensor_ ? std::make_unique<BaseDevice>(*other.centerSensor_) : nullptr),
      mapSampleFov_(other.mapSampleFov_) {}
Member Function Documentation
allowMapRebuild()
const bool coloradar::LidarExportConfig::allowMapRebuild () const inline
Definition at line 278 of file device.h.
{ return allowMapRebuild_; }
References allowMapRebuild_.
allowResample()
const bool coloradar::LidarExportConfig::allowResample () const inline
Definition at line 287 of file device.h.
{ return allowResample_; }
References allowResample_.
centerSensor()
const BaseDevice * coloradar::LidarExportConfig::centerSensor () const inline
Definition at line 290 of file device.h.
{ return centerSensor_.get(); }
References centerSensor_.
cloudFov()
const FovConfig & coloradar::LidarExportConfig::cloudFov () const inline
Definition at line 276 of file device.h.
{ return cloudFov_; }
References cloudFov_.
collapseElevation()
const bool coloradar::LidarExportConfig::collapseElevation () const inline
Definition at line 271 of file device.h.
{ return collapseElevation_; }
References collapseElevation_.
collapseElevationMaxZ()
const float coloradar::LidarExportConfig::collapseElevationMaxZ () const inline
Definition at line 273 of file device.h.
{ return collapseElevationMaxZ_; }
References collapseElevationMaxZ_.
collapseElevationMinZ()
const float coloradar::LidarExportConfig::collapseElevationMinZ () const inline
Definition at line 272 of file device.h.
{ return collapseElevationMinZ_; }
References collapseElevationMinZ_.
exportClouds()
const bool coloradar::LidarExportConfig::exportClouds () const inline
Definition at line 274 of file device.h.
{ return exportClouds_; }
References exportClouds_.
exportMap()
const bool coloradar::LidarExportConfig::exportMap () const inline
Definition at line 277 of file device.h.
{ return exportMap_; }
References exportMap_.
exportMapSamples()
const bool coloradar::LidarExportConfig::exportMapSamples () const inline
Definition at line 283 of file device.h.
{ return exportMapSamples_; }
References exportMapSamples_.
forceMapRebuild()
const bool coloradar::LidarExportConfig::forceMapRebuild () const inline
Definition at line 279 of file device.h.
{ return forceMapRebuild_; }
References forceMapRebuild_.
forceResample()
const bool coloradar::LidarExportConfig::forceResample () const inline
Definition at line 288 of file device.h.
{ return forceResample_; }
References forceResample_.
loadFromFile()
void coloradar::LidarExportConfig::loadFromFile (const YAML::Node & deviceNode) override virtual
Reimplemented from coloradar::BaseExportConfig.
Definition at line 151 of file device.cpp.
{
    BaseExportConfig::loadFromFile(deviceNode);
    collapseElevation_ = coloradar::internal::parseBoolYamlKey(deviceNode["collapse_elevation"], collapseElevation_);
    collapseElevationMinZ_ = coloradar::internal::parseFloatYamlKey(deviceNode["collapse_elevation_min_z_meters"], collapseElevationMinZ_);
    collapseElevationMaxZ_ = coloradar::internal::parseFloatYamlKey(deviceNode["collapse_elevation_max_z_meters"], collapseElevationMaxZ_);
    exportClouds_ = coloradar::internal::parseBoolYamlKey(deviceNode["export_clouds"], exportClouds_);
    removeIntensityDim_ = coloradar::internal::parseBoolYamlKey(deviceNode["remove_intensity_dim"], removeIntensityDim_);
    auto cloudFovNode = deviceNode["cloud_fov"];
    if (cloudFovNode) {
        cloudFov_.useDegreeConstraints = true;
        cloudFov_.horizontalDegreesTotal = coloradar::internal::parseFloatYamlKey(cloudFovNode["horizontal_degrees_total"], cloudFov_.horizontalDegreesTotal);
        cloudFov_.verticalDegreesTotal = coloradar::internal::parseFloatYamlKey(cloudFovNode["vertical_degrees_total"], cloudFov_.verticalDegreesTotal);
        cloudFov_.rangeMeters = coloradar::internal::parseFloatYamlKey(cloudFovNode["range_meters"], cloudFov_.rangeMeters);
    }
    exportMap_ = coloradar::internal::parseBoolYamlKey(deviceNode["export_map"], exportMap_);
    allowMapRebuild_ = coloradar::internal::parseBoolYamlKey(deviceNode["allow_map_rebuild"], allowMapRebuild_);
    forceMapRebuild_ = coloradar::internal::parseBoolYamlKey(deviceNode["force_map_rebuild"], forceMapRebuild_);
    saveMap_ = coloradar::internal::parseBoolYamlKey(deviceNode["save_map"], saveMap_);
    mapResolution_ = coloradar::internal::parseFloatYamlKey(deviceNode["map_resolution"], mapResolution_);
    auto mapInputCloudFovNode = deviceNode["map_input_cloud_fov"];
    if (mapInputCloudFovNode) {
        mapInputCloudFov_.useDegreeConstraints = true;
        mapInputCloudFov_.horizontalDegreesTotal = coloradar::internal::parseFloatYamlKey(mapInputCloudFovNode["horizontal_degrees_total"], mapInputCloudFov_.horizontalDegreesTotal);
        mapInputCloudFov_.verticalDegreesTotal = coloradar::internal::parseFloatYamlKey(mapInputCloudFovNode["vertical_degrees_total"], mapInputCloudFov_.verticalDegreesTotal);
        mapInputCloudFov_.rangeMeters = coloradar::internal::parseFloatYamlKey(mapInputCloudFovNode["range_meters"], mapInputCloudFov_.rangeMeters);
    }
    exportMapSamples_ = coloradar::internal::parseBoolYamlKey(deviceNode["export_map_samples"], exportMapSamples_);
    removeOccupancyDim_ = coloradar::internal::parseBoolYamlKey(deviceNode["remove_occupancy_dim"], removeOccupancyDim_);
    logOddsToProbability_ = coloradar::internal::parseBoolYamlKey(deviceNode["convert_log_odds_to_probability"], logOddsToProbability_);
    occupancyThresholdPercent_ = coloradar::internal::parseFloatYamlKey(deviceNode["occupancy_threshold_percent"], occupancyThresholdPercent_);
    allowResample_ = coloradar::internal::parseBoolYamlKey(deviceNode["allow_resample"], allowResample_);
    forceResample_ = coloradar::internal::parseBoolYamlKey(deviceNode["force_resample"], forceResample_);
    saveSamples_ = coloradar::internal::parseBoolYamlKey(deviceNode["save_samples"], saveSamples_);
    auto mapFovNode = deviceNode["map_sample_fov"];
    if (mapFovNode) {
        mapSampleFov_.useDegreeConstraints = true;
        mapSampleFov_.horizontalDegreesTotal = coloradar::internal::parseFloatYamlKey(mapFovNode["horizontal_degrees_total"], mapSampleFov_.horizontalDegreesTotal);
        mapSampleFov_.verticalDegreesTotal = coloradar::internal::parseFloatYamlKey(mapFovNode["vertical_degrees_total"], mapSampleFov_.verticalDegreesTotal);
        mapSampleFov_.rangeMeters = coloradar::internal::parseFloatYamlKey(mapFovNode["range_meters"], mapSampleFov_.rangeMeters);
    }
    std::string centerSensorName = parseDeviceName(deviceNode["center_sensor"], centerSensor_->name());
    if (centerSensorName == (new BaseDevice())->name()) {
        centerSensor_ = std::make_unique<BaseDevice>();
    } else if (centerSensorName == (new LidarDevice())->name()) {
        centerSensor_ = std::make_unique<LidarDevice>();
    } else if (centerSensorName == (new CascadeDevice())->name()) {
        centerSensor_ = std::make_unique<CascadeDevice>();
    } else if (centerSensorName == (new SingleChipDevice())->name()) {
        centerSensor_ = std::make_unique<SingleChipDevice>();
    } else if (centerSensorName == (new ImuDevice())->name()) {
        centerSensor_ = std::make_unique<ImuDevice>();
    } else {
        throw std::runtime_error("Error: Unknown center sensor '" + centerSensorName + "'");
    }
}
References allowMapRebuild_, allowResample_, centerSensor_, cloudFov_, collapseElevation_, collapseElevationMaxZ_, collapseElevationMinZ_, exportClouds_, exportMap_, exportMapSamples_, forceMapRebuild_, forceResample_, coloradar::FovConfig::horizontalDegreesTotal, coloradar::BaseExportConfig::loadFromFile(), logOddsToProbability_, mapInputCloudFov_, mapResolution_, mapSampleFov_, occupancyThresholdPercent_, coloradar::internal::parseBoolYamlKey(), coloradar::internal::parseFloatYamlKey(), coloradar::FovConfig::rangeMeters, removeIntensityDim_, removeOccupancyDim_, saveMap_, saveSamples_, coloradar::FovConfig::useDegreeConstraints, and coloradar::FovConfig::verticalDegreesTotal.
logOddsToProbability()
const bool coloradar::LidarExportConfig::logOddsToProbability () const inline
Definition at line 285 of file device.h.
{ return logOddsToProbability_; }
References logOddsToProbability_.
mapInputCloudFov()
const FovConfig & coloradar::LidarExportConfig::mapInputCloudFov () const inline
Definition at line 282 of file device.h.
{ return mapInputCloudFov_; }
References mapInputCloudFov_.
mapResolution()
const float coloradar::LidarExportConfig::mapResolution () const inline
Definition at line 281 of file device.h.
{ return mapResolution_; }
References mapResolution_.
mapSampleFov()
const FovConfig & coloradar::LidarExportConfig::mapSampleFov () const inline
Definition at line 291 of file device.h.
{ return mapSampleFov_; }
References mapSampleFov_.
occupancyThresholdPercent()
const float coloradar::LidarExportConfig::occupancyThresholdPercent () const inline
Definition at line 286 of file device.h.
{ return occupancyThresholdPercent_; }
References occupancyThresholdPercent_.
operator=()
LidarExportConfig & coloradar::LidarExportConfig::operator= (const LidarExportConfig & other) inline
Definition at line 243 of file device.h.
{
        if (this != &other) {
            BaseExportConfig::operator=(other);
            collapseElevation_ = other.collapseElevation_;
            collapseElevationMinZ_ = other.collapseElevationMinZ_;
            collapseElevationMaxZ_ = other.collapseElevationMaxZ_;
            exportClouds_ = other.exportClouds_;
            removeIntensityDim_ = other.removeIntensityDim_;
            cloudFov_ = other.cloudFov_;
            exportMap_ = other.exportMap_;
            allowMapRebuild_ = other.allowMapRebuild_;
            forceMapRebuild_ = other.forceMapRebuild_;
            saveMap_ = other.saveMap_;
            mapResolution_ = other.mapResolution_;
            mapInputCloudFov_ = other.mapInputCloudFov_;
            exportMapSamples_ = other.exportMapSamples_;
            removeOccupancyDim_ = other.removeOccupancyDim_;
            logOddsToProbability_ = other.logOddsToProbability_;
            occupancyThresholdPercent_ = other.occupancyThresholdPercent_;
            allowResample_ = other.allowResample_;
            forceResample_ = other.forceResample_;
            saveSamples_ = other.saveSamples_;
            centerSensor_ = other.centerSensor_ ? std::make_unique<BaseDevice>(*other.centerSensor_) : nullptr;
            mapSampleFov_ = other.mapSampleFov_;
        }
        return *this;
    }
References allowMapRebuild_, allowResample_, centerSensor_, cloudFov_, collapseElevation_, collapseElevationMaxZ_, collapseElevationMinZ_, exportClouds_, exportMap_, exportMapSamples_, forceMapRebuild_, forceResample_, logOddsToProbability_, mapInputCloudFov_, mapResolution_, mapSampleFov_, occupancyThresholdPercent_, coloradar::BaseExportConfig::operator=(), removeIntensityDim_, removeOccupancyDim_, saveMap_, and saveSamples_.
removeIntensityDim()
const bool coloradar::LidarExportConfig::removeIntensityDim () const inline
Definition at line 275 of file device.h.
{ return removeIntensityDim_; }
References removeIntensityDim_.
removeOccupancyDim()
const bool coloradar::LidarExportConfig::removeOccupancyDim () const inline
Definition at line 284 of file device.h.
{ return removeOccupancyDim_; }
References removeOccupancyDim_.
saveMap()
const bool coloradar::LidarExportConfig::saveMap () const inline
Definition at line 280 of file device.h.
{ return saveMap_; }
References saveMap_.
saveSamples()
const bool coloradar::LidarExportConfig::saveSamples () const inline
Definition at line 289 of file device.h.
{ return saveSamples_; }
References saveSamples_.
validate()
void coloradar::LidarExportConfig::validate () override protected virtual
Reimplemented from coloradar::BaseExportConfig.
Definition at line 56 of file device.cpp.
{
    BaseExportConfig::validate();
    if (collapseElevation_) {
        if (collapseElevationMaxZ_ < collapseElevationMinZ_) {
            throw std::runtime_error("'collapse_elevation_max_z_meters' must be greater or equal to 'collapse_elevation_min_z_meters'.");
        }
    }
    if (exportClouds_) {
        if (cloudFov_.horizontalDegreesTotal < 0 || cloudFov_.horizontalDegreesTotal > 360) {
            throw std::runtime_error("cloud_fov: 'horizontal_degrees_total' must be a float between 0 and 360.");
        }
        if (cloudFov_.verticalDegreesTotal < 0 || cloudFov_.verticalDegreesTotal > 180) {
            throw std::runtime_error("cloud_fov: 'vertical_degrees_total' must be a float between 0 and 180.");
        }
    }
    if (exportMap_ || exportMapSamples_) {
        if (occupancyThresholdPercent_ < 0 || occupancyThresholdPercent_ > 100) {
            throw std::runtime_error("'occupancy_threshold_percent' must be a float between 0 and 100.");
        }
    }
    if (exportMap_) {
        if (mapResolution_ <= 0) {
            throw std::runtime_error("'map_resolution' must be positive.");
        }
        if (forceMapRebuild_ && !allowMapRebuild_) {
            throw std::runtime_error("cannot have 'force_map_rebuild' set to True when 'allow_map_rebuild' is set to False.");
        }
        if (mapInputCloudFov_.horizontalDegreesTotal < 0 || mapInputCloudFov_.horizontalDegreesTotal > 360) {
            throw std::runtime_error("map_input_cloud_fov: 'horizontal_degrees_total' must be a float between 0 and 360.");
        }
        if (mapInputCloudFov_.verticalDegreesTotal < 0 || mapInputCloudFov_.verticalDegreesTotal > 180) {
            throw std::runtime_error("map_input_cloud_fov: 'vertical_degrees_total' must be a float between 0 and 180.");
        }
    }
    if (exportMapSamples_) {
        if (!centerSensor_) {
            throw std::runtime_error("center sensor cannot be set empty.");
        }
        if (forceResample_ && !allowResample_) {
            throw std::runtime_error("cannot have 'force_resample' set to True when 'allow_resample' is set to False.");
        }
        if (mapSampleFov_.horizontalDegreesTotal < 0 || mapSampleFov_.horizontalDegreesTotal > 360) {
            throw std::runtime_error("map_sample_fov: 'horizontal_degrees_total' must be a float between 0 and 360.");
        }
        if (mapSampleFov_.verticalDegreesTotal < 0 || mapSampleFov_.verticalDegreesTotal > 180) {
            throw std::runtime_error("map_sample_fov: 'vertical_degrees_total' must be a float between 0 and 180.");
        }
    }
}
References allowMapRebuild_, allowResample_, centerSensor_, cloudFov_, collapseElevation_, collapseElevationMaxZ_, collapseElevationMinZ_, exportClouds_, exportMap_, exportMapSamples_, forceMapRebuild_, forceResample_, coloradar::FovConfig::horizontalDegreesTotal, mapInputCloudFov_, mapResolution_, mapSampleFov_, coloradar::BaseExportConfig::validate(), and coloradar::FovConfig::verticalDegreesTotal.
Member Data Documentation
allowMapRebuild_
bool coloradar::LidarExportConfig::allowMapRebuild_ protected
Definition at line 147 of file device.h.
allowResample_
bool coloradar::LidarExportConfig::allowResample_ protected
Definition at line 156 of file device.h.
centerSensor_
std::unique_ptr<BaseDevice> coloradar::LidarExportConfig::centerSensor_ protected
Definition at line 159 of file device.h.
cloudFov_
FovConfig coloradar::LidarExportConfig::cloudFov_ protected
Definition at line 144 of file device.h.
collapseElevation_
bool coloradar::LidarExportConfig::collapseElevation_ protected
Definition at line 138 of file device.h.
collapseElevationMaxZ_
float coloradar::LidarExportConfig::collapseElevationMaxZ_ protected
Definition at line 140 of file device.h.
collapseElevationMinZ_
float coloradar::LidarExportConfig::collapseElevationMinZ_ protected
Definition at line 139 of file device.h.
exportClouds_
bool coloradar::LidarExportConfig::exportClouds_ protected
Definition at line 142 of file device.h.
exportMap_
bool coloradar::LidarExportConfig::exportMap_ protected
Definition at line 146 of file device.h.
exportMapSamples_
bool coloradar::LidarExportConfig::exportMapSamples_ protected
Definition at line 152 of file device.h.
forceMapRebuild_
bool coloradar::LidarExportConfig::forceMapRebuild_ protected
Definition at line 148 of file device.h.
forceResample_
bool coloradar::LidarExportConfig::forceResample_ protected
Definition at line 157 of file device.h.
logOddsToProbability_
bool coloradar::LidarExportConfig::logOddsToProbability_ protected
Definition at line 154 of file device.h.
mapInputCloudFov_
FovConfig coloradar::LidarExportConfig::mapInputCloudFov_ protected
Definition at line 151 of file device.h.
mapResolution_
float coloradar::LidarExportConfig::mapResolution_ protected
Definition at line 150 of file device.h.
mapSampleFov_
FovConfig coloradar::LidarExportConfig::mapSampleFov_ protected
Definition at line 160 of file device.h.
occupancyThresholdPercent_
float coloradar::LidarExportConfig::occupancyThresholdPercent_ protected
Definition at line 155 of file device.h.
removeIntensityDim_
bool coloradar::LidarExportConfig::removeIntensityDim_ protected
Definition at line 143 of file device.h.
removeOccupancyDim_
bool coloradar::LidarExportConfig::removeOccupancyDim_ protected
Definition at line 153 of file device.h.
saveMap_
bool coloradar::LidarExportConfig::saveMap_ protected
Definition at line 149 of file device.h.
saveSamples_
bool coloradar::LidarExportConfig::saveSamples_ protected
Definition at line 158 of file device.h.
The documentation for this class was generated from the following files:
include/configs/device.h
src/configs/device.cpp