Coloradar Library: coloradar::H5Run Class Reference
coloradar::H5Run Class Reference
#include <h5_run.h>
Public Member Functions
H5Run (std::string name, std::shared_ptr< RadarConfig > cascadeRadarConfig=nullptr)
virtual ~H5Run ()=default
void setData (std::vector< double > poseTimestamps={}, std::vector< double > imuTimestamps={}, std::vector< double > lidarTimestamps={}, std::vector< double > cascadeCubeTimestamps={}, std::vector< double > cascadeTimestamps={}, std::vector< Eigen::Affine3f > poses={}, std::vector< pcl::PointCloud< pcl::PointXYZI >::Ptr > lidarPointclouds={}, std::vector< std::shared_ptr< std::vector< int16_t > > > cascadeDatacubes={}, std::vector< std::shared_ptr< std::vector< float > > > cascadeHeatmaps={}, std::vector< pcl::PointCloud< RadarPoint >::Ptr > cascadePointclouds={}, pcl::PointCloud< pcl::PointXYZI >::Ptr lidarOctomap={}, std::vector< pcl::PointCloud< pcl::PointXYZI >::Ptr > mapSamples={})
virtual std::shared_ptr< pcl::PointCloud< pcl::PointXYZI > > getLidarPointCloud (const int cloudIdx) const override
virtual std::shared_ptr< std::vector< int16_t > > getCascadeDatacube (const int cubeIdx) const override
virtual std::shared_ptr< std::vector< float > > getCascadeHeatmap (const int hmIdx) const override
virtual pcl::PointCloud< RadarPoint >::Ptr getCascadePointcloud (const int cloudIdx, const double intensityThreshold=0.0) const override
virtual pcl::PointCloud< pcl::PointXYZI >::Ptr getLidarOctomap () const override
virtual pcl::PointCloud< pcl::PointXYZI >::Ptr getMapSample (const int sampleIdx) const override
virtual void saveMapSample (const int sampleIdx, const pcl::PointCloud< pcl::PointXYZI >::Ptr sample) override
template<CloudType CloudT>
std::shared_ptr< CloudT > getLidarPointCloud (const int cloudIdx) const
Public Member Functions inherited from coloradar::Run
Run (std::string name, std::shared_ptr< RadarConfig > cascadeRadarConfig=nullptr)
virtual ~Run ()=default
const std::string & name () const noexcept
std::shared_ptr< RadarConfig > cascadeConfig () const noexcept
const std::vector< double > & poseTimestamps () const
const std::vector< double > & imuTimestamps () const
const std::vector< double > & lidarTimestamps () const
const std::vector< double > & cascadeCubeTimestamps () const
const std::vector< double > & cascadeTimestamps () const
template<PoseType PoseT>
std::vector< PoseT > getPoses () const
pcl::PointCloud< pcl::PointXYZI >::Ptr sampleMapFrame (const float horizontalFov, const float verticalFov, const float range, const Eigen::Affine3f &mapFramePose, const pcl::PointCloud< pcl::PointXYZI >::Ptr mapCloud)
Protected Attributes
std::vector< std::shared_ptr< std::vector< int16_t > > > cascadeDatacubes_
std::vector< std::shared_ptr< std::vector< float > > > cascadeHeatmaps_
std::vector< pcl::PointCloud< RadarPoint >::Ptr > cascadePointclouds_
std::vector< pcl::PointCloud< pcl::PointXYZI >::Ptr > lidarPointclouds_
pcl::PointCloud< pcl::PointXYZI >::Ptr lidarOctomap_
std::vector< pcl::PointCloud< pcl::PointXYZI >::Ptr > mapSamples_
Protected Attributes inherited from coloradar::Run
std::string name_
std::shared_ptr< RadarConfig > cascadeConfig_
std::vector< double > poseTimestamps_
std::vector< double > imuTimestamps_
std::vector< double > lidarTimestamps_
std::vector< double > cascadeCubeTimestamps_
std::vector< double > cascadeTimestamps_
std::vector< Eigen::Affine3f > poses_
Detailed Description
Definition at line 9 of file h5_run.h.
Constructor & Destructor Documentation
H5Run()
coloradar::H5Run::H5Run (std::string name, std::shared_ptr< RadarConfig > cascadeRadarConfig = nullptr) inline
Definition at line 20 of file h5_run.h.
: Run(std::move(name), std::move(cascadeRadarConfig)) {}
~H5Run()
virtual coloradar::H5Run::~H5Run () virtual default
Member Function Documentation
getCascadeDatacube()
std::shared_ptr< std::vector< int16_t > > coloradar::H5Run::getCascadeDatacube (const int cubeIdx) const override virtual
Implements coloradar::Run.
Definition at line 95 of file h5_run.cpp.
{
    // if (cascadeDatacubes_.empty()) throw std::runtime_error("No cascade datacubes found in run " + name_);
    if (cubeIdx < 0 || cubeIdx >= cascadeDatacubes_.size()) throw std::invalid_argument("H5Run: 'cubeIdx' out of bounds [0, " + std::to_string(cascadeDatacubes_.size()) + ")");
    return cascadeDatacubes_[cubeIdx];
}
References cascadeDatacubes_.
getCascadeHeatmap()
std::shared_ptr< std::vector< float > > coloradar::H5Run::getCascadeHeatmap (const int hmIdx) const override virtual
Implements coloradar::Run.
Definition at line 102 of file h5_run.cpp.
{
    // if (cascadeHeatmaps_.empty()) throw std::runtime_error("No cascade heatmaps found in run " + name_);
    if (hmIdx < 0 || hmIdx >= cascadeHeatmaps_.size()) throw std::invalid_argument("H5Run: 'hmIdx' out of bounds [0, " + std::to_string(cascadeHeatmaps_.size()) + ")");
    return cascadeHeatmaps_[hmIdx];
}
References cascadeHeatmaps_.
getCascadePointcloud()
pcl::PointCloud< RadarPoint >::Ptr coloradar::H5Run::getCascadePointcloud (const int cloudIdx, const double intensityThreshold = 0.0) const override virtual
Implements coloradar::Run.
Definition at line 109 of file h5_run.cpp.
{
    // if (cascadePointclouds_.empty()) throw std::runtime_error("No cascade pointclouds found in run " + name_);
    if (cloudIdx < 0 || cloudIdx >= cascadePointclouds_.size()) throw std::invalid_argument("H5Run: 'cloudIdx' out of bounds [0, " + std::to_string(cascadePointclouds_.size()) + ")");
    if (intensityThreshold < 0.0) throw std::invalid_argument("H5Run: 'intensityThreshold' must be non-negative");
    if (intensityThreshold > 0.0) {
        pcl::PointCloud<RadarPoint>::Ptr cloud(new pcl::PointCloud<RadarPoint>());
        for (const auto& point : *cascadePointclouds_[cloudIdx]) {
            if (point.intensity >= intensityThreshold) {
                cloud->points.push_back(point);
            }
        }
        return cloud;
    }
    return cascadePointclouds_[cloudIdx];
}
References cascadePointclouds_.
getLidarOctomap()
pcl::PointCloud< pcl::PointXYZI >::Ptr coloradar::H5Run::getLidarOctomap () const override virtual
Implements coloradar::Run.
Definition at line 126 of file h5_run.cpp.
{
    // if (!lidarOctomap_) throw std::runtime_error("No lidar octomap found in run " + name_);
    return lidarOctomap_;
}
References lidarOctomap_.
getLidarPointCloud() [1/2]
template<CloudType CloudT> std::shared_ptr< CloudT > coloradar::H5Run::getLidarPointCloud (const int cloudIdx) const virtual
Implements coloradar::Run.
Definition at line 9 of file h5_run.hpp.
{
    if (lidarPointclouds_.empty()) throw std::runtime_error("No lidar point clouds found in run " + name_);
    if (cloudIdx < 0 || cloudIdx >= lidarPointclouds_.size()) throw std::invalid_argument("H5Run: 'cloudIdx' out of bounds [0, " + std::to_string(lidarPointclouds_.size()) + ")");
    return std::dynamic_pointer_cast<CloudT>(lidarPointclouds_[cloudIdx]);
}
References lidarPointclouds_, and coloradar::Run::name_.
getLidarPointCloud() [2/2]
pcl::PointCloud< pcl::PointXYZI >::Ptr coloradar::H5Run::getLidarPointCloud (const int cloudIdx) const override virtual
Implements coloradar::Run.
Definition at line 88 of file h5_run.cpp.
{
    // if (lidarPointclouds_.empty()) throw std::runtime_error("No lidar pointclouds found in run " + name_);
    if (cloudIdx < 0 || cloudIdx >= lidarPointclouds_.size()) throw std::invalid_argument("H5Run: 'cloudIdx' out of bounds [0, " + std::to_string(lidarPointclouds_.size()) + ")");
    return lidarPointclouds_[cloudIdx];
}
References lidarPointclouds_.
getMapSample()
pcl::PointCloud< pcl::PointXYZI >::Ptr coloradar::H5Run::getMapSample (const int sampleIdx) const override virtual
Implements coloradar::Run.
Definition at line 131 of file h5_run.cpp.
{
    // if (!mapSamples_.empty()) throw std::runtime_error("No map samples found in run " + name_);
    if (sampleIdx < 0 || sampleIdx >= mapSamples_.size()) throw std::invalid_argument("H5Run: 'sampleIdx' out of bounds [0, " + std::to_string(mapSamples_.size()) + ")");
    return mapSamples_[sampleIdx];
}
References mapSamples_.
saveMapSample()
void coloradar::H5Run::saveMapSample (const int sampleIdx, const pcl::PointCloud< pcl::PointXYZI >::Ptr sample) override virtual
Implements coloradar::Run.
Definition at line 137 of file h5_run.cpp.
{
    if (sampleIdx < 0) throw std::invalid_argument("H5Run: 'sampleIdx' out of bounds [0, " + std::to_string(mapSamples_.size()) + ")");
    if (sampleIdx >= mapSamples_.size()) mapSamples_.resize(sampleIdx + 1);
    mapSamples_[sampleIdx] = sample;
}
References mapSamples_.
setData()
void coloradar::H5Run::setData (std::vector< double > poseTimestamps = {}, std::vector< double > imuTimestamps = {}, std::vector< double > lidarTimestamps = {}, std::vector< double > cascadeCubeTimestamps = {}, std::vector< double > cascadeTimestamps = {}, std::vector< Eigen::Affine3f > poses = {}, std::vector< pcl::PointCloud< pcl::PointXYZI >::Ptr > lidarPointclouds = {}, std::vector< std::shared_ptr< std::vector< int16_t > > > cascadeDatacubes = {}, std::vector< std::shared_ptr< std::vector< float > > > cascadeHeatmaps = {}, std::vector< pcl::PointCloud< RadarPoint >::Ptr > cascadePointclouds = {}, pcl::PointCloud< pcl::PointXYZI >::Ptr lidarOctomap = {}, std::vector< pcl::PointCloud< pcl::PointXYZI >::Ptr > mapSamples = {})
Definition at line 7 of file h5_run.cpp.
  {
    // pose data
    if (!poseTimestamps.empty() && !poses.empty() && poseTimestamps.size() != poses.size())
        throw std::invalid_argument("Data length mismatch in run " + name_ + ": 'poseTimestamps' (" + std::to_string(poseTimestamps.size()) + ") vs 'poses' (" + std::to_string(poses.size()) + ").");
    poseTimestamps_ = poseTimestamps;
    poses_ = poses;
    // imu data
    // if (!imuTimestamps.empty() && !imuPoses.empty() && imuTimestamps.size() != imuPoses.size())
    //     throw std::invalid_argument("H5Run::setData() Length Mismatch: 'imuTimestamps' (" + std::to_string(imuTimestamps.size()) + ") vs 'imuPoses' (" + std::to_string(imuPoses.size()) + ").");
    imuTimestamps_ = imuTimestamps;
    // imuPoses_ = imuPoses;
    // lidar data
    if (!lidarTimestamps.empty() && !lidarPointclouds.empty() && lidarTimestamps.size() != lidarPointclouds.size())
        throw std::invalid_argument(
            "Data length mismatch in run " + name_ + ": 'lidarTimestamps' (" + std::to_string(lidarTimestamps.size()) + ")"
            " vs 'lidarPointclouds' (" + std::to_string(lidarPointclouds.size()) + ")."
        );
    lidarTimestamps_ = lidarTimestamps;
    lidarPointclouds_ = lidarPointclouds;
    lidarOctomap_ = lidarOctomap;
    mapSamples_ = mapSamples;
    // datacube data
    if (!cascadeCubeTimestamps.empty() && !cascadeDatacubes.empty() && cascadeCubeTimestamps.size() != cascadeDatacubes.size())
        throw std::invalid_argument(
            "Data length mismatch in run " + name_ + ": 'cascadeCubeTimestamps' (" + std::to_string(cascadeCubeTimestamps.size()) + ")"
            " vs 'cascadeDatacubes' (" + std::to_string(cascadeDatacubes.size()) + ")."
        );
    if (!cascadeDatacubes.empty()) {
        if (!cascadeDatacubes[0]) throw std::invalid_argument("cascadeDatacubes[0] is null.");
        const std::size_t refSize = cascadeDatacubes[0]->size();
        for (std::size_t i = 1; i < cascadeDatacubes.size(); ++i) {
            if (!cascadeDatacubes[i]) throw std::invalid_argument("cascadeDatacubes[" + std::to_string(i) + "] is null.");
            if (cascadeDatacubes[i]->size() != refSize) throw std::invalid_argument("Expected datacube size " + std::to_string(refSize) + ", got " + std::to_string(cascadeDatacubes[i]->size()) + " at index " + std::to_string(i) + ".");
        }
    }
    cascadeCubeTimestamps_ = cascadeCubeTimestamps;
    cascadeDatacubes_ = cascadeDatacubes;
    // heatmap data
    int numHeatmaps = 0;
    if (!cascadeTimestamps.empty()) numHeatmaps = cascadeHeatmaps.size();
    if (!cascadeHeatmaps.empty()) {
        if (numHeatmaps == 0) numHeatmaps = cascadeHeatmaps.size();
        else if (cascadeHeatmaps.size() != numHeatmaps)
            throw std::invalid_argument("Expected " + std::to_string(numHeatmaps) + " cascade heatmaps, got " + std::to_string(cascadeHeatmaps.size()) + ".");
    }
    if (!cascadePointclouds.empty()) {
        if (numHeatmaps == 0) numHeatmaps = cascadePointclouds.size();
        else if (cascadePointclouds.size() != numHeatmaps)
            throw std::invalid_argument("Expected " + std::to_string(numHeatmaps) + " cascade pointclouds, got " + std::to_string(cascadePointclouds.size()) + ".");
    }
    if (!cascadeHeatmaps.empty()) {
        if (!cascadeHeatmaps[0]) throw std::invalid_argument("cascadeHeatmaps[0] is null.");
        const std::size_t refSize = cascadeHeatmaps[0]->size();
        for (std::size_t i = 1; i < cascadeHeatmaps.size(); ++i) {
            if (!cascadeHeatmaps[i]) throw std::invalid_argument("cascadeHeatmaps[" + std::to_string(i) + "] is null.");
            if (cascadeHeatmaps[i]->size() != refSize) throw std::invalid_argument("Expected heatmap size " + std::to_string(refSize) + ", got " + std::to_string(cascadeHeatmaps[i]->size()) + " at index " + std::to_string(i) + ".");
        }
    }
    cascadeTimestamps_ = cascadeTimestamps;
    cascadeHeatmaps_ = cascadeHeatmaps;
    cascadePointclouds_ = cascadePointclouds;
}
References coloradar::Run::cascadeCubeTimestamps(), coloradar::Run::cascadeCubeTimestamps_, cascadeDatacubes_, cascadeHeatmaps_, cascadePointclouds_, coloradar::Run::cascadeTimestamps(), coloradar::Run::cascadeTimestamps_, coloradar::Run::imuTimestamps(), coloradar::Run::imuTimestamps_, lidarOctomap_, lidarPointclouds_, coloradar::Run::lidarTimestamps(), coloradar::Run::lidarTimestamps_, mapSamples_, coloradar::Run::name_, coloradar::Run::poses_, coloradar::Run::poseTimestamps(), and coloradar::Run::poseTimestamps_.
Member Data Documentation
cascadeDatacubes_
std::vector<std::shared_ptr<std::vector<int16_t> > > coloradar::H5Run::cascadeDatacubes_ protected
Definition at line 12 of file h5_run.h.
cascadeHeatmaps_
std::vector<std::shared_ptr<std::vector<float> > > coloradar::H5Run::cascadeHeatmaps_ protected
Definition at line 13 of file h5_run.h.
cascadePointclouds_
std::vector<pcl::PointCloud<RadarPoint>::Ptr> coloradar::H5Run::cascadePointclouds_ protected
Definition at line 14 of file h5_run.h.
lidarOctomap_
pcl::PointCloud<pcl::PointXYZI>::Ptr coloradar::H5Run::lidarOctomap_ protected
Definition at line 16 of file h5_run.h.
lidarPointclouds_
std::vector<pcl::PointCloud<pcl::PointXYZI>::Ptr> coloradar::H5Run::lidarPointclouds_ protected
Definition at line 15 of file h5_run.h.
mapSamples_
std::vector<pcl::PointCloud<pcl::PointXYZI>::Ptr> coloradar::H5Run::mapSamples_ protected
Definition at line 17 of file h5_run.h.
The documentation for this class was generated from the following files:
include/run/h5_run.h
include/run/h5_run.hpp
src/run/h5_run.cpp