Coloradar Library: coloradar::RadarExportConfig Class Reference
coloradar::RadarExportConfig Class Reference
#include <device.h>
Public Member Functions
RadarExportConfig (bool exportPoses=false, bool exportTimestamps=false, bool collapseElevation=false, float collapseElevationMinZ=0.0f, float collapseElevationMaxZ=0.0f, bool removeDopplerDim=false, FovConfig heatmapCloudFov=FovConfig(), bool exportDatacubes=false, bool exportHeatmaps=false, bool exportClouds=false, double intensityThreshold=0.0f, bool cloudsInGlobalFrame=false)
RadarExportConfig (const RadarExportConfig &other)=default
RadarExportConfig & operator= (const RadarExportConfig &other)=default
const bool collapseElevation () const
const float collapseElevationMinZ () const
const float collapseElevationMaxZ () const
const bool removeDopplerDim () const
const FovConfig & heatmapCloudFov () const
const bool exportDatacubes () const
const bool exportHeatmaps () const
const bool exportClouds () const
const double intensityThreshold () const
const bool cloudsInGlobalFrame () const
void loadFromFile (const YAML::Node &deviceNode) override
Public Member Functions inherited from coloradar::BaseExportConfig
BaseExportConfig (bool exportPoses=false, bool exportTimestamps=false)
BaseExportConfig (const BaseExportConfig &other)=default
BaseExportConfig & operator= (const BaseExportConfig &other)=default
const bool exportPoses () const
const bool exportTimestamps () const
Protected Member Functions
virtual void validate () override
Protected Attributes
bool collapseElevation_
float collapseElevationMinZ_
float collapseElevationMaxZ_
bool removeDopplerDim_
FovConfig heatmapCloudFov_
bool exportDatacubes_
bool exportHeatmaps_
bool exportClouds_
double intensityThreshold_
bool cloudsInGlobalFrame_
Protected Attributes inherited from coloradar::BaseExportConfig
bool exportPoses_
bool exportTimestamps_
Detailed Description
Definition at line 73 of file device.h.
Constructor & Destructor Documentation
RadarExportConfig() [1/2]
coloradar::RadarExportConfig::RadarExportConfig (bool exportPoses = false, bool exportTimestamps = false, bool collapseElevation = false, float collapseElevationMinZ = 0.0f, float collapseElevationMaxZ = 0.0f, bool removeDopplerDim = false, FovConfig heatmapCloudFov = FovConfig(), bool exportDatacubes = false, bool exportHeatmaps = false, bool exportClouds = false, double intensityThreshold = 0.0f, bool cloudsInGlobalFrame = false) inline
Definition at line 90 of file device.h.
      : BaseExportConfig(exportPoses, exportTimestamps),
        collapseElevation_(collapseElevation),
        collapseElevationMinZ_(collapseElevationMinZ),
        collapseElevationMaxZ_(collapseElevationMaxZ),
        removeDopplerDim_(removeDopplerDim),
        heatmapCloudFov_(heatmapCloudFov),
        exportDatacubes_(exportDatacubes),
        exportHeatmaps_(exportHeatmaps),
        exportClouds_(exportClouds),
        intensityThreshold_(intensityThreshold),
        cloudsInGlobalFrame_(cloudsInGlobalFrame) {
        validate();
    }
References validate().
RadarExportConfig() [2/2]
coloradar::RadarExportConfig::RadarExportConfig (const RadarExportConfig & other) default
Member Function Documentation
cloudsInGlobalFrame()
const bool coloradar::RadarExportConfig::cloudsInGlobalFrame () const inline
Definition at line 131 of file device.h.
{ return cloudsInGlobalFrame_; }
References cloudsInGlobalFrame_.
collapseElevation()
const bool coloradar::RadarExportConfig::collapseElevation () const inline
Definition at line 122 of file device.h.
{ return collapseElevation_; }
References collapseElevation_.
collapseElevationMaxZ()
const float coloradar::RadarExportConfig::collapseElevationMaxZ () const inline
Definition at line 124 of file device.h.
{ return collapseElevationMaxZ_; }
References collapseElevationMaxZ_.
collapseElevationMinZ()
const float coloradar::RadarExportConfig::collapseElevationMinZ () const inline
Definition at line 123 of file device.h.
{ return collapseElevationMinZ_; }
References collapseElevationMinZ_.
exportClouds()
const bool coloradar::RadarExportConfig::exportClouds () const inline
Definition at line 129 of file device.h.
{ return exportClouds_; }
References exportClouds_.
exportDatacubes()
const bool coloradar::RadarExportConfig::exportDatacubes () const inline
Definition at line 127 of file device.h.
{ return exportDatacubes_; }
References exportDatacubes_.
exportHeatmaps()
const bool coloradar::RadarExportConfig::exportHeatmaps () const inline
Definition at line 128 of file device.h.
{ return exportHeatmaps_; }
References exportHeatmaps_.
heatmapCloudFov()
const FovConfig & coloradar::RadarExportConfig::heatmapCloudFov () const inline
Definition at line 126 of file device.h.
{ return heatmapCloudFov_; }
References heatmapCloudFov_.
intensityThreshold()
const double coloradar::RadarExportConfig::intensityThreshold () const inline
Definition at line 130 of file device.h.
{ return intensityThreshold_; }
References intensityThreshold_.
loadFromFile()
void coloradar::RadarExportConfig::loadFromFile (const YAML::Node & deviceNode) override virtual
Reimplemented from coloradar::BaseExportConfig.
Definition at line 112 of file device.cpp.
{
    BaseExportConfig::loadFromFile(deviceNode);
    collapseElevation_ = coloradar::internal::parseBoolYamlKey(deviceNode["collapse_elevation"], collapseElevation_);
    collapseElevationMinZ_ = coloradar::internal::parseFloatYamlKey(deviceNode["collapse_elevation_min_z_meters"], collapseElevationMinZ_);
    collapseElevationMaxZ_ = coloradar::internal::parseFloatYamlKey(deviceNode["collapse_elevation_max_z_meters"], collapseElevationMaxZ_);
    removeDopplerDim_ = coloradar::internal::parseBoolYamlKey(deviceNode["remove_doppler_dim"], removeDopplerDim_);
    int azimuthIdx = coloradar::internal::parseIntYamlKey(deviceNode["fov_azimuth_idx"], heatmapCloudFov_.azimuthIdx);
    int elevationIdx = coloradar::internal::parseIntYamlKey(deviceNode["fov_elevation_idx"], heatmapCloudFov_.elevationIdx);
    int horizontalDegreesTotal = coloradar::internal::parseFloatYamlKey(deviceNode["horizontal_fov_degrees_total"], heatmapCloudFov_.horizontalDegreesTotal);
    int verticalDegreesTotal = coloradar::internal::parseFloatYamlKey(deviceNode["vertical_fov_degrees_total"], heatmapCloudFov_.verticalDegreesTotal);
    heatmapCloudFov_.rangeMeters = coloradar::internal::parseFloatYamlKey(deviceNode["range_meters"], heatmapCloudFov_.rangeMeters);
    if (azimuthIdx >= 0 || elevationIdx >= 0                                     // non-default idx values
       || (horizontalDegreesTotal == heatmapCloudFov_.horizontalDegreesTotal     // default horizontal degree value
           && verticalDegreesTotal == heatmapCloudFov_.verticalDegreesTotal)) {  // default vertical degree value
            heatmapCloudFov_.useDegreeConstraints = false;
    }
    heatmapCloudFov_.azimuthIdx = azimuthIdx;
    heatmapCloudFov_.elevationIdx = elevationIdx;
    heatmapCloudFov_.horizontalDegreesTotal = horizontalDegreesTotal;
    heatmapCloudFov_.verticalDegreesTotal = verticalDegreesTotal;
    exportDatacubes_ = coloradar::internal::parseBoolYamlKey(deviceNode["export_datacubes"], exportDatacubes_);
    exportHeatmaps_ = coloradar::internal::parseBoolYamlKey(deviceNode["export_heatmaps"], exportHeatmaps_);
    exportClouds_ = coloradar::internal::parseBoolYamlKey(deviceNode["export_clouds"], exportClouds_);
    intensityThreshold_ = coloradar::internal::parseFloatYamlKey(deviceNode["intensity_threshold"], intensityThreshold_);
    cloudsInGlobalFrame_ = coloradar::internal::parseBoolYamlKey(deviceNode["clouds_in_global_frame"], cloudsInGlobalFrame_);
    auto heatmapCloudFovNode = deviceNode["heatmap_cloud_fov"];
    if (heatmapCloudFovNode) {
        heatmapCloudFov_.azimuthIdx = coloradar::internal::parseIntYamlKey(heatmapCloudFovNode["azimuth_idx"], heatmapCloudFov_.azimuthIdx);
        heatmapCloudFov_.elevationIdx = coloradar::internal::parseIntYamlKey(heatmapCloudFovNode["elevation_idx"], heatmapCloudFov_.elevationIdx);
        heatmapCloudFov_.horizontalDegreesTotal = coloradar::internal::parseFloatYamlKey(heatmapCloudFovNode["horizontal_degrees_total"], heatmapCloudFov_.horizontalDegreesTotal);
        heatmapCloudFov_.verticalDegreesTotal = coloradar::internal::parseFloatYamlKey(heatmapCloudFovNode["vertical_degrees_total"], heatmapCloudFov_.verticalDegreesTotal);
        heatmapCloudFov_.rangeMeters = coloradar::internal::parseFloatYamlKey(heatmapCloudFovNode["range_meters"], heatmapCloudFov_.rangeMeters);
    }
}
References coloradar::FovConfig::azimuthIdx, cloudsInGlobalFrame_, collapseElevation_, collapseElevationMaxZ_, collapseElevationMinZ_, coloradar::FovConfig::elevationIdx, exportClouds_, exportDatacubes_, exportHeatmaps_, heatmapCloudFov_, coloradar::FovConfig::horizontalDegreesTotal, intensityThreshold_, coloradar::BaseExportConfig::loadFromFile(), coloradar::internal::parseBoolYamlKey(), coloradar::internal::parseFloatYamlKey(), coloradar::internal::parseIntYamlKey(), coloradar::FovConfig::rangeMeters, removeDopplerDim_, coloradar::FovConfig::useDegreeConstraints, and coloradar::FovConfig::verticalDegreesTotal.
operator=()
RadarExportConfig & coloradar::RadarExportConfig::operator= (const RadarExportConfig & other) default
removeDopplerDim()
const bool coloradar::RadarExportConfig::removeDopplerDim () const inline
Definition at line 125 of file device.h.
{ return removeDopplerDim_; }
References removeDopplerDim_.
validate()
void coloradar::RadarExportConfig::validate () override protected virtual
Reimplemented from coloradar::BaseExportConfig.
Definition at line 33 of file device.cpp.
{
    BaseExportConfig::validate();
    if (collapseElevation_) {
        if (collapseElevationMaxZ_ < collapseElevationMinZ_) {
            throw std::runtime_error("'collapse_elevation_max_z_meters' must be greater or equal to 'collapse_elevation_min_z_meters'.");
        }
    }
    if (heatmapCloudFov_.useDegreeConstraints) {
        if (heatmapCloudFov_.horizontalDegreesTotal < 0 || heatmapCloudFov_.horizontalDegreesTotal > 360) {
            throw std::runtime_error("heatmap_cloud_fov: 'horizontal_degrees_total' must be a float between 0 and 360.");
        }
        if (heatmapCloudFov_.verticalDegreesTotal < 0 || heatmapCloudFov_.verticalDegreesTotal > 180) {
            throw std::runtime_error("heatmap_cloud_fov: 'vertical_degrees_total' must be a float between 0 and 180.");
        }
    }
    if (exportClouds_) {
        if (intensityThreshold_ < 0) {
            throw std::runtime_error("'intensity_threshold' must be non-negative.");
        }
    }
}
References collapseElevation_, collapseElevationMaxZ_, collapseElevationMinZ_, exportClouds_, heatmapCloudFov_, coloradar::FovConfig::horizontalDegreesTotal, intensityThreshold_, coloradar::FovConfig::useDegreeConstraints, coloradar::BaseExportConfig::validate(), and coloradar::FovConfig::verticalDegreesTotal.
Member Data Documentation
cloudsInGlobalFrame_
bool coloradar::RadarExportConfig::cloudsInGlobalFrame_ protected
Definition at line 85 of file device.h.
collapseElevation_
bool coloradar::RadarExportConfig::collapseElevation_ protected
Definition at line 75 of file device.h.
collapseElevationMaxZ_
float coloradar::RadarExportConfig::collapseElevationMaxZ_ protected
Definition at line 77 of file device.h.
collapseElevationMinZ_
float coloradar::RadarExportConfig::collapseElevationMinZ_ protected
Definition at line 76 of file device.h.
exportClouds_
bool coloradar::RadarExportConfig::exportClouds_ protected
Definition at line 83 of file device.h.
exportDatacubes_
bool coloradar::RadarExportConfig::exportDatacubes_ protected
Definition at line 81 of file device.h.
exportHeatmaps_
bool coloradar::RadarExportConfig::exportHeatmaps_ protected
Definition at line 82 of file device.h.
heatmapCloudFov_
FovConfig coloradar::RadarExportConfig::heatmapCloudFov_ protected
Definition at line 79 of file device.h.
intensityThreshold_
double coloradar::RadarExportConfig::intensityThreshold_ protected
Definition at line 84 of file device.h.
removeDopplerDim_
bool coloradar::RadarExportConfig::removeDopplerDim_ protected
Definition at line 78 of file device.h.
The documentation for this class was generated from the following files:
include/configs/device.h
src/configs/device.cpp