Coloradar Library: coloradar::DatasetExportConfig Class Reference
coloradar::DatasetExportConfig Class Reference
#include <dataset_configs.h>
Public Member Functions
DatasetExportConfig (const std::string &yamlFilePath)
DatasetExportConfig (const std::filesystem::path &destinationFilePath="dataset.h5", const std::vector< std::string > &runs={}, bool exportTransforms=true, const RadarExportConfig &cascadeCfg=RadarExportConfig(), const LidarExportConfig &lidarCfg=LidarExportConfig(), const BaseExportConfig &baseCfg=BaseExportConfig(), const ImuExportConfig &imuCfg=ImuExportConfig(), const RadarExportConfig &singleChipCfg=RadarExportConfig())
const std::filesystem::path & destinationFilePath () const
const std::vector< std::string > & runs () const
bool exportTransforms () const
std::span< const std::unique_ptr< BaseDevice > > devices () const
void initDataset (std::vector< std::string > runNames={}, std::span< const std::unique_ptr< BaseDevice > > devices={})
const RadarExportConfig & cascade () const
const LidarExportConfig & lidar () const
const BaseExportConfig & base () const
const ImuExportConfig & imu () const
Protected Member Functions
void validateConfigYaml (const YAML::Node &config)
std::filesystem::path parseDestination (const YAML::Node &destinationValue, const std::filesystem::path &defaultDestination)
std::vector< std::string > parseRuns (const YAML::Node &runsValue)
std::filesystem::path validateDestination (const std::filesystem::path &destination)
std::vector< std::string > validateRuns (const std::vector< std::string > &runs)
Protected Attributes
std::filesystem::path destinationFilePath_ = "dataset.h5"
std::vector< std::string > runs_ = {}
bool exportTransforms_ = true
std::span< const std::unique_ptr< BaseDevice > > devices_
RadarExportConfig cascadeCfg_
LidarExportConfig lidarCfg_
ImuExportConfig imuCfg_
BaseExportConfig baseCfg_
RadarExportConfig singleChipCfg_
Detailed Description
Definition at line 9 of file dataset_configs.h.
Constructor & Destructor Documentation
DatasetExportConfig() [1/2]
coloradar::DatasetExportConfig::DatasetExportConfig (const std::string & yamlFilePath)
Definition at line 101 of file dataset_configs.cpp.
{
    YAML::Node config = YAML::LoadFile(yamlFilePath);
    validateConfigYaml(config);
    destinationFilePath_ = parseDestination(config["global"]["destination_file"], destinationFilePath_);
    runs_ = parseRuns(config["global"]["runs"]);
    // std::cout << "DatasetExportConfig(): parsed " << runs_.size() << " runs: ";
    for (const auto &run : runs_) {
        std::cout << run << " ";
    }
    std::cout << std::endl;
    exportTransforms_ = coloradar::internal::parseBoolYamlKey(config["global"]["export_transforms"], exportTransforms_);
    cascadeCfg_.loadFromFile(config["devices"]["cascade_radar"]);
    lidarCfg_.loadFromFile(config["devices"]["lidar"]);
    baseCfg_.loadFromFile(config["devices"]["base"]);
    imuCfg_.loadFromFile(config["devices"]["imu"]);
    singleChipCfg_.loadFromFile(config["devices"]["single_chip_radar"]);
    std::vector<BaseExportConfig*> deviceConfigs = {&cascadeCfg_, &lidarCfg_, &baseCfg_, &imuCfg_, &singleChipCfg_};
    for (auto* deviceCfg : deviceConfigs) {
        if (lidarCfg_.centerSensor() && typeid(*lidarCfg_.centerSensor()->exportConfig()) == typeid(*deviceCfg)) {
            lidarCfg_.centerSensor()->loadExportConfig(deviceCfg);
        }
    }
}
References baseCfg_, cascadeCfg_, coloradar::LidarExportConfig::centerSensor(), destinationFilePath_, coloradar::BaseDevice::exportConfig(), exportTransforms_, imuCfg_, lidarCfg_, coloradar::BaseDevice::loadExportConfig(), coloradar::BaseExportConfig::loadFromFile(), coloradar::RadarExportConfig::loadFromFile(), coloradar::LidarExportConfig::loadFromFile(), coloradar::ImuExportConfig::loadFromFile(), coloradar::internal::parseBoolYamlKey(), parseDestination(), parseRuns(), runs_, singleChipCfg_, and validateConfigYaml().
DatasetExportConfig() [2/2]
coloradar::DatasetExportConfig::DatasetExportConfig (const std::filesystem::path & destinationFilePath = "dataset.h5", const std::vector< std::string > & runs = {}, bool exportTransforms = true, const RadarExportConfig & cascadeCfg = RadarExportConfig(), const LidarExportConfig & lidarCfg = LidarExportConfig(), const BaseExportConfig & baseCfg = BaseExportConfig(), const ImuExportConfig & imuCfg = ImuExportConfig(), const RadarExportConfig & singleChipCfg = RadarExportConfig())
Definition at line 82 of file dataset_configs.cpp.
  : destinationFilePath_(validateDestination(destinationFilePath)),
    runs_(validateRuns(runs)),
    exportTransforms_(exportTransforms),
    cascadeCfg_(cascadeCfg),
    lidarCfg_(lidarCfg),
    baseCfg_(baseCfg),
    imuCfg_(imuCfg),
    singleChipCfg_(singleChipCfg) {}
Member Function Documentation
base()
const BaseExportConfig & coloradar::DatasetExportConfig::base () const inline
Definition at line 52 of file dataset_configs.h.
{ return baseCfg_; }
References baseCfg_.
cascade()
const RadarExportConfig & coloradar::DatasetExportConfig::cascade () const inline
Definition at line 50 of file dataset_configs.h.
{ return cascadeCfg_; }
References cascadeCfg_.
destinationFilePath()
const std::filesystem::path & coloradar::DatasetExportConfig::destinationFilePath () const
Definition at line 128 of file dataset_configs.cpp.
{
    return destinationFilePath_;
}
References destinationFilePath_.
devices()
std::span< const std::unique_ptr< BaseDevice > > coloradar::DatasetExportConfig::devices () const inline
Definition at line 46 of file dataset_configs.h.
{ return devices_; }
References devices_.
exportTransforms()
bool coloradar::DatasetExportConfig::exportTransforms () const
Definition at line 136 of file dataset_configs.cpp.
{
    return exportTransforms_;
}
References exportTransforms_.
imu()
const ImuExportConfig & coloradar::DatasetExportConfig::imu () const inline
Definition at line 53 of file dataset_configs.h.
{ return imuCfg_; }
References imuCfg_.
initDataset()
void coloradar::DatasetExportConfig::initDataset (std::vector< std::string > runNames = {}, std::span< const std::unique_ptr< BaseDevice > > devices = {})
Definition at line 140 of file dataset_configs.cpp.
{
    if (!runNames.empty()) {
        runs_ = validateRuns(runNames);
    }
    if (!devices.empty()) {
        devices_ = devices;
    }
}
References devices(), devices_, runs_, and validateRuns().
lidar()
const LidarExportConfig & coloradar::DatasetExportConfig::lidar () const inline
Definition at line 51 of file dataset_configs.h.
{ return lidarCfg_; }
References lidarCfg_.
parseDestination()
std::filesystem::path coloradar::DatasetExportConfig::parseDestination (const YAML::Node & destinationValue, const std::filesystem::path & defaultDestination) protected
Definition at line 18 of file dataset_configs.cpp.
{
    std::filesystem::path destination;
    if (!destinationValue) {
        destination = defaultDestination;
    } else {
        destination = destinationValue.as<std::string>();
    }
    return validateDestination(destination);
}
References validateDestination().
parseRuns()
std::vector< std::string > coloradar::DatasetExportConfig::parseRuns (const YAML::Node & runsValue) protected
Definition at line 29 of file dataset_configs.cpp.
{
    if (!runsValue || runsValue.IsNull()) return {};
    std::vector<std::string> runs;
    if (runsValue.IsScalar()) {
        std::string run = runsValue.as<std::string>();
        runs.push_back(run);
    } else if (runsValue.IsSequence()) {
        for (const auto &n : runsValue) {
            if (!n.IsScalar()) throw std::runtime_error("Invalid 'runs' item: each entry must be a string.");
            std::string run = n.as<std::string>();
            runs.push_back(run);
        }
    } else throw std::runtime_error("Invalid format for 'runs' key. Expected a string or a list of strings.");
    return validateRuns(runs);
}
References runs(), and validateRuns().
runs()
const std::vector< std::string > & coloradar::DatasetExportConfig::runs () const
Definition at line 132 of file dataset_configs.cpp.
{
    return runs_;
}
References runs_.
validateConfigYaml()
void coloradar::DatasetExportConfig::validateConfigYaml (const YAML::Node & config) protected
Definition at line 10 of file dataset_configs.cpp.
{
    for (auto nodeName : {"global", "devices"}) {
        if (!config[nodeName]) {
            throw std::runtime_error("Missing node: " + std::string(nodeName));
        }
    }
}
validateDestination()
std::filesystem::path coloradar::DatasetExportConfig::validateDestination (const std::filesystem::path & destination) protected
Definition at line 47 of file dataset_configs.cpp.
{
    std::filesystem::path absoluteDestination = std::filesystem::absolute(destination);
    std::filesystem::path directoriesPath = absoluteDestination.parent_path();
    std::string filename = absoluteDestination.filename().string();
    if (!std::filesystem::exists(directoriesPath)) {
        std::filesystem::create_directories(directoriesPath);
    }
    if (filename.empty()) {
        auto now = std::chrono::system_clock::now();
        std::time_t now_c = std::chrono::system_clock::to_time_t(now);
        char buffer[100];
        std::strftime(buffer, sizeof(buffer), "%Y%m%d_%H%M%S", std::localtime(&now_c));
        filename = "dataset_" + std::string(buffer) + ".h5";
    }
    if (std::filesystem::path(filename).extension() != ".h5") {
        filename += ".h5";
    }
    return directoriesPath / filename;
}
validateRuns()
std::vector< std::string > coloradar::DatasetExportConfig::validateRuns (const std::vector< std::string > & runs) protected
Definition at line 67 of file dataset_configs.cpp.
{
    if (runs.size() == 1 && (runs[0].empty() || runs[0] == "all")) return {};
    for (const auto &run : runs) {
        if (run.empty()) throw std::runtime_error("Invalid run name: empty string.");
        if (run == "all") throw std::runtime_error("Invalid run name: 'all' is not allowed if other names are specified.");
        for (unsigned char c : run) {
            if (!(std::isalnum(c) || c == '_' || c == '-')) throw std::runtime_error(
                "Invalid run name \"" + run + "\"\nOnly letter, number, '_' or '-' characters are allowed."
                "\nUse correct YAML list formats:\n```\n  runs:\n    - run1\n    - run2\n```\nor as a flow sequence:\n```\n  runs: [run1, run2]\n```"
            );
        }
    }
    return runs;
}
References runs().
Member Data Documentation
baseCfg_
BaseExportConfig coloradar::DatasetExportConfig::baseCfg_ protected
Definition at line 19 of file dataset_configs.h.
cascadeCfg_
RadarExportConfig coloradar::DatasetExportConfig::cascadeCfg_ protected
Definition at line 16 of file dataset_configs.h.
destinationFilePath_
std::filesystem::path coloradar::DatasetExportConfig::destinationFilePath_ = "dataset.h5" protected
Definition at line 11 of file dataset_configs.h.
devices_
std::span<const std::unique_ptr<BaseDevice> > coloradar::DatasetExportConfig::devices_ protected
Definition at line 14 of file dataset_configs.h.
exportTransforms_
bool coloradar::DatasetExportConfig::exportTransforms_ = true protected
Definition at line 13 of file dataset_configs.h.
imuCfg_
ImuExportConfig coloradar::DatasetExportConfig::imuCfg_ protected
Definition at line 18 of file dataset_configs.h.
lidarCfg_
LidarExportConfig coloradar::DatasetExportConfig::lidarCfg_ protected
Definition at line 17 of file dataset_configs.h.
runs_
std::vector<std::string> coloradar::DatasetExportConfig::runs_ = {} protected
Definition at line 12 of file dataset_configs.h.
{};
singleChipCfg_
RadarExportConfig coloradar::DatasetExportConfig::singleChipCfg_ protected
Definition at line 20 of file dataset_configs.h.
The documentation for this class was generated from the following files:
include/configs/dataset_configs.h
src/configs/dataset_configs.cpp