Coloradar Library: coloradar::H5Dataset Class Reference
coloradar::H5Dataset Class Reference
#include <h5_dataset.h>
Public Member Functions
H5Dataset (const std::filesystem::path &pathToH5File)
H5Dataset (const H5Dataset &)=delete
H5Dataset & operator= (const H5Dataset &)=delete
H5Dataset (H5Dataset &&) noexcept=default
H5Dataset & operator= (H5Dataset &&) noexcept=default
virtual ~H5Dataset ()=default
void summary () const
const std::shared_ptr< RadarConfig > heatmapConfig () const
Public Member Functions inherited from coloradar::Dataset
Dataset ()=default
Dataset (const Dataset &)=delete
Dataset & operator= (const Dataset &)=delete
Dataset (Dataset &&) noexcept=default
Dataset & operator= (Dataset &&) noexcept=default
virtual ~Dataset ()=default
const std::shared_ptr< RadarConfig > cascadeConfig () const
const Eigen::Affine3f & imuTransform () const
const Eigen::Affine3f & lidarTransform () const
const Eigen::Affine3f & cascadeTransform () const
std::vector< std::string > listRuns () const
std::vector< std::shared_ptr< Run > > getRuns () const
std::shared_ptr< Run > getRun (const std::string &runName) const
Protected Member Functions
H5Dataset ()=default
Protected Member Functions inherited from coloradar::Dataset
const std::string getExportArrayName (const std::string contentName, const std::string runName) const
Protected Attributes
std::filesystem::path h5SourceFilePath_
std::shared_ptr< RadarConfig > heatmapConfig_
Protected Attributes inherited from coloradar::Dataset
Eigen::Affine3f imuTransform_
Eigen::Affine3f lidarTransform_
Eigen::Affine3f cascadeTransform_
std::shared_ptr< RadarConfig > cascadeConfig_
std::unique_ptr< BaseDevice > base_device_
std::unique_ptr< ImuDevice > imu_
std::unique_ptr< CascadeDevice > cascade_
std::unique_ptr< LidarDevice > lidar_
std::vector< std::string > runNames_
std::vector< std::shared_ptr< Run > > runs_
Additional Inherited Members
Static Protected Attributes inherited from coloradar::Dataset
static const std::string poseTimestampsContentName = "base_timestamps"
static const std::string imuTimestampsContentName = "imu_timestamps"
static const std::string lidarTimestampsContentName = "lidar_timestamps"
static const std::string cascadeCubeTimestampsContentName = "cascade_cube_timestamps"
static const std::string cascadeTimestampsContentName = "cascade_timestamps"
static const std::string transformBaseToCascadeContentName = "transform_base_to_cascade"
static const std::string transformBaseToLidarContentName = "transform_base_to_lidar"
static const std::string transformBaseToImuContentName = "transform_base_to_imu"
static const std::string posesContentName = "base_poses"
static const std::string imuPosesContentName = "imu_poses"
static const std::string lidarPosesContentName = "lidar_poses"
static const std::string cascadePosesContentName = "cascade_poses"
static const std::string lidarCloudsContentName = "lidar_clouds"
static const std::string lidarMapContentName = "lidar_map"
static const std::string lidarMapSamplesContentName = "lidar_map_samples"
static const std::string cascadeDatacubesContentName = "cascade_datacubes"
static const std::string cascadeHeatmapsContentName = "cascade_heatmaps"
static const std::string cascadeCloudsContentName = "cascade_clouds"
Detailed Description
Definition at line 11 of file h5_dataset.h.
Constructor & Destructor Documentation
H5Dataset() [1/4]
coloradar::H5Dataset::H5Dataset () protected default
H5Dataset() [2/4]
coloradar::H5Dataset::H5Dataset (const std::filesystem::path & pathToH5File) explicit
Definition at line 25 of file h5_dataset.cpp.
{
    // read file
    coloradar::internal::checkPathExists(pathToH5File);
    h5SourceFilePath_ = pathToH5File;
    H5::H5File file(h5SourceFilePath_.string(), H5F_ACC_RDONLY);
    // read config
    H5::DataSet datasetConfig = file.openDataSet("config");
    H5::DataSpace space = datasetConfig.getSpace();
    int ndims = space.getSimpleExtentNdims();
    if (ndims != 1) throw std::runtime_error("HDF5 'config' dataset must be 1-D uint8.");
    hsize_t dims[1] = {0};
    space.getSimpleExtentDims(dims, nullptr);
    std::vector<unsigned char> buf(static_cast<size_t>(dims[0]));
    if (!buf.empty()) {
        datasetConfig.read(buf.data(), H5::PredType::NATIVE_UINT8);
    }
    std::string configStr(reinterpret_cast<const char*>(buf.data()), buf.size());
    Json::CharReaderBuilder b;
    std::unique_ptr<Json::CharReader> reader(b.newCharReader());
    Json::Value root;
    std::string errs;
    const char* begin = configStr.data();
    const char* end   = begin + configStr.size();
    if (!reader->parse(begin, end, &root, &errs)) throw std::runtime_error("Failed to parse JSON from HDF5 'config': " + errs);
    if (!root.isObject()) throw std::runtime_error("Invalid config JSON: expected an object at top level.");
    // extract runs
    std::vector<std::string> configRuns;
    if (!root.isMember("runs") || !root["runs"].isArray()) {
        throw std::runtime_error("Invalid config JSON: 'runs' must be an array.");
    }
    const Json::Value& runsNode = root["runs"];
    configRuns.reserve(runsNode.size());
    for (const auto& v : runsNode) {
        if (!v.isString()) {
            throw std::runtime_error("Invalid config JSON: 'runs' must be an array of strings.");
        }
        configRuns.push_back(v.asString());
    }
    // extract data_content
    std::set<std::string, std::less<>> configDataContent;
    if (!root.isMember("data_content") || !root["data_content"].isArray()) {
        throw std::runtime_error("Invalid config JSON: 'data_content' must be an array.");
    }
    const Json::Value& dcNode = root["data_content"];
    for (const auto& v : dcNode) {
        if (!v.isString()) {
            throw std::runtime_error("Invalid config JSON: 'data_content' must be an array of strings.");
        }
        configDataContent.insert(v.asString());
    }
    // extract cascade radar config
    if (root.isMember("radar_config") && root["radar_config"].isObject()) {
        cascadeConfig_ = std::make_shared<coloradar::CascadeConfig>(root["radar_config"]);
    }
    if (root.isMember("heatmap_radar_config") && root["heatmap_radar_config"].isObject()) {
        heatmapConfig_ = std::make_shared<coloradar::CascadeConfig>(root["heatmap_radar_config"]);
    } else {
        heatmapConfig_ = std::make_shared<CascadeConfig>(*static_cast<CascadeConfig*>(cascadeConfig_.get()));
    }
    // read transforms
    if (root.isMember("transforms") && root["transforms"].isObject()) {
        const Json::Value& transformsJson = root["transforms"];
        if (transformsJson.isMember(transformBaseToCascadeContentName)) {
            cascadeTransform_ = jsonToAffine(transformsJson[transformBaseToCascadeContentName]);
        }
        if (transformsJson.isMember(transformBaseToLidarContentName)) {
            lidarTransform_ = jsonToAffine(transformsJson[transformBaseToLidarContentName]);
        }
        if (transformsJson.isMember(transformBaseToImuContentName)) {
            imuTransform_ = jsonToAffine(transformsJson[transformBaseToImuContentName]);
        }
    } else {
        std::cerr << "Warning: No transforms found in dataset " << h5SourceFilePath_.string() << std::endl;
    }
    // read run data
    for (const auto& run : configRuns) {
        std::vector<double> poseTimestamps = {}, imuTimestamps = {}, lidarTimestamps = {}, cascadeCubeTimestamps = {}, cascadeTimestamps = {};
        std::vector<Eigen::Affine3f> poses = {};
        std::vector<std::shared_ptr<std::vector<int16_t>>> cascadeDatacubes = {};
        std::vector<std::shared_ptr<std::vector<float>>> cascadeHeatmaps = {};
        std::vector<pcl::PointCloud<RadarPoint>::Ptr> cascadePointclouds = {};
        std::vector<pcl::PointCloud<pcl::PointXYZI>::Ptr> lidarPointclouds = {};
        pcl::PointCloud<pcl::PointXYZI>::Ptr lidarOctomap = {};
        std::vector<pcl::PointCloud<pcl::PointXYZI>::Ptr> mapSamples = {};
        if (configDataContent.find(poseTimestampsContentName) != configDataContent.end()) {
            poseTimestamps = coloradar::internal::readH5Timestamps(file, getExportArrayName(poseTimestampsContentName, run));
        }
        if (configDataContent.find(imuTimestampsContentName) != configDataContent.end()) {
            imuTimestamps = coloradar::internal::readH5Timestamps(file, getExportArrayName(imuTimestampsContentName, run));
        }
        if (configDataContent.find(lidarTimestampsContentName) != configDataContent.end()) {
            lidarTimestamps = coloradar::internal::readH5Timestamps(file, getExportArrayName(lidarTimestampsContentName, run));
        }
        if (configDataContent.find(cascadeCubeTimestampsContentName) != configDataContent.end()) {
            cascadeCubeTimestamps = coloradar::internal::readH5Timestamps(file, getExportArrayName(cascadeCubeTimestampsContentName, run));
        }
        if (configDataContent.find(cascadeTimestampsContentName) != configDataContent.end()) {
            cascadeTimestamps = coloradar::internal::readH5Timestamps(file, getExportArrayName(cascadeTimestampsContentName, run));
        }
        if (configDataContent.find(posesContentName) != configDataContent.end()) {
            poses = coloradar::internal::readH5Poses(file, getExportArrayName(posesContentName, run));
        }
        if (configDataContent.find(lidarCloudsContentName) != configDataContent.end()) {
            lidarPointclouds = coloradar::internal::readH5LidarClouds(file, getExportArrayName(lidarCloudsContentName, run));
        }
        if (configDataContent.find(lidarMapContentName) != configDataContent.end()) {
            lidarOctomap = coloradar::internal::readH5SingleCloud(file, getExportArrayName(lidarMapContentName, run));
        }
        if (configDataContent.find(lidarMapSamplesContentName) != configDataContent.end()) {
            mapSamples = coloradar::internal::readH5LidarClouds(file, getExportArrayName(lidarMapSamplesContentName, run));
        }
        if (configDataContent.find(cascadeDatacubesContentName) != configDataContent.end()) {
            cascadeDatacubes = coloradar::internal::readH5Datacubes(file, getExportArrayName(cascadeDatacubesContentName, run));
        }
        if (configDataContent.find(cascadeHeatmapsContentName) != configDataContent.end()) {
            cascadeHeatmaps = coloradar::internal::readH5Heatmaps(file, getExportArrayName(cascadeHeatmapsContentName, run));
            if (configDataContent.find(cascadeCloudsContentName) != configDataContent.end()) {
                auto rawCascadePointclouds = coloradar::internal::readH5LidarClouds(file, getExportArrayName(cascadeCloudsContentName, run));
                for (const auto& cloud : rawCascadePointclouds) {
                    cascadePointclouds.push_back(toRadarCloud(cloud));  // WARNING: ignores doppler values
                }
            }
        }
        auto runObj = std::make_shared<H5Run>(run, cascadeConfig_);
        runObj->setData(
            poseTimestamps, imuTimestamps, lidarTimestamps, cascadeCubeTimestamps, cascadeTimestamps,
            poses,
            lidarPointclouds,
            cascadeDatacubes, cascadeHeatmaps, cascadePointclouds,
            lidarOctomap, mapSamples
        );
        runs_.push_back(runObj);
        runNames_.push_back(run);
    }
}
References coloradar::Dataset::cascadeCloudsContentName, coloradar::Dataset::cascadeConfig_, coloradar::Dataset::cascadeCubeTimestampsContentName, coloradar::Dataset::cascadeDatacubesContentName, coloradar::Dataset::cascadeHeatmapsContentName, coloradar::Dataset::cascadeTimestampsContentName, coloradar::Dataset::cascadeTransform_, coloradar::internal::checkPathExists(), coloradar::Dataset::getExportArrayName(), h5SourceFilePath_, heatmapConfig_, coloradar::Dataset::imuTimestampsContentName, coloradar::Dataset::imuTransform_, jsonToAffine(), coloradar::Dataset::lidarCloudsContentName, coloradar::Dataset::lidarMapContentName, coloradar::Dataset::lidarMapSamplesContentName, coloradar::Dataset::lidarTimestampsContentName, coloradar::Dataset::lidarTransform_, coloradar::Dataset::posesContentName, coloradar::Dataset::poseTimestampsContentName, coloradar::internal::readH5Datacubes(), coloradar::internal::readH5Heatmaps(), coloradar::internal::readH5LidarClouds(), coloradar::internal::readH5Poses(), coloradar::internal::readH5SingleCloud(), coloradar::internal::readH5Timestamps(), coloradar::Dataset::runNames_, coloradar::Dataset::runs_, coloradar::toRadarCloud(), coloradar::Dataset::transformBaseToCascadeContentName, coloradar::Dataset::transformBaseToImuContentName, and coloradar::Dataset::transformBaseToLidarContentName.
H5Dataset() [3/4]
coloradar::H5Dataset::H5Dataset (const H5Dataset &) delete
H5Dataset() [4/4]
coloradar::H5Dataset::H5Dataset (H5Dataset &&) default noexcept
~H5Dataset()
virtual coloradar::H5Dataset::~H5Dataset () virtual default
Member Function Documentation
heatmapConfig()
const std::shared_ptr< RadarConfig > coloradar::H5Dataset::heatmapConfig () const inline
Definition at line 30 of file h5_dataset.h.
{ return heatmapConfig_; }
References heatmapConfig_.
operator=() [1/2]
H5Dataset & coloradar::H5Dataset::operator= (const H5Dataset &) delete
operator=() [2/2]
H5Dataset & coloradar::H5Dataset::operator= (H5Dataset &&) default noexcept
summary()
void coloradar::H5Dataset::summary () const
Definition at line 168 of file h5_dataset.cpp.
{
    std::cout << "\nTotal runs: " << runs_.size() << std::endl;
    for (const auto& run : runs_) {
        std::cout << "Run " << run->name() << ": poses=" << run->poseTimestamps().size()
                 // << " (" << run->getPoses<Eigen::Affine3f>().size() << " poses)"
                 << ", imu=" << run->imuTimestamps().size()
                 << ", lidar=" << run->lidarTimestamps().size()
                 // << " (" << run->getLidarPointCloud(0)->size() << " clouds)"
                 << ", cascade_cubes=" << run->cascadeCubeTimestamps().size()
                 // << " (" << run->getCascadeDatacube(0)->size() << " cubes)"
                 // << ", cascade_heatmaps=" << run->cascadeHeatmaps().size()
                 // << " (" << run->getCascadeHeatmap(0)->size() << " heatmaps)"
                 // << ", cascade_clouds=" << run->cascadePointclouds().size()
                 // << " (" << run->getCascadePointcloud(0)->size() << " clouds)"
                 << ", cascade=" << run->cascadeTimestamps().size() << std::endl;
    }
}
References coloradar::Dataset::runs_.
Member Data Documentation
h5SourceFilePath_
std::filesystem::path coloradar::H5Dataset::h5SourceFilePath_ protected
Definition at line 14 of file h5_dataset.h.
heatmapConfig_
std::shared_ptr<RadarConfig> coloradar::H5Dataset::heatmapConfig_ protected
Definition at line 15 of file h5_dataset.h.
The documentation for this class was generated from the following files:
include/dataset/h5_dataset.h
src/dataset/h5_dataset.cpp