Coloradar Library: coloradar::DatasetVisualizer Class Reference
coloradar::DatasetVisualizer Class Reference
#include <visualizer.h>
Public Member Functions
DatasetVisualizer (const std::shared_ptr< CascadeConfig > cascadeRadarConfig, const Eigen::Affine3f baseToLidarTransform, const Eigen::Affine3f baseToCascadeTransform, const int frameIncrement=1, const double cascadeRadarIntensityThreshold=0.0, const std::string cameraConfigPath="camera_config.txt")
virtual ~DatasetVisualizer ()=default
void visualize (const std::shared_ptr< Run > run, const bool usePrebuiltMap=false)
Protected Member Functions
void reset ()
void step (const int increment=1)
void keyboardCallback (const pcl::visualization::KeyboardEvent &event)
pcl::PointCloud< RadarPoint >::Ptr readCascadeCloud (const int scanIdx)
pcl::PointCloud< pcl::PointXYZI >::Ptr readLidarCloud (const int scanIdx)
pcl::PointCloud< pcl::PointXYZI >::Ptr downsampleLidarCloud (const pcl::PointCloud< pcl::PointXYZI >::Ptr &inputCloud, const float leafSize=0.3) const
pcl::PointCloud< RadarPoint >::Ptr normalizeRadarCloudIntensity (const pcl::PointCloud< RadarPoint >::Ptr &inputCloud) const
pcl::PointCloud< RadarPoint >::Ptr extractTopNIntensity (const pcl::PointCloud< RadarPoint >::Ptr &inputCloud, size_t N) const
void updateLidarMap (const int lastStep)
void renderLidarMap ()
void renderRadarCloud (const pcl::PointCloud< RadarPoint >::Ptr &cloud)
std::vector< Control > getControls ()
void renderLegend ()
void showMessage (const std::string &message)
Protected Attributes
std::shared_ptr< CascadeConfig > cascadeRadarConfig
std::shared_ptr< CascadeConfig > clippedCascadeRadarConfig
const Eigen::Affine3f baseToLidarTransform
const Eigen::Affine3f baseToCascadeTransform
int frameIncrement
double cascadeRadarIntensityThreshold
std::string cameraConfigPath
const std::string lidarMapCloudName = "lidar_map_cloud"
const std::string cascadeRadarCloudName = "current_cascade_cloud"
pcl::visualization::PCLVisualizer::Ptr viewer
vtkSmartPointer< vtkImageData > vtkImage
vtkSmartPointer< vtkImageActor > imageActor
std::shared_ptr< Run > run
std::vector< Eigen::Affine3f > basePoses
std::vector< Eigen::Affine3f > basePosesLidarTs
std::vector< Eigen::Affine3f > basePosesCascadeTs
std::vector< int > cascadeToLidarFrameIndices
std::vector< int > baseToLidarFrameIndices
std::vector< int > baseToCascadeFrameIndices
bool mapIsPrebuilt
pcl::PointCloud< pcl::PointXYZI >::Ptr lidarMapCloud
int numSteps
int currentStep
int currentMapStep
std::string currentMessage
std::chrono::steady_clock::time_point messageTime
Detailed Description
Definition at line 18 of file visualizer.h.
Constructor & Destructor Documentation
DatasetVisualizer()
coloradar::DatasetVisualizer::DatasetVisualizer (const std::shared_ptr< CascadeConfig > cascadeRadarConfig, const Eigen::Affine3f baseToLidarTransform, const Eigen::Affine3f baseToCascadeTransform, const int frameIncrement = 1, const double cascadeRadarIntensityThreshold = 0.0, const std::string cameraConfigPath = "camera_config.txt")
Definition at line 11 of file visualizer.cpp.
 :
    cascadeRadarConfig(std::make_shared<CascadeConfig>(*cascadeRadarConfig)),
    clippedCascadeRadarConfig(std::make_shared<CascadeConfig>(*cascadeRadarConfig)),
    baseToLidarTransform(baseToLidarTransform),
    baseToCascadeTransform(baseToCascadeTransform),
    frameIncrement(frameIncrement),
    cascadeRadarIntensityThreshold(cascadeRadarIntensityThreshold),
    cameraConfigPath(cameraConfigPath),
    viewer(new pcl::visualization::PCLVisualizer("3D Viewer")),
    vtkImage(vtkSmartPointer<vtkImageData>::New()),
    imageActor(vtkSmartPointer<vtkImageActor>::New())
{
    reset();
    // init radar config
    auto sampleHeatmap = std::make_shared<std::vector<float>>(cascadeRadarConfig->heatmapSize(), 0.0f);
    auto result = cascadeRadarConfig->clipHeatmap(sampleHeatmap, cascadeRadarConfig->numAzimuthBins(), 0, static_cast<int>(cascadeRadarConfig->nRangeBins() * 0.75));
    clippedCascadeRadarConfig = std::dynamic_pointer_cast<CascadeConfig>(result.newConfig);
    clippedCascadeRadarConfig->precomputePointcloudTemplate(); // update cloud template
}
References cascadeRadarConfig, clippedCascadeRadarConfig, and reset().
~DatasetVisualizer()
virtual coloradar::DatasetVisualizer::~DatasetVisualizer () virtual default
Member Function Documentation
downsampleLidarCloud()
pcl::PointCloud< pcl::PointXYZI >::Ptr coloradar::DatasetVisualizer::downsampleLidarCloud (const pcl::PointCloud< pcl::PointXYZI >::Ptr & inputCloud, const float leafSize = 0.3) const protected
Definition at line 226 of file visualizer.cpp.
{
    auto downsampledCloud = std::make_shared<pcl::PointCloud<pcl::PointXYZI>>();
    pcl::VoxelGrid<pcl::PointXYZI> voxelGrid;
    voxelGrid.setInputCloud(inputCloud);
    voxelGrid.setLeafSize(leafSize, leafSize, leafSize);
    voxelGrid.filter(*downsampledCloud);
    return downsampledCloud;
}
extractTopNIntensity()
pcl::PointCloud< RadarPoint >::Ptr coloradar::DatasetVisualizer::extractTopNIntensity (const pcl::PointCloud< RadarPoint >::Ptr & inputCloud, size_t N) const protected
Definition at line 258 of file visualizer.cpp.
{
    auto sorted = *inputCloud;
    std::nth_element(sorted.begin(), sorted.begin() + N, sorted.end(),
        [](const RadarPoint& a, const RadarPoint& b) { return a.intensity > b.intensity; });
    sorted.resize(std::min(N, sorted.size()));
    auto output = std::make_shared<pcl::PointCloud<RadarPoint>>();
    output->insert(output->end(), sorted.begin(), sorted.end());
    return output;
}
getControls()
std::vector< Control > coloradar::DatasetVisualizer::getControls () protected
Definition at line 116 of file visualizer.cpp.
{
    return {
        {"Up", "<Up Arrow>", "next frame", [this]() {
            step(frameIncrement);
        }},
        {"Down", "<Down Arrow>", "previous frame", [this]() {
            step(-frameIncrement);
        }},
        {"s", "s", "save camera parameters", [this]() {
            viewer->saveCameraParameters(cameraConfigPath);
            showMessage("Camera parameters saved to " + std::filesystem::absolute(cameraConfigPath).string());
        }},
        {"l", "l", "load camera parameters", [this]() {
            viewer->loadCameraParameters(cameraConfigPath);
            showMessage("Camera parameters loaded from " + std::filesystem::absolute(cameraConfigPath).string());
        }}
    };
}
References cameraConfigPath, frameIncrement, showMessage(), step(), and viewer.
keyboardCallback()
void coloradar::DatasetVisualizer::keyboardCallback (const pcl::visualization::KeyboardEvent & event) protected
Definition at line 104 of file visualizer.cpp.
{
    if (!event.keyDown()) return;
    std::string keySym = event.getKeySym();
    for (const auto& control : getControls()) {
        if (keySym == control.button) {
            control.action();
            break;
        }
    }
}
References getControls().
normalizeRadarCloudIntensity()
pcl::PointCloud< RadarPoint >::Ptr coloradar::DatasetVisualizer::normalizeRadarCloudIntensity (const pcl::PointCloud< RadarPoint >::Ptr & inputCloud) const protected
Definition at line 236 of file visualizer.cpp.
{
    auto normalizedCloud = std::make_shared<pcl::PointCloud<RadarPoint>>();
    normalizedCloud->reserve(inputCloud->size());
    float minIntensity = std::numeric_limits<float>::max();
    float maxIntensity = std::numeric_limits<float>::lowest();
    for (const auto& point : *inputCloud) {
        if (point.intensity < minIntensity) minIntensity = point.intensity;
        if (point.intensity > maxIntensity) maxIntensity = point.intensity;
    }
    float range = maxIntensity - minIntensity;
    if (range == 0) range = 1.0f;
    for (const auto& point : *inputCloud) {
        RadarPoint normalizedPoint = point;
        normalizedPoint.intensity = (point.intensity - minIntensity) / range;
        normalizedCloud->push_back(normalizedPoint);
    }
    return normalizedCloud;
}
References coloradar::RadarPoint::intensity.
readCascadeCloud()
pcl::PointCloud< RadarPoint >::Ptr coloradar::DatasetVisualizer::readCascadeCloud (const int scanIdx) protected
Definition at line 198 of file visualizer.cpp.
{
    auto cascadeHeatmap = run->getCascadeHeatmap(scanIdx);
    int targetNumRangeBins = static_cast<int>(cascadeRadarConfig->nRangeBins() * 0.75);
    if (cascadeRadarConfig->numElevationBins() > 0 || cascadeRadarConfig->nRangeBins() > targetNumRangeBins) {
        auto result = cascadeRadarConfig->clipHeatmap(cascadeHeatmap, cascadeRadarConfig->numAzimuthBins(), 0, targetNumRangeBins);
        cascadeHeatmap = result.heatmap;
    }
    auto cascadeCloud = clippedCascadeRadarConfig->heatmapToPointcloud(cascadeHeatmap, cascadeRadarIntensityThreshold); // use clipped config to convert heatmap to pointcloud
    cascadeCloud = normalizeRadarCloudIntensity(cascadeCloud);
    auto map_T_base = basePosesCascadeTs[scanIdx];  // read map_T_base as "base to map"
    auto base_T_cascade = baseToCascadeTransform; // read base_T_cascade as "cascade to base"
    auto map_T_cascade = map_T_base * base_T_cascade; // read map_T_cascade as "cascade to map"
    pcl::transformPointCloud(*cascadeCloud, *cascadeCloud, map_T_cascade); // map frame
    return cascadeCloud;
}
References basePosesCascadeTs, baseToCascadeTransform, cascadeRadarConfig, cascadeRadarIntensityThreshold, clippedCascadeRadarConfig, normalizeRadarCloudIntensity(), and run.
readLidarCloud()
pcl::PointCloud< pcl::PointXYZI >::Ptr coloradar::DatasetVisualizer::readLidarCloud (const int scanIdx) protected
Definition at line 216 of file visualizer.cpp.
{
    auto lidarCloud = run->getLidarPointCloud(scanIdx);
    auto map_T_base = basePosesLidarTs[scanIdx];
    auto base_T_lidar = baseToLidarTransform;
    auto map_T_lidar = map_T_base * base_T_lidar;
    pcl::transformPointCloud(*lidarCloud, *lidarCloud, map_T_lidar);     // map frame
    return lidarCloud;
}
References basePosesLidarTs, baseToLidarTransform, and run.
renderLegend()
void coloradar::DatasetVisualizer::renderLegend () protected
Definition at line 136 of file visualizer.cpp.
{
    std::stringstream legend;
    legend << "Step: " << (currentStep + 1) << " / " << numSteps << "\n";
    legend << "Keyboard Controls:\n";
    for (const auto& control : getControls()) {
        legend << "- [" << control.name << "]: " << control.description << "\n";
    }
    viewer->removeText3D("keyboard_legend");
    viewer->addText(legend.str(), 30, 30, 35, 1.0, 1.0, 1.0, "keyboard_legend");
    if (!currentMessage.empty()) {
        auto now = std::chrono::steady_clock::now();
        auto elapsed = std::chrono::duration_cast<std::chrono::seconds>(now - messageTime).count();
        if (elapsed < 3) {
            viewer->removeText3D("message_text");
            viewer->addText(currentMessage, 30, 10, 25, 1.0, 1.0, 1.0, "message_text");
        } else {
            currentMessage.clear();
            viewer->removeText3D("message_text");
        }
    }
}
References currentMessage, currentStep, getControls(), messageTime, numSteps, and viewer.
renderLidarMap()
void coloradar::DatasetVisualizer::renderLidarMap () protected
Definition at line 270 of file visualizer.cpp.
{
    viewer->removePointCloud(lidarMapCloudName);
    pcl::visualization::PointCloudColorHandlerCustom<pcl::PointXYZI> mapColorHandler(
        lidarMapCloud,
        mapIsPrebuilt ? 255 : 180,
        mapIsPrebuilt ? 255 : 180,
        mapIsPrebuilt ? 255 : 180
    );
    viewer->addPointCloud<pcl::PointXYZI>(lidarMapCloud, mapColorHandler, lidarMapCloudName);
    viewer->setPointCloudRenderingProperties(pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 0.1, lidarMapCloudName);
}
References lidarMapCloud, lidarMapCloudName, mapIsPrebuilt, and viewer.
renderRadarCloud()
void coloradar::DatasetVisualizer::renderRadarCloud (const pcl::PointCloud< RadarPoint >::Ptr & cloud) protected
Definition at line 283 of file visualizer.cpp.
{
    viewer->removePointCloud(cascadeRadarCloudName);
    pcl::visualization::PointCloudColorHandlerGenericField<RadarPoint> radarColorHandler(cloud, "intensity");
    viewer->addPointCloud<RadarPoint>(cloud, radarColorHandler, cascadeRadarCloudName);
    viewer->setPointCloudRenderingProperties(pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 3, cascadeRadarCloudName);
}
References cascadeRadarCloudName, and viewer.
reset()
void coloradar::DatasetVisualizer::reset () protected
Definition at line 40 of file visualizer.cpp.
{
    run = nullptr;
    mapIsPrebuilt = false;
    lidarMapCloud.reset(new pcl::PointCloud<pcl::PointXYZI>());
    basePosesLidarTs.clear();
    basePosesCascadeTs.clear();
    numSteps = 0;
    currentStep = -1;
    currentMapStep = -1;
    currentMessage.clear();
    messageTime = std::chrono::steady_clock::now();
    viewer->removeAllPointClouds();
    viewer->removeAllCoordinateSystems();
    viewer->removeAllShapes();
    viewer->resetCamera();
    viewer->initCameraParameters();
    vtkImage->Initialize();
    imageActor->GetMapper()->SetInputData(vtkImage);
}
References basePosesCascadeTs, basePosesLidarTs, currentMapStep, currentMessage, currentStep, imageActor, lidarMapCloud, mapIsPrebuilt, messageTime, numSteps, run, viewer, and vtkImage.
showMessage()
void coloradar::DatasetVisualizer::showMessage (const std::string & message) protected
Definition at line 159 of file visualizer.cpp.
{
    currentMessage = message;
    messageTime = std::chrono::steady_clock::now();
    renderLegend();
}
References currentMessage, messageTime, and renderLegend().
step()
void coloradar::DatasetVisualizer::step (const int increment = 1) protected
Definition at line 166 of file visualizer.cpp.
{
    if (increment == 0) throw std::runtime_error("Step increment must be non-zero.");
    int prevStep = currentStep;
    int targetStep = std::clamp(currentStep + increment, 0, numSteps - 1);
    if (targetStep == currentStep) return;
    currentStep = targetStep;
    if (!mapIsPrebuilt) {
        // update lidar map if accumulating
        updateLidarMap(currentStep);
        renderLidarMap();
    }
    auto cascadeCloud = readCascadeCloud(currentStep);
    renderRadarCloud(cascadeCloud);
    renderLegend();
}
References currentStep, mapIsPrebuilt, numSteps, readCascadeCloud(), renderLegend(), renderLidarMap(), renderRadarCloud(), and updateLidarMap().
updateLidarMap()
void coloradar::DatasetVisualizer::updateLidarMap (const int lastStep) protected
Definition at line 185 of file visualizer.cpp.
{
    if (step >= numSteps) throw std::runtime_error("Step " + std::to_string(step) + " is out of range [0, " + std::to_string(numSteps) + ").");
    if (currentMapStep >= step) return;
    for (int i = currentMapStep + 1; i <= step; i++) {
        int lidarFrameIdx = cascadeToLidarFrameIndices[i];
        auto lidarCloud = readLidarCloud(lidarFrameIdx);
        lidarCloud = downsampleLidarCloud(lidarCloud);
        *lidarMapCloud += *lidarCloud;
    }
    currentMapStep = step;
}
References cascadeToLidarFrameIndices, currentMapStep, downsampleLidarCloud(), lidarMapCloud, numSteps, readLidarCloud(), and step().
visualize()
void coloradar::DatasetVisualizer::visualize (const std::shared_ptr< Run > run, const bool usePrebuiltMap = false)
Definition at line 62 of file visualizer.cpp.
{
    reset();
    this->run = run;
    // init poses and use cascade timestamps as reference
    auto basePoses = run->getPoses<Eigen::Affine3f>();
    if (basePoses.empty()) throw std::runtime_error("Base poses are empty.");
    basePosesLidarTs = interpolatePoses(basePoses, run->poseTimestamps(), run->lidarTimestamps());
    basePosesCascadeTs = interpolatePoses(basePoses, run->poseTimestamps(), run->cascadeTimestamps());
    cascadeToLidarFrameIndices.resize(basePosesCascadeTs.size());
    for (size_t cascadeIdx = 0; cascadeIdx < basePosesCascadeTs.size(); cascadeIdx++) {
        auto cascadeTimestamp = run->cascadeTimestamps()[cascadeIdx];
        auto lidarIdx = findClosestTimestampIndex(cascadeTimestamp, run->lidarTimestamps());
        cascadeToLidarFrameIndices[cascadeIdx] = lidarIdx;
    }
    numSteps = basePosesCascadeTs.size();
    mapIsPrebuilt = usePrebuiltMap;
    if (usePrebuiltMap) {
        lidarMapCloud = run->getLidarOctomap();
        if (lidarMapCloud->empty()) throw std::runtime_error("Prebuilt map cloud is empty.");
        filterOccupancy(lidarMapCloud, 0, true);
        renderLidarMap();
    }
    // display frame 0
    step(1);
    // start viewer
    viewer->setBackgroundColor(0, 0, 0);
    viewer->addCoordinateSystem(2.0);
    if (std::filesystem::exists(cameraConfigPath)) {
        viewer->loadCameraParameters(cameraConfigPath);
        showMessage("Camera parameters loaded from " + std::filesystem::absolute(cameraConfigPath).string());
    }
    viewer->registerKeyboardCallback(std::bind(&DatasetVisualizer::keyboardCallback, this, std::placeholders::_1));
    renderLegend();
    while (!viewer->wasStopped()) {
        viewer->spin();
    }
}
References basePoses, basePosesCascadeTs, basePosesLidarTs, cameraConfigPath, cascadeToLidarFrameIndices, coloradar::filterOccupancy(), coloradar::findClosestTimestampIndex(), coloradar::interpolatePoses(), keyboardCallback(), lidarMapCloud, mapIsPrebuilt, numSteps, renderLegend(), renderLidarMap(), reset(), run, showMessage(), step(), and viewer.
Member Data Documentation
basePoses
std::vector<Eigen::Affine3f> coloradar::DatasetVisualizer::basePoses protected
Definition at line 41 of file visualizer.h.
basePosesCascadeTs
std::vector<Eigen::Affine3f> coloradar::DatasetVisualizer::basePosesCascadeTs protected
Definition at line 43 of file visualizer.h.
basePosesLidarTs
std::vector<Eigen::Affine3f> coloradar::DatasetVisualizer::basePosesLidarTs protected
Definition at line 42 of file visualizer.h.
baseToCascadeFrameIndices
std::vector<int> coloradar::DatasetVisualizer::baseToCascadeFrameIndices protected
Definition at line 46 of file visualizer.h.
baseToCascadeTransform
const Eigen::Affine3f coloradar::DatasetVisualizer::baseToCascadeTransform protected
Definition at line 25 of file visualizer.h.
baseToLidarFrameIndices
std::vector<int> coloradar::DatasetVisualizer::baseToLidarFrameIndices protected
Definition at line 45 of file visualizer.h.
baseToLidarTransform
const Eigen::Affine3f coloradar::DatasetVisualizer::baseToLidarTransform protected
Definition at line 24 of file visualizer.h.
cameraConfigPath
std::string coloradar::DatasetVisualizer::cameraConfigPath protected
Definition at line 28 of file visualizer.h.
cascadeRadarCloudName
const std::string coloradar::DatasetVisualizer::cascadeRadarCloudName = "current_cascade_cloud" protected
Definition at line 32 of file visualizer.h.
cascadeRadarConfig
std::shared_ptr<CascadeConfig> coloradar::DatasetVisualizer::cascadeRadarConfig protected
Definition at line 22 of file visualizer.h.
cascadeRadarIntensityThreshold
double coloradar::DatasetVisualizer::cascadeRadarIntensityThreshold protected
Definition at line 27 of file visualizer.h.
cascadeToLidarFrameIndices
std::vector<int> coloradar::DatasetVisualizer::cascadeToLidarFrameIndices protected
Definition at line 44 of file visualizer.h.
clippedCascadeRadarConfig
std::shared_ptr<CascadeConfig> coloradar::DatasetVisualizer::clippedCascadeRadarConfig protected
Definition at line 23 of file visualizer.h.
currentMapStep
int coloradar::DatasetVisualizer::currentMapStep protected
Definition at line 51 of file visualizer.h.
currentMessage
std::string coloradar::DatasetVisualizer::currentMessage protected
Definition at line 52 of file visualizer.h.
currentStep
int coloradar::DatasetVisualizer::currentStep protected
Definition at line 50 of file visualizer.h.
frameIncrement
int coloradar::DatasetVisualizer::frameIncrement protected
Definition at line 26 of file visualizer.h.
imageActor
vtkSmartPointer<vtkImageActor> coloradar::DatasetVisualizer::imageActor protected
Definition at line 37 of file visualizer.h.
lidarMapCloud
pcl::PointCloud<pcl::PointXYZI>::Ptr coloradar::DatasetVisualizer::lidarMapCloud protected
Definition at line 48 of file visualizer.h.
lidarMapCloudName
const std::string coloradar::DatasetVisualizer::lidarMapCloudName = "lidar_map_cloud" protected
Definition at line 31 of file visualizer.h.
mapIsPrebuilt
bool coloradar::DatasetVisualizer::mapIsPrebuilt protected
Definition at line 47 of file visualizer.h.
messageTime
std::chrono::steady_clock::time_point coloradar::DatasetVisualizer::messageTime protected
Definition at line 53 of file visualizer.h.
numSteps
int coloradar::DatasetVisualizer::numSteps protected
Definition at line 49 of file visualizer.h.
run
std::shared_ptr<Run> coloradar::DatasetVisualizer::run protected
Definition at line 40 of file visualizer.h.
viewer
pcl::visualization::PCLVisualizer::Ptr coloradar::DatasetVisualizer::viewer protected
Definition at line 35 of file visualizer.h.
vtkImage
vtkSmartPointer<vtkImageData> coloradar::DatasetVisualizer::vtkImage protected
Definition at line 36 of file visualizer.h.
The documentation for this class was generated from the following files:
include/utils/visualizer.h
src/utils/visualizer.cpp