Coloradar Library: coloradar Namespace Reference
coloradar Namespace Reference
Namespaces
namespace internal
Classes
class BaseDevice
class BaseExportConfig
class CascadeConfig
class CascadeDevice
class ColoradarDataset
class ColoradarPlusDataset
class ColoradarPlusRun
class ColoradarRun
struct Control
class Dataset
class DatasetExportConfig
class DatasetVisualizer
struct FovConfig
class H5Dataset
class H5Run
struct HeatmapTransformResult
class ImuDevice
class ImuExportConfig
class LidarDevice
class LidarExportConfig
class OctoPointcloud
struct PointKey
struct PointKeyHash
struct PoseTraits
struct PoseTraits< Eigen::Affine3f >
struct PoseTraits< octomath::Pose6D >
class RadarConfig
class RadarDevice
class RadarExportConfig
struct RadarPoint
class RadarProcessor
class Run
class SingleChipConfig
class SingleChipDevice
Concepts
concept Pcl3dPointType
concept Pcl4dPointType
concept PclPointType
concept OctomapPointType
concept PointType
concept PclCloudType
concept OctomapCloudType
concept CloudType
concept PclPoseType
concept OctoPoseType
concept PoseType
Functions
bool validateDeviceName (const std::string &deviceName)
template<typename T >
void copyToGpu (const std::vector< T > &source, T *&dest)
template<Pcl4dPointType PointT, template< PclCloudType > class CloudT>
void octreeToPcl (const octomap::OcTree &tree, std::shared_ptr< CloudT< PointT > > &cloud)
template<PclPointType PointT, template< PclCloudType > class CloudT>
void filterFov (std::shared_ptr< CloudT< PointT > > &cloud, const float &horizontalFov, const float &verticalFov, const float &range)
template<Pcl4dPointType PointT, template< typename > class CloudT>
void collapseElevation (std::shared_ptr< CloudT< PointT > > &cloud, const float &elevationMinMeters, const float &elevationMaxMeters)
template<PclPointType PointT, template< typename > class CloudT>
void collapseElevation (std::shared_ptr< CloudT< PointT > > &cloud)
template<Pcl4dPointType PointT, template< typename > class CloudT>
void filterOccupancy (std::shared_ptr< CloudT< PointT > > &cloud, const float &probabilityThreshold, const bool &saveProbabilities)
template<PoseType PoseT>
std::vector< PoseT > interpolatePoses (const std::vector< PoseT > &poses, const std::vector< double > &poseTimestamps, const std::vector< double > &targetTimestamps)
template<typename PointT , template< typename > class CloudT>
pcl::PointCloud< RadarPoint >::Ptr toRadarCloud (const std::shared_ptr< CloudT< PointT > > cloud)
int frameIdxToFileIdx (const int frameIdx, const std::filesystem::path &framesDirPath)
const int findClosestTimestampIndex (const double targetTimestamp, const std::vector< double > &timestamps, const std::string &preference="none")
Json::Value affineToJson (const Eigen::Affine3f &transform)
Function Documentation
affineToJson()
Json::Value coloradar::affineToJson (const Eigen::Affine3f & transform)
Definition at line 70 of file coloradar_plus_dataset.cpp.
{
    Json::Value transformJson(Json::objectValue);
    Eigen::Vector3f trans = transform.translation();
    Json::Value transJson(Json::arrayValue);
    transJson.append(trans.x());
    transJson.append(trans.y());
    transJson.append(trans.z());
    transformJson["translation"] = transJson;
    Eigen::Quaternionf rot(transform.linear());
    Json::Value rotJson(Json::arrayValue);
    rotJson.append(rot.x());
    rotJson.append(rot.y());
    rotJson.append(rot.z());
    rotJson.append(rot.w());
    transformJson["rotation"] = rotJson;
    return transformJson;
}
collapseElevation() [1/2]
template<PclPointType PointT, template< typename > class CloudT> void coloradar::collapseElevation (std::shared_ptr< CloudT< PointT > > & cloud)
Definition at line 78 of file basic_utils.hpp.
{
    const int precision = 4;
    std::unordered_map<PointKey, PointT, PointKeyHash> uniquePointsMap;
    uniquePointsMap.reserve(cloud->size());
    for (const auto& point : *cloud) {
        PointKey key(point.x, point.y, precision);
        if (uniquePointsMap.find(key) == uniquePointsMap.end()) {
            uniquePointsMap[key] = point;
        }
    }
    cloud->clear();
    cloud->reserve(uniquePointsMap.size());
    for (const auto& [key, point] : uniquePointsMap) {
        PointT collapsedPoint = point;
        collapsedPoint.z = 0.0f;
        cloud->push_back(collapsedPoint);
    }
}
collapseElevation() [2/2]
template<Pcl4dPointType PointT, template< typename > class CloudT> void coloradar::collapseElevation (std::shared_ptr< CloudT< PointT > > & cloud, const float & elevationMinMeters, const float & elevationMaxMeters)
Definition at line 52 of file basic_utils.hpp.
{
    const int precision = 4;
    if (elevationMinMeters > elevationMaxMeters)
        throw std::invalid_argument("Invalid elevation range: elevationMin must be less or equal to elevationMax.");
    std::unordered_map<PointKey, PointT, PointKeyHash> maxIntensityMap;
    maxIntensityMap.reserve(cloud->size());
    for (const auto& point : *cloud) {
        if (point.z >= elevationMinMeters && point.z <= elevationMaxMeters) {
            PointKey key(point.x, point.y, precision);
            auto iter = maxIntensityMap.find(key);
            if (iter == maxIntensityMap.end() || point.intensity > iter->second.intensity) {
                maxIntensityMap[key] = point;
            }
        }
    }
    cloud->clear();
    cloud->reserve(maxIntensityMap.size());
    for (const auto& [key, point] : maxIntensityMap) {
        PointT collapsedPoint = point;
        collapsedPoint.z = 0.0f;
        cloud->push_back(collapsedPoint);
    }
}
copyToGpu()
template<typename T > void coloradar::copyToGpu (const std::vector< T > & source, T *& dest)
Definition at line 58 of file coloradar_cuda.h.
{
        cudaError_t err = cudaMemcpy(dest, source.data(), sizeof(T) * source.size(), cudaMemcpyHostToDevice);
        if (err != cudaSuccess) {
            std::cerr << "CUDA memcpy error:  " << cudaGetErrorString(err) << std::endl;
        }
        cudaDeviceSynchronize();
    }
filterFov()
template<PclPointType PointT, template< PclCloudType > class CloudT> void coloradar::filterFov (std::shared_ptr< CloudT< PointT > > & cloud, const float & horizontalFov, const float & verticalFov, const float & range)
Definition at line 24 of file basic_utils.hpp.
{
    coloradar::internal::filterFov<PointT, CloudT<PointT>>(cloud, horizontalFov, verticalFov, range);
}
References coloradar::internal::makePose().
filterOccupancy()
template<Pcl4dPointType PointT, template< typename > class CloudT> void coloradar::filterOccupancy (std::shared_ptr< CloudT< PointT > > & cloud, const float & probabilityThreshold, const bool & saveProbabilities)
Definition at line 99 of file basic_utils.hpp.
{
    if (probabilityThreshold < 0.0f || probabilityThreshold > 1.0f) {
        throw std::out_of_range("Invalid probability threshold: expected value from 0 to 1, got " + std::to_string(probabilityThreshold));
    }
    if (probabilityThreshold == 0.0f && !saveProbabilities) return;
    CloudT<PointT> filteredCloud;
    filteredCloud.reserve(cloud->size());
    for (const auto& point : *cloud) {
        float probability = 1.0f / (1.0f + std::exp(-point.intensity));
        if (probability >= probabilityThreshold) {
            PointT newPoint = point;
            if (saveProbabilities) newPoint.intensity = probability;
            filteredCloud.push_back(newPoint);
        }
    }
    cloud->swap(filteredCloud);
}
findClosestTimestampIndex()
const int coloradar::findClosestTimestampIndex (const double targetTimestamp, const std::vector< double > & timestamps, const std::string & preference = "none")
Definition at line 30 of file basic_utils.cpp.
{
    if (timestamps.empty()) throw std::runtime_error("Timestamps vector is empty.");
    if (preference != "none" && preference != "before" && preference != "after") throw std::invalid_argument("Invalid preference: must be 'none', 'before', or 'after'.");
    auto it = std::lower_bound(timestamps.begin(), timestamps.end(), targetTimestamp);
    size_t afterIdx = static_cast<size_t>(it - timestamps.begin());
    if (afterIdx < timestamps.size() && timestamps[afterIdx] == targetTimestamp) {
        return static_cast<int>(afterIdx);
    }
    bool hasAfter = afterIdx < timestamps.size();
    bool hasBefore = afterIdx > 0;
    size_t beforeIdx = hasBefore ? afterIdx - 1 : 0;
    if (preference == "none") {
        double beforeDiff = hasBefore ? std::abs(timestamps[beforeIdx] - targetTimestamp)
                                      : std::numeric_limits<double>::max();
        double afterDiff  = hasAfter  ? std::abs(timestamps[afterIdx]  - targetTimestamp)
                                      : std::numeric_limits<double>::max();
        return (beforeDiff <= afterDiff) ? static_cast<int>(beforeIdx) : static_cast<int>(afterIdx);
    }
    if (preference == "before") {
        if (hasBefore) return static_cast<int>(beforeIdx);
        if (hasAfter)  return static_cast<int>(afterIdx);
    }
    if (preference == "after") {
        if (hasAfter)  return static_cast<int>(afterIdx);
        if (hasBefore) return static_cast<int>(beforeIdx);
    }
    throw std::runtime_error("No valid timestamp found.");
}
frameIdxToFileIdx()
int coloradar::frameIdxToFileIdx (const int frameIdx, const std::filesystem::path & framesDirPath)
Definition at line 11 of file basic_utils.cpp.
{
    std::optional<int> minFileIdx;
    for (const auto& entry : std::filesystem::directory_iterator(framesDirPath)) {
        const std::string entryName = entry.path().filename().string();
        auto fileIdx = coloradar::internal::extractFirstInt(entryName);
        if (!fileIdx) throw std::runtime_error("unexpected file name " + entryName + " in folder " + framesDirPath.string());
        if (!minFileIdx || *fileIdx < *minFileIdx) minFileIdx = *fileIdx;
    }
    if (!minFileIdx) throw std::runtime_error("no files with integers found in " + framesDirPath.string());
    std::string dirPathStr = framesDirPath.string();
    if (*minFileIdx != 0 && warnedDirectories.find(dirPathStr) == warnedDirectories.end()) {
        std::cout << "\nWarning! Frames are not indexed from 0 in directory\n'" << dirPathStr << "'\n(first detected frame index: " << *minFileIdx << ")\n" << std::endl;
        warnedDirectories.insert(dirPathStr);
    }
    return *minFileIdx + frameIdx;
}
References coloradar::internal::extractFirstInt().
interpolatePoses()
template<PoseType PoseT> std::vector< PoseT > coloradar::interpolatePoses (const std::vector< PoseT > & poses, const std::vector< double > & poseTimestamps, const std::vector< double > & targetTimestamps)
Definition at line 120 of file basic_utils.hpp.
{
    if (poses.empty()) throw std::runtime_error("Cannot interpolate empty poses.");
    if (poseTimestamps.empty()) throw std::runtime_error("Cannot interpolate over empty pose timestamps.");
    if (targetTimestamps.empty()) throw std::runtime_error("Cannot interpolate over empty target timestamps.");
    if (poses.size() != poseTimestamps.size()) throw std::runtime_error("The length of poses and poses' timestamps vectors must match.");
    std::vector<PoseT> interpolatedPoses;
    size_t tsStartIdx = 0, tsEndIdx = poseTimestamps.size() - 1;
    size_t tsIdx = tsStartIdx;
    for (size_t targetTsIdx = 0; targetTsIdx < targetTimestamps.size(); ++targetTsIdx) {
        if (targetTimestamps[targetTsIdx] < poseTimestamps[tsStartIdx]) {
            interpolatedPoses.push_back(poses[tsStartIdx]);
            continue;
        }
        if (targetTimestamps[targetTsIdx] > poseTimestamps[tsEndIdx]) {
            interpolatedPoses.push_back(poses[tsEndIdx]);
            continue;
        }
        while (tsIdx + 1 <= tsEndIdx && poseTimestamps[tsIdx + 1] < targetTimestamps[targetTsIdx])
            tsIdx++;
        double denominator = poseTimestamps[tsIdx + 1] - poseTimestamps[tsIdx];
        double ratio = denominator > 0.0f ? (targetTimestamps[targetTsIdx] - poseTimestamps[tsIdx]) / denominator : 0.0f;
        Eigen::Vector3f t1 = coloradar::internal::toEigenTrans(poses[tsIdx]);
        Eigen::Vector3f t2 = coloradar::internal::toEigenTrans(poses[tsIdx + 1]);
        Eigen::Vector3f interpolatedTransEig = (1.0f - ratio) * t1 + ratio * t2;
        auto interpolatedTrans = coloradar::internal::fromEigenTrans<typename PoseTraits<PoseT>::TranslationType>(interpolatedTransEig);
        Eigen::Quaternionf q1 = coloradar::internal::toEigenQuat(poses[tsIdx]);
        Eigen::Quaternionf q2 = coloradar::internal::toEigenQuat(poses[tsIdx + 1]);
        Eigen::Quaternionf interpolatedRotEig = q1.slerp(ratio, q2);
        auto interpolatedRot = coloradar::internal::fromEigenQuat<typename PoseTraits<PoseT>::RotationType>(interpolatedRotEig);
        PoseT interpolatedPose = coloradar::internal::makePose<PoseT>(interpolatedTrans, interpolatedRot);
        interpolatedPoses.push_back(interpolatedPose);
    }
    return interpolatedPoses;
}
References coloradar::internal::makePose(), coloradar::internal::toEigenQuat(), and coloradar::internal::toEigenTrans().
octreeToPcl()
template<Pcl4dPointType PointT, template< PclCloudType > class CloudT> void coloradar::octreeToPcl (const octomap::OcTree & tree, std::shared_ptr< CloudT< PointT > > & cloud)
Definition at line 9 of file basic_utils.hpp.
{
    cloud->clear();
    for (auto it = tree.begin_leafs(), end = tree.end_leafs(); it != end; ++it) {
        PointT point;
        octomap::point3d coords = it.getCoordinate();
        point.x = coords.x();
        point.y = coords.y();
        point.z = coords.z();
        point.intensity = it->getLogOdds();
        cloud->push_back(point);
    }
}
toRadarCloud()
template<typename PointT , template< typename > class CloudT> pcl::PointCloud< RadarPoint >::Ptr coloradar::toRadarCloud (const std::shared_ptr< CloudT< PointT > > cloud)
Definition at line 162 of file basic_utils.hpp.
{
    auto radarCloud = pcl::PointCloud<RadarPoint>::Ptr(new pcl::PointCloud<RadarPoint>());
    radarCloud->header = cloud->header;
    radarCloud->width = cloud->width;
    radarCloud->height = cloud->height;
    radarCloud->is_dense = cloud->is_dense;
    radarCloud->points.resize(cloud->size());
    for (std::size_t i = 0; i < cloud->size(); ++i) {
        const auto& s = (*cloud)[i];
        auto& d = radarCloud->points[i];
        d.x = s.x;
        d.y = s.y;
        d.z = s.z;
        d.intensity = s.intensity;
        d.doppler = 0;
    }
    return radarCloud;
}
validateDeviceName()
bool coloradar::validateDeviceName (const std::string & deviceName)
Definition at line 4 of file device.cpp.
{
    if (deviceName != (new coloradar::CascadeDevice())->name() &&
        deviceName != (new coloradar::SingleChipDevice())->name() &&
        deviceName != (new coloradar::LidarDevice())->name() &&
        deviceName != (new coloradar::ImuDevice())->name() &&
        deviceName != (new coloradar::BaseDevice())->name()) {
        return false;
    }
    return true;
}