Coloradar Library: coloradar::internal Namespace Reference
coloradar::internal Namespace Reference
Classes
struct H5MemType
struct H5MemType< double >
struct H5MemType< float >
struct H5MemType< hsize_t >
struct H5MemType< int16_t >
struct H5MemType< size_t >
struct H5TypeMap
struct H5TypeMap< double >
struct H5TypeMap< float >
struct H5TypeMap< int >
struct H5TypeMap< int16_t >
struct H5TypeMap< int64_t >
struct H5TypeMap< uint16_t >
struct H5TypeMap< uint64_t >
struct H5TypeMap< unsigned int >
Functions
template<typename T >
void saveVectorToHDF5 (const std::string &name, H5::H5File &file, const std::vector< T > &vec)
void savePoseToHDF5 (const std::string &name, H5::H5File &file, const Eigen::Affine3f &pose)
void savePosesToHDF5 (const std::string &name, H5::H5File &file, const std::vector< Eigen::Affine3f > &poses)
void saveCloudToHDF5 (const std::string &name, H5::H5File &file, const std::vector< float > &flatCloud, hsize_t numDims)
void saveCloudsToHDF5 (const std::string &name, H5::H5File &file, const std::vector< float > &flatClouds, hsize_t numFrames, const std::vector< hsize_t > &cloudSizes, hsize_t numDims)
void saveDatacubesToHDF5 (const std::string &name, H5::H5File &file, const std::vector< int16_t > &flatDatacubes, hsize_t numFrames, hsize_t datacubeSize)
void saveHeatmapsToHDF5 (const std::string &name, H5::H5File &file, const std::vector< float > &flatHeatmaps, hsize_t numFrames, int numAzimuthBins, int numRangeBins, int numElevationBins, bool hasDoppler)
template<coloradar::PclCloudType CloudT>
std::vector< float > flattenLidarCloud (const std::shared_ptr< CloudT > &cloud, bool collapseElevation, bool removeIntensity)
template<coloradar::PclCloudType CloudT>
std::vector< float > flattenRadarCloud (const std::shared_ptr< CloudT > &cloud, const int numElevationBins, const bool hasDoppler)
std::vector< double > readH5Timestamps (const H5::H5File &file, const std::string &datasetName)
Eigen::Affine3f readH5Pose (const H5::H5File &file, const std::string &datasetName)
std::vector< Eigen::Affine3f > readH5Poses (const H5::H5File &file, const std::string &datasetName)
std::vector< std::shared_ptr< std::vector< int16_t > > > readH5Datacubes (const H5::H5File &file, const std::string &datasetName)
std::vector< std::shared_ptr< std::vector< float > > > readH5Heatmaps (const H5::H5File &file, const std::string &datasetName)
std::vector< pcl::PointCloud< pcl::PointXYZI >::Ptr > readH5LidarClouds (const H5::H5File &file, const std::string &baseName)
pcl::PointCloud< pcl::PointXYZI >::Ptr readH5SingleCloud (const H5::H5File &file, const std::string &datasetName)
template<class T >
std::vector< T > readH5Vector1D (const H5::H5File &file, const std::string &name)
template<class T >
std::vector< T > readH5Matrix2D (const H5::H5File &file, const std::string &name, size_t &rows, size_t &cols)
std::string toLower (std::string s)
Converts a string to lowercase.
std::optional< int > extractFirstInt (const std::string &input)
Extracts the first integer found in a string.
void checkPathExists (const std::filesystem::path &path)
Checks whether a filesystem path exists.
void createDirectoryIfNotExists (const std::filesystem::path &dirPath)
Ensures that a directory exists. Creates the directory specified by dirPath along with any necessary parent directories if they do not already exist. Does nothing if the directory already exists.
std::vector< std::filesystem::path > readArrayDirectory (const std::filesystem::path &directoryPath, const std::string &filePrefix="", const std::string &fileExtension="", const int &arraySize=-1)
Reads files from a directory and returns them as an ordered array of paths. This function scans the specified directory for files that match a given prefix and extension. It expects file names to follow the pattern: <filePrefix><index><fileExtension>, where <index> is an integer starting from 0. Files are returned in a vector sorted by the index. If arraySize is provided (>= 0), exactly that number of files is expected. If arraySize is -1, all matching files in the directory are used. The function throws a std::runtime_error if:
bool parseBoolYamlKey (const YAML::Node &nodeValue, bool defaultValue)
Parses a YAML node as a boolean. Returns the node value as a bool. If the node is missing, returns the provided default value.
int parseIntYamlKey (const YAML::Node &nodeValue, int defaultValue)
Parses a YAML node as an integer. Returns the node value as an int. If the node is missing, returns the provided default value.
float parseFloatYamlKey (const YAML::Node &nodeValue, float defaultValue)
Parses a YAML node as a float. Returns the node value as a float. If the node is missing, returns the provided default value.
template<coloradar::Pcl4dPointType PointT>
PointT makePoint (const float &x, const float &y, const float &z, const float &i)
Constructs a 4D point object of a PCL type PointT. Creates a point with X, Y, Z coordinates and an intensity value i. Intended for PCL point types that store intensity or extra fields (4D points).
template<coloradar::PclPoseType PoseT>
PoseT makePose (const typename coloradar::PoseTraits< PoseT >::TranslationType &translation, const typename coloradar::PoseTraits< PoseT >::RotationType &rotation)
Constructs a pose object of type PoseT (PCL-style) from translation and rotation components.
template<coloradar::PclPoseType PoseT>
Eigen::Vector3f toEigenTrans (const PoseT &pose)
Extracts an Eigen translation vector from a PCL-style pose object.
template<typename TransT >
TransT fromEigenTrans (const Eigen::Vector3f &r)
Converts an Eigen translation vector to the specified translation type.
template<>
octomath::Vector3 fromEigenTrans (const Eigen::Vector3f &r)
An extension of the template with a specific implementation for octomath::Vector3.
template<coloradar::PclPoseType PoseT>
Eigen::Quaternionf toEigenQuat (const PoseT &pose)
Extracts an Eigen quaternion object from a PCL-style pose object.
template<typename RotationT >
RotationT fromEigenQuat (const Eigen::Quaternionf &r)
Converts an Eigen quaternion to the specified translation type.
template<>
octomath::Quaternion fromEigenQuat (const Eigen::Quaternionf &r)
An extension of the template with a specific implementation for octomath::Quaternion.
template<coloradar::PclPoseType PoseT>
Eigen::Affine3f toEigenPose (const PoseT &pose)
Converts a PCL-style pose object to an Eigen::Affine3f pose.
template<coloradar::PclPoseType PoseT>
PoseT fromEigenPose (const Eigen::Affine3f &pose)
Converts an Eigen::Affine3f pose to the specified PCL-style pose object.
template<coloradar::PointType PointT, coloradar::CloudType CloudT>
std::shared_ptr< CloudT > readLidarPointCloud (const std::filesystem::path &binPath)
Reads a binary point cloud file into a point cloud object. Loads a point cloud from a binary file, where each point is stored as four consecutive float values in the order: X, Y, Z, intensity (I). The function automatically determines the number of points based on the file size.
template<typename PointT , typename CloudT >
void filterFov (std::shared_ptr< CloudT > &cloud, const float &horizontalFov, const float &verticalFov, const float &range)
Filters a point cloud in place based on horizontal and vertical field of view (FOV) and range. Removes points outside the specified horizontal FOV, vertical FOV, or maximum range.
static std::pair< std::vector< float >, std::vector< hsize_t > > readAllDimsFloat (const H5::H5File &file, const std::string &name)
static std::vector< hsize_t > readSizes1D (const H5::H5File &file, const std::string &name)
Function Documentation
checkPathExists()
void coloradar::internal::checkPathExists (const std::filesystem::path & path)
Checks whether a filesystem path exists.
Parameters
path The path to check.
Exceptions
std::filesystem::filesystem_error if the path does not exist.
Definition at line 15 of file internal_utils.cpp.
{
    // std::cout << "Validating path: " << path << std::endl;
    if (!std::filesystem::exists(path)) {
         throw std::filesystem::filesystem_error("Failed to open file", path, std::make_error_code(std::errc::no_such_file_or_directory));
    }
}
createDirectoryIfNotExists()
void coloradar::internal::createDirectoryIfNotExists (const std::filesystem::path & dirPath)
Ensures that a directory exists. Creates the directory specified by dirPath along with any necessary parent directories if they do not already exist. Does nothing if the directory already exists.
Parameters
dirPath The directory path to create.
Exceptions
std::filesystem::filesystem_error if the directory cannot be created.
Definition at line 21 of file internal_utils.cpp.
{
    if (!std::filesystem::exists(dirPath)) {
        std::filesystem::create_directories(dirPath);
    }
}
extractFirstInt()
std::optional< int > coloradar::internal::extractFirstInt (const std::string & input)
Extracts the first integer found in a string.
Parameters
input The input string.
Returns
The first integer found, or std::nullopt if none exists.
Definition at line 6 of file internal_utils.cpp.
{
    static const std::regex re(R"(\d+)");
    std::smatch match;
    if (std::regex_search(input, match, re)) return std::stoi(match.str());
    return std::nullopt;
}
References makePose().
filterFov()
template<typename PointT , typename CloudT > void coloradar::internal::filterFov (std::shared_ptr< CloudT > & cloud, const float & horizontalFov, const float & verticalFov, const float & range)
Filters a point cloud in place based on horizontal and vertical field of view (FOV) and range. Removes points outside the specified horizontal FOV, vertical FOV, or maximum range.
Template Parameters
PointT The point type (e.g., pcl::PointXYZI).
CloudT The cloud container type (e.g., pcl::PointCloud<PointT>).
Parameters
cloud Shared pointer to the input point cloud, which will be modified in place.
horizontalFov Horizontal field of view in degrees (0 < horizontalFov <= 360).
verticalFov Vertical field of view in degrees (0 < verticalFov <= 180).
range Maximum distance from the origin to include points (range > 0).
Exceptions
std::runtime_error if any of the FOV or range parameters are invalid.
Definition at line 112 of file internal_utils.hpp.
{
    if (horizontalFov <= 0 || horizontalFov > 360) {
        throw std::runtime_error("Invalid horizontal FOV value: expected 0 < FOV <= 360, got " + std::to_string(horizontalFov));
    }
    if (verticalFov <= 0 || verticalFov > 180) {
        throw std::runtime_error("Invalid vertical FOV value: expected 0 < FOV <= 180, got " + std::to_string(verticalFov));
    }
    if (range <= 0) {
        throw std::runtime_error("internal::filterFov(): Invalid max range value: expected R > 0, got " + std::to_string(range));
    }
    float horizontalHalfFovRad = horizontalFov / 2 * M_PI / 180.0f;
    float verticalHalfFovRad = verticalFov / 2 * M_PI / 180.0f;
    FovCheck<PointT> checkAzimuth = horizontalFov <= 180 ? checkAzimuthFrontOnly<PointT> : checkAzimuthFrontBack<PointT>;
    CloudT unfilteredCloud(*cloud);
    cloud->clear();
    for (size_t i = 0; i < unfilteredCloud.size(); ++i) {
        const PointT& point = unfilteredCloud[i];
        float distance = std::sqrt(std::pow(getX(point), 2) + std::pow(getY(point), 2) + std::pow(getZ(point), 2));
        if (distance > range) {
            continue;
        }
        float elevationSin = std::sin(verticalHalfFovRad);
        if (checkAzimuth(point, horizontalHalfFovRad) && (getZ(point) <= distance * elevationSin) && (getZ(point) >= -distance * elevationSin)) {
            cloud->push_back(point);
        }
    }
}
flattenLidarCloud()
template<coloradar::PclCloudType CloudT> std::vector< float > coloradar::internal::flattenLidarCloud (const std::shared_ptr< CloudT > & cloud, bool collapseElevation, bool removeIntensity)
Definition at line 30 of file h5_utils.hpp.
{
    size_t numPoints = cloud->size();
    std::vector<float> data;
    if (numPoints == 0) return data;
    size_t numDims = collapseElevation ? 3 : 4;
    if (removeIntensity) numDims--;
    data.resize(numPoints * numDims);
    for (size_t i = 0; i < numPoints; ++i) {
        data[i * numDims + 0] = (*cloud)[i].x;
        data[i * numDims + 1] = (*cloud)[i].y;
        if (collapseElevation) {
            if (!removeIntensity) data[i * numDims + 2] = (*cloud)[i].intensity;
        } else {
            data[i * numDims + 2] = (*cloud)[i].z;
            if (!removeIntensity) data[i * numDims + 3] = (*cloud)[i].intensity;
        }
    }
    return data;
}
References coloradar::collapseElevation().
flattenRadarCloud()
template<coloradar::PclCloudType CloudT> std::vector< float > coloradar::internal::flattenRadarCloud (const std::shared_ptr< CloudT > & cloud, const int numElevationBins, const bool hasDoppler)
Definition at line 53 of file h5_utils.hpp.
{
    size_t numPoints = cloud->size();
    std::vector<float> data;
    if (numPoints == 0) return data;
    bool hasZ = numElevationBins > 0;
    size_t numDims = hasZ ? 5 : 4;
    if (!hasDoppler) numDims -= 1;
    data.resize(numPoints * numDims);
    for (size_t i = 0; i < numPoints; ++i) {
        data[i * numDims + 0] = (*cloud)[i].x;
        data[i * numDims + 1] = (*cloud)[i].y;
        if (hasZ) {
            data[i * numDims + 2] = (*cloud)[i].z;
            data[i * numDims + 3] = (*cloud)[i].intensity;
            if (hasDoppler) data[i * numDims + 4] = (*cloud)[i].doppler;
        } else {
            data[i * numDims + 2] = (*cloud)[i].intensity;
            if (hasDoppler) data[i * numDims + 3] = (*cloud)[i].doppler;
        }
    }
    return data;
}
fromEigenPose()
template<coloradar::PclPoseType PoseT> PoseT coloradar::internal::fromEigenPose (const Eigen::Affine3f & pose)
Converts an Eigen::Affine3f pose to the specified PCL-style pose object.
Converts an Eigen::Affine3f pose to the specified Octomap-style pose object.
Template Parameters
PoseT The PCL pose type (e.g., Eigen::Affine3f).
Parameters
pose The input Eigen::Affine3f.
Returns
PoseT object representing the pose.
Template Parameters
PoseT The Octomap-compatible pose type.
Parameters
pose The input Eigen::Affine3f.
Returns
PoseT object representing the pose.
Definition at line 68 of file internal_utils.hpp.
{ return PoseT(pose); }
fromEigenQuat() [1/2]
template<typename RotationT > RotationT coloradar::internal::fromEigenQuat (const Eigen::Quaternionf & r)
Converts an Eigen quaternion to the specified translation type.
Template Parameters
RotationT The output rotation type.
Parameters
r The input Eigen::Quaternionf rotation.
Returns
Rotation object of type RotationT.
Definition at line 65 of file internal_utils.hpp.
{ return r; }
fromEigenQuat() [2/2]
template<> octomath::Quaternion coloradar::internal::fromEigenQuat (const Eigen::Quaternionf & r)
An extension of the template with a specific implementation for octomath::Quaternion.
Parameters
r The input Eigen::Quaternionf rotation.
Returns
octomath::Quaternion representing the rotation.
Definition at line 73 of file internal_utils.cpp.
{ return octomath::Quaternion(r.w(), r.x(), r.y(), r.z()); }
fromEigenTrans() [1/2]
template<typename TransT > TransT coloradar::internal::fromEigenTrans (const Eigen::Vector3f & r)
Converts an Eigen translation vector to the specified translation type.
Template Parameters
TransT The output translation type.
Parameters
r The input Eigen::Vector3f translation.
Returns
Translation object of type TransT.
Definition at line 64 of file internal_utils.hpp.
{ return r; }
fromEigenTrans() [2/2]
template<> octomath::Vector3 coloradar::internal::fromEigenTrans (const Eigen::Vector3f & r)
An extension of the template with a specific implementation for octomath::Vector3.
Parameters
r The input Eigen::Vector3f translation.
Returns
octomath::Vector3 representing the translation.
Definition at line 72 of file internal_utils.cpp.
{ return octomath::Vector3(r.x(), r.y(), r.z()); }
makePoint()
template<coloradar::Pcl4dPointType PointT> PointT coloradar::internal::makePoint (const float & x, const float & y, const float & z, const float & i)
Constructs a 4D point object of a PCL type PointT. Creates a point with X, Y, Z coordinates and an intensity value i. Intended for PCL point types that store intensity or extra fields (4D points).
Constructs a 3D point object of type PointT. Creates a point with X, Y, Z coordinates. Ignores the intensity value. Intended for generic point types that do not store intensity.
Template Parameters
PointT The PCL 4D point type (e.g., pcl::PointXYZI).
Parameters
x X-coordinate of the point.
y Y-coordinate of the point.
z Z-coordinate of the point.
i Intensity value of the point.
Returns
A PointT object with the specified coordinates and intensity.
Template Parameters
PointT The point type (e.g., pcl::PointXYZ or custom 3D point types).
Parameters
x X-coordinate of the point.
y Y-coordinate of the point.
z Z-coordinate of the point.
i Ignored; included for API consistency with 4D point constructor.
Returns
A PointT object with the specified coordinates.
Definition at line 42 of file internal_utils.hpp.
{ return PointT(x, y, z, i); }
makePose()
template<coloradar::PclPoseType PoseT> PoseT coloradar::internal::makePose (const typename coloradar::PoseTraits< PoseT >::TranslationType & translation, const typename coloradar::PoseTraits< PoseT >::RotationType & rotation)
Constructs a pose object of type PoseT (PCL-style) from translation and rotation components.
Constructs a pose object of type PoseT (Octomap-style) from translation and rotation components.
Template Parameters
PoseT The PCL pose type (e.g., Eigen::Isometry3f).
Parameters
translation The translation vector.
rotation The rotation component (quaternion).
Returns
A PoseT object representing the pose with the specified translation and rotation.
Template Parameters
PoseT The Octomap-compatible pose type.
Parameters
translation The translation vector.
rotation The rotation component (quaternion).
Returns
A PoseT object representing the pose with the specified translation and rotation.
Definition at line 48 of file internal_utils.hpp.
{
    PoseT pose = PoseT::Identity();
    pose.translation() = translation;
    pose.linear() = rotation.toRotationMatrix();
    return pose;
}
parseBoolYamlKey()
bool coloradar::internal::parseBoolYamlKey (const YAML::Node & nodeValue, bool defaultValue)
Parses a YAML node as a boolean. Returns the node value as a bool. If the node is missing, returns the provided default value.
Parameters
nodeValue The YAML node to parse.
defaultValue Value to return if the node is missing.
Returns
The boolean value from the YAML node or defaultValue.
Exceptions
std::runtime_error if the node exists but is not a valid bool.
Definition at line 76 of file internal_utils.cpp.
{
    if (!nodeValue) {
        return defaultValue;
    }
    try {
        return nodeValue.as<bool>();
    } catch (const YAML::BadConversion &) {
        throw std::runtime_error("Malformed bool value");
    }
}
parseFloatYamlKey()
float coloradar::internal::parseFloatYamlKey (const YAML::Node & nodeValue, float defaultValue)
Parses a YAML node as a float. Returns the node value as a float. If the node is missing, returns the provided default value.
Parameters
nodeValue The YAML node to parse.
defaultValue Value to return if the node is missing.
Returns
The float value from the YAML node or defaultValue.
Exceptions
std::runtime_error if the node exists but is not a valid float.
Definition at line 98 of file internal_utils.cpp.
{
    if (!nodeValue) {
        return defaultValue;
    }
    try {
        return nodeValue.as<float>();
    } catch (const YAML::BadConversion &) {
        throw std::runtime_error("Malformed float value");
    }
}
parseIntYamlKey()
int coloradar::internal::parseIntYamlKey (const YAML::Node & nodeValue, int defaultValue)
Parses a YAML node as an integer. Returns the node value as an int. If the node is missing, returns the provided default value.
Parameters
nodeValue The YAML node to parse.
defaultValue Value to return if the node is missing.
Returns
The integer value from the YAML node or defaultValue.
Exceptions
std::runtime_error if the node exists but is not a valid int.
Definition at line 87 of file internal_utils.cpp.
{
    if (!nodeValue) {
        return defaultValue;
    }
    try {
        return nodeValue.as<int>();
    } catch (const YAML::BadConversion &) {
        throw std::runtime_error("Malformed int value");
    }
}
readAllDimsFloat()
static std::pair< std::vector< float >, std::vector< hsize_t > > coloradar::internal::readAllDimsFloat (const H5::H5File & file, const std::string & name) inline static
Definition at line 162 of file h5_utils.cpp.
{
    H5::DataSet ds = file.openDataSet(name);
    H5::DataSpace sp = ds.getSpace();
    int rank = sp.getSimpleExtentNdims();
    if (rank < 1) throw std::runtime_error(name + ": expected rank >= 1");
    std::vector<hsize_t> dims(static_cast<size_t>(rank));
    sp.getSimpleExtentDims(dims.data());
    size_t total = 1;
    for (auto d : dims) total *= static_cast<size_t>(d);
    std::vector<float> flat(total);
    if (total) ds.read(flat.data(), H5::PredType::NATIVE_FLOAT);
    return {std::move(flat), std::move(dims)};
}
References makePose().
readArrayDirectory()
std::vector< std::filesystem::path > coloradar::internal::readArrayDirectory (const std::filesystem::path & directoryPath, const std::string & filePrefix = "", const std::string & fileExtension = "", const int & arraySize = -1)
Reads files from a directory and returns them as an ordered array of paths. This function scans the specified directory for files that match a given prefix and extension. It expects file names to follow the pattern: <filePrefix><index><fileExtension>, where <index> is an integer starting from 0. Files are returned in a vector sorted by the index. If arraySize is provided (>= 0), exactly that number of files is expected. If arraySize is -1, all matching files in the directory are used. The function throws a std::runtime_error if:
The number of matching files does not equal the expected arraySize.
Any file index in the expected range is missing. Malformed file names (non-integer indices) are ignored.
Parameters
directoryPath Path to the directory to scan.
filePrefix Optional prefix that file names must start with. Default is empty string (matches all).
fileExtension Optional file extension to filter by (with or without leading dot). Default is empty string (matches all).
arraySize Expected number of files in the array. Set to -1 to use all matching files.
Returns
A vector of std::filesystem::path objects, ordered by file index.
Exceptions
std::runtime_error if the number of files found does not match arraySize, or if any expected indexed file is missing.
Definition at line 26 of file internal_utils.cpp.
  {
    std::string extension = (fileExtension[0] == '.') ? fileExtension : "." + fileExtension;
    std::map<int, std::filesystem::path> filePaths;
    // List files
    for (const auto& entry : std::filesystem::directory_iterator(directoryPath)) {
        if (entry.path().extension() == extension) {                                // Empty extension is ok
            std::string filename = entry.path().stem().string();                    // Name string without extension
            if (filename.rfind(filePrefix, 0) == 0) {                               // Make sure it starts with prefix, empty prefix is ok
                try {
                    int index = std::stoi(filename.substr(filePrefix.size()));      // Extract file index
                    filePaths[index] = entry.path();
                } catch (const std::exception&) {
                    continue;                                                       // Ignore malformed filenames
                }
            }
        }
    }
    size_t numFiles = arraySize >= 0 ? arraySize : filePaths.size();
    if (numFiles != filePaths.size()) {
        throw std::runtime_error(
            "Expected " + std::to_string(numFiles) + " files (prefix '" + filePrefix +
            "', extension '" + extension + "'), but found " + std::to_string(filePaths.size()) +
            " in directory: " + directoryPath.string());
    }
    std::vector<std::filesystem::path> files(numFiles);
    for (int i = 0; i < numFiles; ++i) {
        if (!filePaths.count(i)) {
            throw std::runtime_error("Missing expected file: '" + filePrefix + std::to_string(i) + extension + "' in directory: " + directoryPath.string());
        }
        files[i] = filePaths[i];
    }
    return files;
}
readH5Datacubes()
std::vector< std::shared_ptr< std::vector< int16_t > > > coloradar::internal::readH5Datacubes (const H5::H5File & file, const std::string & datasetName)
Definition at line 147 of file h5_utils.cpp.
{
    size_t rows=0, cols=0;
    // Writer used INT16 data with a FLOAT declared type; HDF5 will convert on read.
    auto flat = readH5Matrix2D<int16_t>(file, datasetName, rows, cols);
    std::vector<std::shared_ptr<std::vector<int16_t>>> frames;
    frames.reserve(rows);
    for (size_t i = 0; i < rows; ++i) {
        auto vec = std::make_shared<std::vector<int16_t>>(cols);
        std::copy_n(flat.data() + i*cols, cols, vec->data());
        frames.push_back(std::move(vec));
    }
    return frames;
}
References makePose().
readH5Heatmaps()
std::vector< std::shared_ptr< std::vector< float > > > coloradar::internal::readH5Heatmaps (const H5::H5File & file, const std::string & datasetName)
Definition at line 181 of file h5_utils.cpp.
{
    auto [flat, dims] = readAllDimsFloat(file, datasetName);
    if (dims.empty()) return {};
    const size_t numFrames = static_cast<size_t>(dims[0]);
    size_t perFrame = 1;
    for (size_t i = 1; i < dims.size(); ++i) perFrame *= static_cast<size_t>(dims[i]);
    if (perFrame == 0) return {};
    std::vector<std::shared_ptr<std::vector<float>>> frames;
    frames.reserve(numFrames);
    for (size_t i = 0; i < numFrames; ++i) {
        auto vec = std::make_shared<std::vector<float>>(perFrame);
        std::copy_n(flat.data() + i*perFrame, perFrame, vec->data());
        frames.push_back(std::move(vec));
    }
    return frames;
}
References makePose(), and readAllDimsFloat().
readH5LidarClouds()
std::vector< pcl::PointCloud< pcl::PointXYZI >::Ptr > coloradar::internal::readH5LidarClouds (const H5::H5File & file, const std::string & baseName)
Definition at line 206 of file h5_utils.cpp.
{
    size_t rows=0, D=0;
    auto flat = readH5Matrix2D<float>(file, baseName, rows, D);
    if (D < 3) throw std::runtime_error("readH5LidarClouds(): expected 3 or more columns (XYZ or XYZ+I) in dataset " + baseName);
    auto sizes = readSizes1D(file, baseName + "_sizes");
    size_t totalPoints = std::accumulate(sizes.begin(), sizes.end(), static_cast<size_t>(0));
    if (totalPoints != rows) throw std::runtime_error("readH5LidarClouds(): total points mismatch with sizes array in dataset " + baseName);
    std::vector<pcl::PointCloud<pcl::PointXYZI>::Ptr> out;
    out.reserve(sizes.size());
    size_t off = 0;
    for (hsize_t n : sizes) {
        auto cloud = std::make_shared<pcl::PointCloud<pcl::PointXYZI>>();
        cloud->resize(static_cast<size_t>(n));
        for (size_t k = 0; k < static_cast<size_t>(n); ++k) {
            pcl::PointXYZI p{};
            p.x = flat[(off+k)*D + 0];
            p.y = flat[(off+k)*D + 1];
            p.z = (D >= 3) ? flat[(off+k)*D + 2] : 0.f;
            p.intensity = (D >= 4) ? flat[(off+k)*D + 3] : 0.f;
            (*cloud)[k] = p;
        }
        off += static_cast<size_t>(n);
        out.push_back(cloud);
    }
    return out;
}
References makePose(), and readSizes1D().
readH5Matrix2D()
template<class T > std::vector< T > coloradar::internal::readH5Matrix2D (const H5::H5File & file, const std::string & name, size_t & rows, size_t & cols) inline
Definition at line 103 of file h5_utils.hpp.
{
    H5::DataSet ds = file.openDataSet(name);
    H5::DataSpace sp = ds.getSpace();
    if (sp.getSimpleExtentNdims() != 2) {
        throw std::runtime_error(name + ": expected rank-2 dataset");
    }
    hsize_t dims[2]{};
    sp.getSimpleExtentDims(dims);
    rows = static_cast<size_t>(dims[0]);
    cols = static_cast<size_t>(dims[1]);
    std::vector<T> buf(rows * cols);
    if (rows * cols) {
        ds.read(buf.data(), H5MemType<T>::get());
    }
    return buf;
}
readH5Pose()
Eigen::Affine3f coloradar::internal::readH5Pose (const H5::H5File & file, const std::string & datasetName)
Definition at line 110 of file h5_utils.cpp.
{
    H5::DataSet ds = file.openDataSet(datasetName);
    H5::DataSpace sp = ds.getSpace();
    int rank = sp.getSimpleExtentNdims();
    if (rank != 1) throw std::runtime_error(datasetName + ": expected rank-1 dataset (length 7).");
    hsize_t dim = 0;
    sp.getSimpleExtentDims(&dim, nullptr);
    if (dim != 7) throw std::runtime_error(datasetName + ": expected 7 elements [x y z qx qy qz qw], got " + std::to_string(dim));
    std::array<float, 7> poseData{};
    ds.read(poseData.data(), H5::PredType::NATIVE_FLOAT);
    Eigen::Vector3f translation(poseData[0], poseData[1], poseData[2]);
    Eigen::Quaternionf rotation(poseData[6], poseData[3], poseData[4], poseData[5]); // (w, x, y, z)
    Eigen::Affine3f pose = Eigen::Translation3f(translation) * rotation;
    return pose;
}
References makePose().
readH5Poses()
std::vector< Eigen::Affine3f > coloradar::internal::readH5Poses (const H5::H5File & file, const std::string & datasetName)
Definition at line 128 of file h5_utils.cpp.
{
    size_t rows=0, cols=0;
    auto flat = readH5Matrix2D<float>(file, datasetName, rows, cols);
    if (cols != 7) {
        throw std::runtime_error(datasetName + ": expected pose rows of length 7 [x y z qx qy qz qw]");
    }
    std::vector<Eigen::Affine3f> out;
    out.reserve(rows);
    for (size_t i = 0; i < rows; ++i) {
        const float* p = &flat[i * 7];
        Eigen::Vector3f translation(p[0], p[1], p[2]);
        Eigen::Quaternionf rotation(p[6], p[3], p[4], p[5]);
        Eigen::Affine3f pose = Eigen::Translation3f(translation) * rotation;
        out.push_back(pose);
    }
    return out;
}
References makePose().
readH5SingleCloud()
pcl::PointCloud< pcl::PointXYZI >::Ptr coloradar::internal::readH5SingleCloud (const H5::H5File & file, const std::string & datasetName)
Definition at line 236 of file h5_utils.cpp.
{
    size_t rows=0, D=0;
    auto flat = readH5Matrix2D<float>(file, datasetName, rows, D);
    if (D < 3) throw std::runtime_error("readH5SingleCloud(): expected 3 or more columns (XYZ or XYZ+I) in dataset " + datasetName);
    auto cloud = std::make_shared<pcl::PointCloud<pcl::PointXYZI>>();
    cloud->resize(rows);
    for (size_t i = 0; i < rows; ++i) {
        pcl::PointXYZI p{};
        p.x = flat[i*D + 0];
        p.y = flat[i*D + 1];
        p.z = (D >= 3) ? flat[i*D + 2] : 0.f;
        p.intensity = (D >= 4) ? flat[i*D + 3] : 0.f;
        (*cloud)[i] = p;
    }
    return cloud;
}
References makePose().
readH5Timestamps()
std::vector< double > coloradar::internal::readH5Timestamps (const H5::H5File & file, const std::string & datasetName)
Definition at line 105 of file h5_utils.cpp.
{
    return readH5Vector1D<double>(file, datasetName);
}
References makePose().
readH5Vector1D()
template<class T > std::vector< T > coloradar::internal::readH5Vector1D (const H5::H5File & file, const std::string & name) inline
Definition at line 87 of file h5_utils.hpp.
{
    H5::DataSet ds = file.openDataSet(name);
    H5::DataSpace sp = ds.getSpace();
    if (sp.getSimpleExtentNdims() != 1) {
        throw std::runtime_error(name + ": expected rank-1 dataset");
    }
    hsize_t dim{};
    sp.getSimpleExtentDims(&dim);
    std::vector<T> v(static_cast<size_t>(dim));
    if (dim > 0) {
        ds.read(v.data(), H5MemType<T>::get());
    }
    return v;
}
readLidarPointCloud()
template<coloradar::PointType PointT, coloradar::CloudType CloudT> std::shared_ptr< CloudT > coloradar::internal::readLidarPointCloud (const std::filesystem::path & binPath)
Reads a binary point cloud file into a point cloud object. Loads a point cloud from a binary file, where each point is stored as four consecutive float values in the order: X, Y, Z, intensity (I). The function automatically determines the number of points based on the file size.
Template Parameters
PointT The point type (e.g., pcl::PointXYZI) to store in the cloud.
CloudT The cloud container type (e.g., pcl::PointCloud<PointT>).
Parameters
binPath Path to the binary lidar point cloud file.
Returns
A shared pointer to a CloudT object containing the loaded points.
Exceptions
std::filesystem::filesystem_error if the file path does not exist.
std::runtime_error if the file cannot be opened, if reading fails, or if the resulting point cloud is empty.
Definition at line 82 of file internal_utils.hpp.
{
    coloradar::internal::checkPathExists(binPath);
    std::ifstream infile(binPath, std::ios::binary);
    if (!infile) {
        throw std::runtime_error("Failed to open file: " + binPath.string());
    }
    infile.seekg(0, std::ios::end);
    size_t numPoints = infile.tellg() / (4 * sizeof(float));
    infile.seekg(0, std::ios::beg);
    auto cloud = std::make_shared<CloudT>();
    cloud->reserve(numPoints);
    for (size_t j = 0; j < numPoints; ++j) {
        float x, y, z, i;
        infile.read(reinterpret_cast<char*>(&x), sizeof(float));
        infile.read(reinterpret_cast<char*>(&y), sizeof(float));
        infile.read(reinterpret_cast<char*>(&z), sizeof(float));
        infile.read(reinterpret_cast<char*>(&i), sizeof(float));
        PointT point = coloradar::internal::makePoint<PointT>(x, y, z, i);
        cloud->push_back(point);
    }
    if (cloud->size() < 1) {
        throw std::runtime_error("Failed to read or empty point cloud: " + binPath.string());
    }
    return cloud;
}
References checkPathExists(), and makePose().
readSizes1D()
static std::vector< hsize_t > coloradar::internal::readSizes1D (const H5::H5File & file, const std::string & name) inline static
Definition at line 202 of file h5_utils.cpp.
{
    return readH5Vector1D<hsize_t>(file, name);
}
References makePose().
saveCloudsToHDF5()
void coloradar::internal::saveCloudsToHDF5 (const std::string & name, H5::H5File & file, const std::vector< float > & flatClouds, hsize_t numFrames, const std::vector< hsize_t > & cloudSizes, hsize_t numDims)
Definition at line 59 of file h5_utils.cpp.
{
    if (cloudSizes.size() != numFrames) throw std::invalid_argument("saveCloudsToHDF5(): expected cloudSizes.size() == numFrames, got " + std::to_string(cloudSizes.size()) + " != " + std::to_string(numFrames));
    if (numDims == 0) throw std::invalid_argument("saveCloudsToHDF5(): expected numDims > 0, got " + std::to_string(numDims));
    std::string sizeDatasetName = name + "_sizes";
    hsize_t sizeDims[1] = {numFrames};
    H5::DataSpace sizeDataspace(1, sizeDims);
    H5::DataSet sizeDataset = file.createDataSet(sizeDatasetName, H5::PredType::NATIVE_HSIZE, sizeDataspace);
    sizeDataset.write(cloudSizes.data(), H5::PredType::NATIVE_HSIZE);
    hsize_t totalPoints = std::accumulate(cloudSizes.begin(), cloudSizes.end(), hsize_t(0));
    hsize_t cloudDims[2] = {totalPoints, numDims};
    H5::DataSpace cloudSpace(2, cloudDims);
    H5::DataSet cloudDataset = file.createDataSet(name, H5::PredType::NATIVE_FLOAT, cloudSpace);
    if (!flatClouds.empty()) cloudDataset.write(flatClouds.data(), H5::PredType::NATIVE_FLOAT);
    cloudDataset.close();
    cloudSpace.close();
}
References makePose().
saveCloudToHDF5()
void coloradar::internal::saveCloudToHDF5 (const std::string & name, H5::H5File & file, const std::vector< float > & flatCloud, hsize_t numDims)
Definition at line 46 of file h5_utils.cpp.
{
    if (numDims == 0) throw std::invalid_argument("saveCloudToHDF5(): expected numDims > 0, got " + std::to_string(numDims));
    if (flatCloud.size() % numDims != 0) throw std::invalid_argument("saveCloudToHDF5(): flatCloud.size() must be divisible by numDims, got " + std::to_string(flatCloud.size()) + " and " + std::to_string(numDims));
    const hsize_t numPoints = flatCloud.size() / numDims;
    const hsize_t dims[2] = { numPoints, numDims };
    H5::DataSpace space(2, dims);
    H5::DataSet ds = file.createDataSet(name, H5::PredType::NATIVE_FLOAT, space);
    if (numPoints > 0) ds.write(flatCloud.data(), H5::PredType::NATIVE_FLOAT);
    ds.close();
    space.close();
}
References makePose().
saveDatacubesToHDF5()
void coloradar::internal::saveDatacubesToHDF5 (const std::string & name, H5::H5File & file, const std::vector< int16_t > & flatDatacubes, hsize_t numFrames, hsize_t datacubeSize)
Definition at line 78 of file h5_utils.cpp.
{
    std::vector<hsize_t> dims = {numFrames, datacubeSize};
    H5::DataSpace dataspace(dims.size(), dims.data());
    H5::PredType datatype = H5::PredType::NATIVE_FLOAT;
    H5::DataSet dataset = file.createDataSet(name, datatype, dataspace);
    dataset.write(flatDatacubes.data(), H5::PredType::NATIVE_INT16);
    dataset.close();
    dataspace.close();
}
References makePose().
saveHeatmapsToHDF5()
void coloradar::internal::saveHeatmapsToHDF5 (const std::string & name, H5::H5File & file, const std::vector< float > & flatHeatmaps, hsize_t numFrames, int numAzimuthBins, int numRangeBins, int numElevationBins, bool hasDoppler)
Definition at line 89 of file h5_utils.cpp.
{
    std::vector<hsize_t> dims = {numFrames};
    if (numElevationBins > 1) dims.push_back(numElevationBins);
    dims.push_back(numAzimuthBins);
    dims.push_back(numRangeBins);
    if (hasDoppler) dims.push_back(2);
    H5::DataSpace space(dims.size(), dims.data());
    H5::DataSet dataset = file.createDataSet(name, H5::PredType::NATIVE_FLOAT, space);
    if (!flatHeatmaps.empty()) dataset.write(flatHeatmaps.data(), H5::PredType::NATIVE_FLOAT);
    dataset.close();
    space.close();
}
References makePose().
savePosesToHDF5()
void coloradar::internal::savePosesToHDF5 (const std::string & name, H5::H5File & file, const std::vector< Eigen::Affine3f > & poses)
Definition at line 23 of file h5_utils.cpp.
{
    const hsize_t dims[2] = { poses.size(), 7 };
    H5::DataSpace space(2, dims);
    H5::DataSet ds = file.createDataSet(name, H5::PredType::NATIVE_FLOAT, space);
    std::vector<float> buf(poses.size() * 7);
    size_t idx = 0;
    for (const auto& p : poses) {
        const Eigen::Vector3f t = p.translation();
        const Eigen::Quaternionf q(p.rotation());
        buf[idx++] = t.x();
        buf[idx++] = t.y();
        buf[idx++] = t.z();
        buf[idx++] = q.x();
        buf[idx++] = q.y();
        buf[idx++] = q.z();
        buf[idx++] = q.w();
    }
    ds.write(buf.data(), H5::PredType::NATIVE_FLOAT);
    ds.close();
    space.close();
}
References makePose().
savePoseToHDF5()
void coloradar::internal::savePoseToHDF5 (const std::string & name, H5::H5File & file, const Eigen::Affine3f & pose)
Definition at line 8 of file h5_utils.cpp.
{
    const hsize_t dims[1] = { 7 };
    H5::DataSpace space(1, dims);
    H5::DataSet ds = file.createDataSet(name, H5::PredType::NATIVE_FLOAT, space);
    float buf[7];
    const Eigen::Vector3f t = pose.translation();
    const Eigen::Quaternionf q(pose.rotation());
    buf[0] = t.x(); buf[1] = t.y(); buf[2] = t.z();
    buf[3] = q.x(); buf[4] = q.y(); buf[5] = q.z(); buf[6] = q.w();
    ds.write(buf, H5::PredType::NATIVE_FLOAT);
    ds.close();
    space.close();
}
References makePose().
saveVectorToHDF5()
template<typename T > void coloradar::internal::saveVectorToHDF5 (const std::string & name, H5::H5File & file, const std::vector< T > & vec)
Definition at line 19 of file h5_utils.hpp.
{
    const hsize_t dims[1] = { vec.size() };
    H5::DataSpace space(1, dims);
    H5::DataSet dataset = file.createDataSet(name, H5TypeMap<T>::type(), space);
    if (!vec.empty()) dataset.write(vec.data(), H5TypeMap<T>::type());
    dataset.close();
    space.close();
}
toEigenPose()
template<coloradar::PclPoseType PoseT> Eigen::Affine3f coloradar::internal::toEigenPose (const PoseT & pose)
Converts a PCL-style pose object to an Eigen::Affine3f pose.
Converts an Octomap-style pose object to an Eigen::Affine3f pose.
Template Parameters
PoseT The PCL pose type (e.g., Eigen::Affine3f).
Parameters
pose The input pose.
Returns
Eigen::Affine3f representing the pose.
Template Parameters
PoseT The Octomap-compatible pose type.
Parameters
pose The input pose.
Returns
Eigen::Affine3f representing the pose.
Definition at line 67 of file internal_utils.hpp.
{ return Eigen::Affine3f(pose); }
toEigenQuat()
template<coloradar::PclPoseType PoseT> Eigen::Quaternionf coloradar::internal::toEigenQuat (const PoseT & pose)
Extracts an Eigen quaternion object from a PCL-style pose object.
Extracts an Eigen quaternion object from a Octomap-style pose object.
Template Parameters
PoseT The PCL pose type (e.g., Eigen::Affine3f).
Parameters
pose The input pose.
Returns
Eigen::Quaternionf representing the rotation.
Template Parameters
PoseT The Octomap-compatible pose type.
Parameters
pose The input pose.
Returns
Eigen::Quaternionf representing the rotation.
Definition at line 60 of file internal_utils.hpp.
{ return Eigen::Quaternionf(pose.rotation()); }
toEigenTrans()
template<coloradar::PclPoseType PoseT> Eigen::Vector3f coloradar::internal::toEigenTrans (const PoseT & pose)
Extracts an Eigen translation vector from a PCL-style pose object.
Extracts an Eigen translation vector from a Octomap-style pose object.
Template Parameters
PoseT The PCL pose type (e.g., Eigen::Affine3f).
Parameters
pose The input pose.
Returns
Eigen::Vector3f containing the translation (x, y, z).
Template Parameters
PoseT The Octomap-compatible pose type.
Parameters
pose The input pose.
Returns
Eigen::Vector3f containing the translation (x, y, z).
Definition at line 59 of file internal_utils.hpp.
{ return Eigen::Vector3f(pose.translation()); }
toLower()
std::string coloradar::internal::toLower (std::string s)
Converts a string to lowercase.
Parameters
s The input string.
Returns
A lowercase copy of the input string.
Definition at line 66 of file internal_utils.cpp.
{
    for (auto& c : s) c = std::tolower(c);
    return s;
}