global:
  runs: all
  destination_file: dataset.h5
  export_transforms: True


devices:
  base_frame:
    export_poses: True
    export_timestamps: True
    
  cascade_radar:
    export_poses: True
    export_timestamps: True
    export_heatmaps: True

    fov_azimuth_idx: 63
    fov_elevation_idx: 4
    range_meters: 7
    remove_doppler_dim: True

  lidar:
    export_poses: True
    export_timestamps: True
    export_map: True
    export_map_samples: True

    allow_resample: True
    force_resample: True
    save_samples: True
    center_sensor: cascade_radar
    map_sample_fov:
      horizontal_degrees_total: 156.6
      vertical_degrees_total: 32.2
      range_meters: 7
