ros_versions:
  noetic:
    ubuntu: 20.04
    gcc: 10
    boost: 1.78.0
    pcl: 1.12.0
    pybind: 2.10.4
  humble:
    ubuntu: 22.04
    gcc: 12
    boost: 1.78.0
    pcl:
    pybind:
  jazzy:
    ubuntu: 24.04
    gcc: 12
    boost:
    pcl:
    pybind:
