# Change base image accordingly to your setup
x-base-image: &base_image ghcr.io/arpg/coloradar-lib:12.6-jazzy


services:
  base:
    image: *base_image
    environment:
      - PYTHONUNBUFFERED=1
      - DOCKER_DATASET_VOLUME_PATH=/data/coloradar

  get_export_config_template:
    extends:
      service: base
    volumes:
      # No adjustment necessary
      - .:/export
    command: cp /src/coloradar_lib/export-config-template.yaml /export/export-config.yaml

  build_maps:
    extends:
      service: base
    working_dir: /app
    volumes:
      # <local dataset directory>:/<container dataset directory>
      - ~/data/coloradar:/data/coloradar
      # No adjustment necessary
      - ./scripts/build_maps.py:/app/build_maps.py
    command: python3 build_maps.py

  sample_maps:
    extends:
      service: base
    working_dir: /app
    volumes:
      # <local dataset directory>:/<container dataset directory>
      - ~/data/coloradar:/data/coloradar
      # No adjustment necessary
      - ./scripts/sample_maps.py:/app/sample_maps.py
    command: python3 sample_maps.py

  export_dataset:
    extends:
      service: base
    working_dir: /app
    volumes:
      # <local dataset directory>:/<container dataset directory>
      - ~/coloradar:/data/coloradar
      # <local export directory>:/<container export directory>
      - .:/export
    command: python3 /export/scripts/export_dataset.py

  visualize_run:
    extends:
      service: base
    working_dir: /app
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # <local dataset directory>:/<container dataset directory>
      - ~/coloradar:/data/coloradar
      # No adjustment necessary
      - ./scripts/visualize_run.py:/app/visualize_run.py
      - .:/export
    # specify run name
    command: python3 visualize_run.py --name edgar_classroom_run0 --step 10

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.demo
      args:
        BASE_IMAGE: *base_image
    volumes:
      # <local dataset directory>:/<container dataset directory>
      - ~/coloradar:/data/coloradar
      # <local working directory>:/<container working directory>
      - .:/app
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

