name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros: ["none", "jazzy"]
        cuda: ["none", "12.6", "12.8"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Free Up Disk Space
        run: |
          sudo apt-get clean
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /var/lib/apt/lists/*
          sudo rm -rf /var/lib/dpkg/info/*
          sudo rm -rf /usr/share/man/*
          sudo rm -rf /usr/share/doc/*
          docker system prune -af --volumes
          df -h

      - name: Run Tests
        run: python3 utils/tests.py

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Cache Docker Layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: docker-buildx-${{ matrix.ros }}-${{ matrix.cuda }}-${{ github.run_id }}
          restore-keys: |
            docker-buildx-${{ matrix.ros }}-${{ matrix.cuda }}
            docker-buildx-

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          DOCKER_BUILDKIT=1 \
          DOCKER_PUSH_IMAGES=true \
          python3 build.py --ros "${{ matrix.ros }}" --cuda "${{ matrix.cuda }}"

      - name: Logout from Docker Hub
        run: docker logout

